/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:28 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using C3WizardLayer.DataObjects;
using C3WizardLayer.DataObjects.Interfaces;
using C3WizardLayer.BusinessObjects.Interfaces;

namespace C3WizardLayer.BusinessObjects
{
    ///<Summary>
    ///Class definition
    ///This is the definition of the class BLCity.
    ///</Summary>
    public partial class BLCity : C3WizardLayerConn_BaseBusiness
    {
        #region member variables
        protected Int32? _sid;
        protected Int32? _cid;
        protected string _name;
        protected string _description;
        protected Int32? _insertedBy;
        protected DateTime? _insertedOn;
        protected string _insertedMachineInfo;
        protected Int32? _updatedBy;
        protected DateTime? _updatedOn;
        protected string _updatedMachineInfo;
        protected bool? _isActive;
        protected string _deletable;
        protected bool _isDirty = false;
        /*collection member objects*******************/
        /*********************************************/
        #endregion

        #region class methods
        ///<Summary>
        ///Constructor
        ///This is the default constructor
        ///</Summary>
        ///<returns>
        ///void
        ///</returns>
        ///<parameters>
        ///
        ///</parameters>
        public BLCity()
        {
        }


        protected internal BLCity(DLCity DLCity)
        {
            try
            {
                _sid = DLCity.SId;
                _cid = DLCity.CId;
                _name = DLCity.Name;
                _description = DLCity.Description;
                _insertedBy = DLCity.InsertedBy;
                _insertedOn = DLCity.InsertedOn;
                _insertedMachineInfo = DLCity.InsertedMachineInfo;
                _updatedBy = DLCity.UpdatedBy;
                _updatedOn = DLCity.UpdatedOn;
                _updatedMachineInfo = DLCity.UpdatedMachineInfo;
                _isActive = DLCity.IsActive;
                _deletable = DLCity.Deletable;
            }
            catch
            {
                throw;
            }
        }


        public static IList<BLCity> SECRoleCollection()
        {
            try
            {
                IList<BLCity> blSECRoleCollection = new List<BLCity>();
                IList<DLCity> dlSECRoleCollection = DLCity.SelectAll();

                foreach (DLCity dlSECRole in dlSECRoleCollection)
                    blSECRoleCollection.Add(new BLCity(dlSECRole));

                return blSECRoleCollection;
            }
            catch
            {
                throw;
            }
        }


        #endregion

        #region member properties

        public virtual Int32? SId
        {
            get
            {
                return _sid;
            }
            set
            {
                _sid = value;
                _isDirty = true;
            }
        }

        public virtual Int32? CId
        {
            get
            {
                return _cid;
            }
            set
            {
                _cid = value;
                _isDirty = true;
            }
        }

        public virtual string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
                _isDirty = true;
            }
        }

        public virtual string Description
        {
            get
            {
                return _description;
            }
            set
            {
                _description = value;
                _isDirty = true;
            }
        }

        public virtual Int32? InsertedBy
        {
            get
            {
                return _insertedBy;
            }
            set
            {
                _insertedBy = value;
                _isDirty = true;
            }
        }

        public virtual DateTime? InsertedOn
        {
            get
            {
                return _insertedOn;
            }
            set
            {
                _insertedOn = value;
                _isDirty = true;
            }
        }

        public virtual string InsertedMachineInfo
        {
            get
            {
                return _insertedMachineInfo;
            }
            set
            {
                _insertedMachineInfo = value;
                _isDirty = true;
            }
        }

        public virtual Int32? UpdatedBy
        {
            get
            {
                return _updatedBy;
            }
            set
            {
                _updatedBy = value;
                _isDirty = true;
            }
        }

        public virtual DateTime? UpdatedOn
        {
            get
            {
                return _updatedOn;
            }
            set
            {
                _updatedOn = value;
                _isDirty = true;
            }
        }

        public virtual string UpdatedMachineInfo
        {
            get
            {
                return _updatedMachineInfo;
            }
            set
            {
                _updatedMachineInfo = value;
                _isDirty = true;
            }
        }

        public virtual bool? IsActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                _isActive = value;
                _isDirty = true;
            }
        }

        public virtual string Deletable
        {
            get
            {
                return _deletable;
            }
            set
            {
                _deletable = value;
                _isDirty = true;
            }
        }

        public virtual object Repository
        {
            get { return null; }
            set { }
        }

        public virtual bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            set
            {
                _isDirty = value;
            }
        }
        #endregion
    }
}
