/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using C3WizardLayer.DataObjects;
using C3WizardLayer.DataObjects.Interfaces;
using C3WizardLayer.BusinessObjects.Interfaces;

namespace C3WizardLayer.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BLMasterIncCodes.
	///</Summary>
	public partial class BLMasterIncCodes : C3WizardLayerConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _incCodeID;
		protected string _incCode;
		protected string _description;
		protected decimal? _dfltNum;
		protected decimal? _dfltRate;
		protected decimal? _dfltHours;
		protected Int32? _dfltAcct;
		protected string _dfltDept;
		protected string _incType;
		protected Int32? _dfltLoIncAmt;
		protected Int32? _dfltHiIncAmt;
		protected string _nonQual;
		protected string _dfltAccountType;
		protected Int32? _insertedBy;
		protected DateTime? _insertedOn;
		protected string _insertedMachineInfo;
		protected Int32? _updatedBy;
		protected DateTime? _updatedOn;
		protected string _updatedMachineInfo;
		protected bool? _isActive;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BLMasterIncCodes()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 incCodeID
		///</parameters>
		public BLMasterIncCodes(Int32 incCodeID)
		{
			try
			{
				DLMasterIncCodes dlMasterIncCodes = DLMasterIncCodes.SelectOne(incCodeID);
				_incCodeID = dlMasterIncCodes.IncCodeID;
				_incCode = dlMasterIncCodes.IncCode;
				_description = dlMasterIncCodes.Description;
				_dfltNum = dlMasterIncCodes.DfltNum;
				_dfltRate = dlMasterIncCodes.DfltRate;
				_dfltHours = dlMasterIncCodes.DfltHours;
				_dfltAcct = dlMasterIncCodes.DfltAcct;
				_dfltDept = dlMasterIncCodes.DfltDept;
				_incType = dlMasterIncCodes.IncType;
				_dfltLoIncAmt = dlMasterIncCodes.DfltLoIncAmt;
				_dfltHiIncAmt = dlMasterIncCodes.DfltHiIncAmt;
				_nonQual = dlMasterIncCodes.NonQual;
				_dfltAccountType = dlMasterIncCodes.DfltAccountType;
				_insertedBy = dlMasterIncCodes.InsertedBy;
				_insertedOn = dlMasterIncCodes.InsertedOn;
				_insertedMachineInfo = dlMasterIncCodes.InsertedMachineInfo;
				_updatedBy = dlMasterIncCodes.UpdatedBy;
				_updatedOn = dlMasterIncCodes.UpdatedOn;
				_updatedMachineInfo = dlMasterIncCodes.UpdatedMachineInfo;
				_isActive = dlMasterIncCodes.IsActive;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DLMasterIncCodes
		///</parameters>
		protected internal BLMasterIncCodes(DLMasterIncCodes dlMasterIncCodes)
		{
			try
			{
				_incCodeID = dlMasterIncCodes.IncCodeID;
				_incCode = dlMasterIncCodes.IncCode;
				_description = dlMasterIncCodes.Description;
				_dfltNum = dlMasterIncCodes.DfltNum;
				_dfltRate = dlMasterIncCodes.DfltRate;
				_dfltHours = dlMasterIncCodes.DfltHours;
				_dfltAcct = dlMasterIncCodes.DfltAcct;
				_dfltDept = dlMasterIncCodes.DfltDept;
				_incType = dlMasterIncCodes.IncType;
				_dfltLoIncAmt = dlMasterIncCodes.DfltLoIncAmt;
				_dfltHiIncAmt = dlMasterIncCodes.DfltHiIncAmt;
				_nonQual = dlMasterIncCodes.NonQual;
				_dfltAccountType = dlMasterIncCodes.DfltAccountType;
				_insertedBy = dlMasterIncCodes.InsertedBy;
				_insertedOn = dlMasterIncCodes.InsertedOn;
				_insertedMachineInfo = dlMasterIncCodes.InsertedMachineInfo;
				_updatedBy = dlMasterIncCodes.UpdatedBy;
				_updatedOn = dlMasterIncCodes.UpdatedOn;
				_updatedMachineInfo = dlMasterIncCodes.UpdatedMachineInfo;
				_isActive = dlMasterIncCodes.IsActive;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new MasterIncCodes record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DLMasterIncCodes dlMasterIncCodes = new DLMasterIncCodes();
			RegisterDataObject(dlMasterIncCodes);
			BeginTransaction("savenewBLMasterIncCodes");
			try
			{
				dlMasterIncCodes.IncCode = _incCode;
				dlMasterIncCodes.Description = _description;
				dlMasterIncCodes.DfltNum = _dfltNum;
				dlMasterIncCodes.DfltRate = _dfltRate;
				dlMasterIncCodes.DfltHours = _dfltHours;
				dlMasterIncCodes.DfltAcct = _dfltAcct;
				dlMasterIncCodes.DfltDept = _dfltDept;
				dlMasterIncCodes.IncType = _incType;
				dlMasterIncCodes.DfltLoIncAmt = _dfltLoIncAmt;
				dlMasterIncCodes.DfltHiIncAmt = _dfltHiIncAmt;
				dlMasterIncCodes.NonQual = _nonQual;
				dlMasterIncCodes.DfltAccountType = _dfltAccountType;
				dlMasterIncCodes.InsertedBy = _insertedBy;
				dlMasterIncCodes.InsertedOn = _insertedOn;
				dlMasterIncCodes.InsertedMachineInfo = _insertedMachineInfo;
				dlMasterIncCodes.UpdatedBy = _updatedBy;
				dlMasterIncCodes.UpdatedOn = _updatedOn;
				dlMasterIncCodes.UpdatedMachineInfo = _updatedMachineInfo;
				dlMasterIncCodes.IsActive = _isActive;
				dlMasterIncCodes.Insert();
				CommitTransaction();
				
				_incCodeID = dlMasterIncCodes.IncCodeID;
				_incCode = dlMasterIncCodes.IncCode;
				_description = dlMasterIncCodes.Description;
				_dfltNum = dlMasterIncCodes.DfltNum;
				_dfltRate = dlMasterIncCodes.DfltRate;
				_dfltHours = dlMasterIncCodes.DfltHours;
				_dfltAcct = dlMasterIncCodes.DfltAcct;
				_dfltDept = dlMasterIncCodes.DfltDept;
				_incType = dlMasterIncCodes.IncType;
				_dfltLoIncAmt = dlMasterIncCodes.DfltLoIncAmt;
				_dfltHiIncAmt = dlMasterIncCodes.DfltHiIncAmt;
				_nonQual = dlMasterIncCodes.NonQual;
				_dfltAccountType = dlMasterIncCodes.DfltAccountType;
				_insertedBy = dlMasterIncCodes.InsertedBy;
				_insertedOn = dlMasterIncCodes.InsertedOn;
				_insertedMachineInfo = dlMasterIncCodes.InsertedMachineInfo;
				_updatedBy = dlMasterIncCodes.UpdatedBy;
				_updatedOn = dlMasterIncCodes.UpdatedOn;
				_updatedMachineInfo = dlMasterIncCodes.UpdatedMachineInfo;
				_isActive = dlMasterIncCodes.IsActive;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBLMasterIncCodes");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one MasterIncCodes record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BLMasterIncCodes
		///</parameters>
		public virtual void Update()
		{
			DLMasterIncCodes dlMasterIncCodes = new DLMasterIncCodes();
			RegisterDataObject(dlMasterIncCodes);
			BeginTransaction("updateBLMasterIncCodes");
			try
			{
				dlMasterIncCodes.IncCodeID = _incCodeID;
				dlMasterIncCodes.IncCode = _incCode;
				dlMasterIncCodes.Description = _description;
				dlMasterIncCodes.DfltNum = _dfltNum;
				dlMasterIncCodes.DfltRate = _dfltRate;
				dlMasterIncCodes.DfltHours = _dfltHours;
				dlMasterIncCodes.DfltAcct = _dfltAcct;
				dlMasterIncCodes.DfltDept = _dfltDept;
				dlMasterIncCodes.IncType = _incType;
				dlMasterIncCodes.DfltLoIncAmt = _dfltLoIncAmt;
				dlMasterIncCodes.DfltHiIncAmt = _dfltHiIncAmt;
				dlMasterIncCodes.NonQual = _nonQual;
				dlMasterIncCodes.DfltAccountType = _dfltAccountType;
				dlMasterIncCodes.InsertedBy = _insertedBy;
				dlMasterIncCodes.InsertedOn = _insertedOn;
				dlMasterIncCodes.InsertedMachineInfo = _insertedMachineInfo;
				dlMasterIncCodes.UpdatedBy = _updatedBy;
				dlMasterIncCodes.UpdatedOn = _updatedOn;
				dlMasterIncCodes.UpdatedMachineInfo = _updatedMachineInfo;
				dlMasterIncCodes.IsActive = _isActive;
				dlMasterIncCodes.Update();
				CommitTransaction();
				
				_incCodeID = dlMasterIncCodes.IncCodeID;
				_incCode = dlMasterIncCodes.IncCode;
				_description = dlMasterIncCodes.Description;
				_dfltNum = dlMasterIncCodes.DfltNum;
				_dfltRate = dlMasterIncCodes.DfltRate;
				_dfltHours = dlMasterIncCodes.DfltHours;
				_dfltAcct = dlMasterIncCodes.DfltAcct;
				_dfltDept = dlMasterIncCodes.DfltDept;
				_incType = dlMasterIncCodes.IncType;
				_dfltLoIncAmt = dlMasterIncCodes.DfltLoIncAmt;
				_dfltHiIncAmt = dlMasterIncCodes.DfltHiIncAmt;
				_nonQual = dlMasterIncCodes.NonQual;
				_dfltAccountType = dlMasterIncCodes.DfltAccountType;
				_insertedBy = dlMasterIncCodes.InsertedBy;
				_insertedOn = dlMasterIncCodes.InsertedOn;
				_insertedMachineInfo = dlMasterIncCodes.InsertedMachineInfo;
				_updatedBy = dlMasterIncCodes.UpdatedBy;
				_updatedOn = dlMasterIncCodes.UpdatedOn;
				_updatedMachineInfo = dlMasterIncCodes.UpdatedMachineInfo;
				_isActive = dlMasterIncCodes.IsActive;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBLMasterIncCodes");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one MasterIncCodes record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DLMasterIncCodes dlMasterIncCodes = new DLMasterIncCodes();
			RegisterDataObject(dlMasterIncCodes);
			BeginTransaction("deleteBLMasterIncCodes");
			try
			{
				dlMasterIncCodes.IncCodeID = _incCodeID;
				dlMasterIncCodes.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBLMasterIncCodes");
				throw;
			}
		}
		
		///<Summary>
		///MasterIncCodesCollection
		///This method returns the collection of BLMasterIncCodes objects
		///</Summary>
		///<returns>
		///List[BLMasterIncCodes]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BLMasterIncCodes> MasterIncCodesCollection()
		{
			try
			{
				IList<BLMasterIncCodes> blMasterIncCodesCollection = new List<BLMasterIncCodes>();
				IList<DLMasterIncCodes> dlMasterIncCodesCollection = DLMasterIncCodes.SelectAll();
			
				foreach(DLMasterIncCodes dlMasterIncCodes in dlMasterIncCodesCollection)
					blMasterIncCodesCollection.Add(new BLMasterIncCodes(dlMasterIncCodes));
			
				return blMasterIncCodesCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///MasterIncCodesCollectionCount
		///This method returns the collection count of BLMasterIncCodes objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 MasterIncCodesCollectionCount()
		{
			try
			{
				Int32 objCount = DLMasterIncCodes.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BLMasterIncCodes>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DLMasterIncCodes.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///MasterIncCodesCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BLMasterIncCodes objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> blMasterIncCodesCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DLMasterIncCodes> dlMasterIncCodesCollection = DLMasterIncCodes.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DLMasterIncCodes resdlMasterIncCodes in dlMasterIncCodesCollection)
					blMasterIncCodesCollection.Add((T)(object)new BLMasterIncCodes(resdlMasterIncCodes));
			
				return blMasterIncCodesCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///MasterIncCodesCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BLMasterIncCodes objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DLMasterIncCodes.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? IncCodeID
		{
			get
			{
				 return _incCodeID;
			}
			set
			{
				_incCodeID = value;
				_isDirty = true;
			}
		}
		
		public virtual string IncCode
		{
			get
			{
				 return _incCode;
			}
			set
			{
				_incCode = value;
				_isDirty = true;
			}
		}
		
		public virtual string Description
		{
			get
			{
				 return _description;
			}
			set
			{
				_description = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? DfltNum
		{
			get
			{
				 return _dfltNum;
			}
			set
			{
				_dfltNum = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? DfltRate
		{
			get
			{
				 return _dfltRate;
			}
			set
			{
				_dfltRate = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? DfltHours
		{
			get
			{
				 return _dfltHours;
			}
			set
			{
				_dfltHours = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? DfltAcct
		{
			get
			{
				 return _dfltAcct;
			}
			set
			{
				_dfltAcct = value;
				_isDirty = true;
			}
		}
		
		public virtual string DfltDept
		{
			get
			{
				 return _dfltDept;
			}
			set
			{
				_dfltDept = value;
				_isDirty = true;
			}
		}
		
		public virtual string IncType
		{
			get
			{
				 return _incType;
			}
			set
			{
				_incType = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? DfltLoIncAmt
		{
			get
			{
				 return _dfltLoIncAmt;
			}
			set
			{
				_dfltLoIncAmt = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? DfltHiIncAmt
		{
			get
			{
				 return _dfltHiIncAmt;
			}
			set
			{
				_dfltHiIncAmt = value;
				_isDirty = true;
			}
		}
		
		public virtual string NonQual
		{
			get
			{
				 return _nonQual;
			}
			set
			{
				_nonQual = value;
				_isDirty = true;
			}
		}
		
		public virtual string DfltAccountType
		{
			get
			{
				 return _dfltAccountType;
			}
			set
			{
				_dfltAccountType = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? InsertedBy
		{
			get
			{
				 return _insertedBy;
			}
			set
			{
				_insertedBy = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? InsertedOn
		{
			get
			{
				 return _insertedOn;
			}
			set
			{
				_insertedOn = value;
				_isDirty = true;
			}
		}
		
		public virtual string InsertedMachineInfo
		{
			get
			{
				 return _insertedMachineInfo;
			}
			set
			{
				_insertedMachineInfo = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? UpdatedBy
		{
			get
			{
				 return _updatedBy;
			}
			set
			{
				_updatedBy = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? UpdatedOn
		{
			get
			{
				 return _updatedOn;
			}
			set
			{
				_updatedOn = value;
				_isDirty = true;
			}
		}
		
		public virtual string UpdatedMachineInfo
		{
			get
			{
				 return _updatedMachineInfo;
			}
			set
			{
				_updatedMachineInfo = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? IsActive
		{
			get
			{
				 return _isActive;
			}
			set
			{
				_isActive = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
