/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using C3WizardLayer.DataObjects;
using C3WizardLayer.DataObjects.Interfaces;
using C3WizardLayer.BusinessObjects.Interfaces;

namespace C3WizardLayer.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BLMasterIncCodes.
	///</Summary>
	public partial class BLMasterDeductionCodes : C3WizardLayerConn_BaseBusiness
	{
        #region member variables
        protected int? _ID ;
        protected int?   _ded_code_id ;
        protected string _ded_code ;
        protected string _description ;
        protected string _ded_type ;
        protected string _ded_taxred ;
        protected decimal? _dflt_rate ;
        protected decimal? _dflt_limit ;
        protected string _dflt_apply ;
        protected decimal? _dflt_hi_ded_amt ;
        protected decimal? _dflt_lo_ded_amt ;
        protected string _state_ein ;
        protected string _tax_jur ;
        protected decimal? _dflt_pay_limit ;
        protected string _yearrollover ;
		protected Int32? _insertedBy;
		protected DateTime? _insertedOn;
		protected string _insertedMachineInfo;
		protected Int32? _updatedBy;
		protected DateTime? _updatedOn;
		protected string _updatedMachineInfo;
		protected bool? _isActive;
		protected bool _isDirty = false;
		
		public BLMasterDeductionCodes()
		{
		}
        protected internal BLMasterDeductionCodes(DLMasterDeductionCodes DLMasterDeductionCodes)
        {
            try
            {
                _ded_code_id = DLMasterDeductionCodes.ded_code_id;
                _ded_code = DLMasterDeductionCodes.ded_code;
                _description = DLMasterDeductionCodes.description;
                _ded_type = DLMasterDeductionCodes.ded_type;
                _ded_taxred = DLMasterDeductionCodes.ded_taxred;
                _dflt_rate = DLMasterDeductionCodes.dflt_rate;
                _dflt_limit = DLMasterDeductionCodes.dflt_limit;
                _dflt_apply = DLMasterDeductionCodes.dflt_apply;
                _dflt_hi_ded_amt = DLMasterDeductionCodes.dflt_hi_ded_amt;
                _dflt_lo_ded_amt = DLMasterDeductionCodes.dflt_lo_ded_amt;
                _state_ein = DLMasterDeductionCodes.state_ein;
                _tax_jur = DLMasterDeductionCodes.tax_jur;
                _dflt_pay_limit = DLMasterDeductionCodes.dflt_pay_limit;
                _yearrollover = DLMasterDeductionCodes.yearrollover;
            }
            catch
            {
                throw;
            }
        }

        public virtual void SaveNew()
		{
            DLMasterDeductionCodes dlMasterDedCodes = new DLMasterDeductionCodes();
			RegisterDataObject(dlMasterDedCodes);
			BeginTransaction("savenewBLMasterDedCodes");
			try
			{
               dlMasterDedCodes.ded_code_id =_ded_code_id;
               dlMasterDedCodes.ded_code = _ded_code;
               dlMasterDedCodes.description = _description;
               dlMasterDedCodes.ded_type = _ded_type;
               dlMasterDedCodes.ded_taxred = _ded_taxred;
               dlMasterDedCodes.dflt_rate = _dflt_rate;
               dlMasterDedCodes.dflt_limit = _dflt_limit;
               dlMasterDedCodes.dflt_apply =_dflt_apply;
               dlMasterDedCodes.dflt_hi_ded_amt = _dflt_hi_ded_amt;
               dlMasterDedCodes.dflt_lo_ded_amt = _dflt_lo_ded_amt;
               dlMasterDedCodes.state_ein = _state_ein;
               dlMasterDedCodes.tax_jur = _tax_jur;
               dlMasterDedCodes.dflt_pay_limit = _dflt_pay_limit;
               dlMasterDedCodes.yearrollover= _yearrollover;
                
				dlMasterDedCodes.InsertedBy = _insertedBy;
				dlMasterDedCodes.InsertedOn = _insertedOn;
				dlMasterDedCodes.InsertedMachineInfo = _insertedMachineInfo;
				dlMasterDedCodes.UpdatedBy = _updatedBy;
				dlMasterDedCodes.UpdatedOn = _updatedOn;
				dlMasterDedCodes.UpdatedMachineInfo = _updatedMachineInfo;
				dlMasterDedCodes.IsActive = _isActive;
                dlMasterDedCodes.Insert();
				CommitTransaction();
				
				_ded_code_id= dlMasterDedCodes.ded_code_id;
				 _ded_code= dlMasterDedCodes.ded_code;
				 _description = dlMasterDedCodes.description;
				 _ded_type = dlMasterDedCodes.ded_type;
				 _ded_taxred = dlMasterDedCodes.ded_taxred;
				 _dflt_rate = dlMasterDedCodes.dflt_rate;
				 _dflt_limit= dlMasterDedCodes.dflt_limit;
				_dflt_apply= dlMasterDedCodes.dflt_apply;
				 _dflt_hi_ded_amt = dlMasterDedCodes.dflt_hi_ded_amt;
				 _dflt_lo_ded_amt = dlMasterDedCodes.dflt_lo_ded_amt;
				 _state_ein = dlMasterDedCodes.state_ein;
				 _tax_jur= dlMasterDedCodes.tax_jur;
				 _dflt_pay_limit = dlMasterDedCodes.dflt_pay_limit;
                _yearrollover = dlMasterDedCodes.yearrollover;
                _insertedBy = dlMasterDedCodes.InsertedBy;
				_insertedOn = dlMasterDedCodes.InsertedOn;
				_insertedMachineInfo = dlMasterDedCodes.InsertedMachineInfo;
				_updatedBy = dlMasterDedCodes.UpdatedBy;
				_updatedOn = dlMasterDedCodes.UpdatedOn;
				_updatedMachineInfo = dlMasterDedCodes.UpdatedMachineInfo;
				_isActive = dlMasterDedCodes.IsActive;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBLMasterDedCodes");
				throw;
			}
		}
        public static IList<BLMasterDeductionCodes> MasterDeductionCodesCollection()
        {
            try
            {
                IList<BLMasterDeductionCodes> blMasterDeductionCodeCollection = new List<BLMasterDeductionCodes>();
                IList<DLMasterDeductionCodes> dlMasterDeductionsCodeCollection = DLMasterDeductionCodes.SelectAll();
                foreach (DLMasterDeductionCodes dlMasterDeductionsCode in dlMasterDeductionsCodeCollection)
                    blMasterDeductionCodeCollection.Add(new BLMasterDeductionCodes(dlMasterDeductionsCode));
                return blMasterDeductionCodeCollection;
            }
            catch
            {
                throw;
            }
        }
        public virtual void Update()
        {
            DLMasterDeductionCodes dlMasterDeductionCodes = new DLMasterDeductionCodes();
            RegisterDataObject(dlMasterDeductionCodes);
            BeginTransaction("updateBLdlMasterDeductionCodes");
            try
            {
                dlMasterDeductionCodes.ded_code_id = _ded_code_id;
                dlMasterDeductionCodes.ded_code = _ded_code;
                dlMasterDeductionCodes.description = _description;
                dlMasterDeductionCodes.ded_type = _ded_type;
                dlMasterDeductionCodes.ded_taxred = _ded_taxred;
                dlMasterDeductionCodes.dflt_rate = _dflt_rate;
                dlMasterDeductionCodes.dflt_limit = _dflt_limit;
                dlMasterDeductionCodes.dflt_apply = _dflt_apply;
                dlMasterDeductionCodes.dflt_hi_ded_amt =_dflt_hi_ded_amt;
                dlMasterDeductionCodes.dflt_lo_ded_amt = _dflt_lo_ded_amt;
                dlMasterDeductionCodes.state_ein = _state_ein;
                dlMasterDeductionCodes.tax_jur = _tax_jur;
                dlMasterDeductionCodes.dflt_pay_limit =_dflt_pay_limit;
                dlMasterDeductionCodes.yearrollover = _yearrollover;
                dlMasterDeductionCodes.Update();
                CommitTransaction();

                _ded_code_id = dlMasterDeductionCodes.ded_code_id;
                _ded_code = dlMasterDeductionCodes.ded_code;
                _description = dlMasterDeductionCodes.description;
                _ded_type = dlMasterDeductionCodes.ded_type;
                _ded_taxred = dlMasterDeductionCodes.ded_taxred;
                _dflt_rate = dlMasterDeductionCodes.dflt_rate;
                _dflt_limit = dlMasterDeductionCodes.dflt_limit;
                _dflt_apply = dlMasterDeductionCodes.dflt_apply;
                _dflt_hi_ded_amt = dlMasterDeductionCodes.dflt_hi_ded_amt;
                _dflt_lo_ded_amt = dlMasterDeductionCodes.dflt_lo_ded_amt;
                _state_ein = dlMasterDeductionCodes.state_ein;
                _tax_jur = dlMasterDeductionCodes.tax_jur;
                _dflt_pay_limit = dlMasterDeductionCodes.dflt_pay_limit;
                _yearrollover = dlMasterDeductionCodes.yearrollover;
                _isDirty = false;
            }
            catch
            {
                RollbackTransaction("updateBLdlMasterDeductionCodes");
                throw;
            }
        }
        #endregion
        #region member properties		
        public virtual Int32? ded_code_id
        {
			get
			{
				 return _ded_code_id;
			}
			set
			{
                _ded_code_id = value;
				_isDirty = true;
			}
		}	
		public virtual string ded_code
        {
			get
			{
				 return _ded_code;
			}
			set
			{
                _ded_code = value;
				_isDirty = true;
			}
		}	
		public virtual string description
        {
			get
			{
				 return _description;
			}
			set
			{
                _description = value;
				_isDirty = true;
			}
		}	
		public virtual string ded_type
        {
			get
			{
				 return _ded_type;
			}
			set
			{
                _ded_type = value;
				_isDirty = true;
			}
		}		
		public virtual string ded_taxred
        {
			get
			{
				 return _ded_taxred;
			}
			set
			{
                _ded_taxred = value;
				_isDirty = true;
			}
		}	
		public virtual decimal? dflt_rate
        {
			get
			{
				 return _dflt_rate;
			}
			set
			{
                _dflt_rate = value;
				_isDirty = true;
			}
		}	
		public virtual decimal? dflt_limit
        {
			get
			{
				 return _dflt_limit;
			}
			set
			{
                _dflt_limit = value;
				_isDirty = true;
			}
		}
        public virtual string dflt_apply
        {
            get
            {
                return _dflt_apply;
            }
            set
            {
                _dflt_apply = value;
                _isDirty = true;
            }
        }
        public virtual decimal? dflt_hi_ded_amt
        {
			get
			{
				 return _dflt_hi_ded_amt;
			}
			set
			{
                _dflt_hi_ded_amt = value;
				_isDirty = true;
			}
		}		
		public virtual decimal? dflt_lo_ded_amt
        {
			get
			{
				 return _dflt_lo_ded_amt;
			}
			set
			{
                _dflt_lo_ded_amt = value;
				_isDirty = true;
			}
		}		
		public virtual string state_ein
        {
			get
			{
				 return _state_ein;
			}
			set
			{
                _state_ein = value;
				_isDirty = true;
			}
		}	
		public virtual string tax_jur
        {
			get
			{
				 return _tax_jur;
			}
			set
			{
                _tax_jur = value;
				_isDirty = true;
			}
		}	
		public virtual decimal? dflt_pay_limit
        {
			get
			{
				 return _dflt_pay_limit;
			}
			set
			{
                _dflt_pay_limit = value;
				_isDirty = true;
			}
		}	
		public virtual string yearrollover
        {
			get
			{
				 return _yearrollover;
			}
			set
			{
                _yearrollover = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? InsertedBy
		{
			get
			{
				 return _insertedBy;
			}
			set
			{
				_insertedBy = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? InsertedOn
		{
			get
			{
				 return _insertedOn;
			}
			set
			{
				_insertedOn = value;
				_isDirty = true;
			}
		}
		
		public virtual string InsertedMachineInfo
		{
			get
			{
				 return _insertedMachineInfo;
			}
			set
			{
				_insertedMachineInfo = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? UpdatedBy
		{
			get
			{
				 return _updatedBy;
			}
			set
			{
				_updatedBy = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? UpdatedOn
		{
			get
			{
				 return _updatedOn;
			}
			set
			{
				_updatedOn = value;
				_isDirty = true;
			}
		}
		
		public virtual string UpdatedMachineInfo
		{
			get
			{
				 return _updatedMachineInfo;
			}
			set
			{
				_updatedMachineInfo = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? IsActive
		{
			get
			{
				 return _isActive;
			}
			set
			{
				_isActive = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
