/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:28 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using C3WizardLayer.DataObjects;
using C3WizardLayer.DataObjects.Interfaces;
using C3WizardLayer.BusinessObjects.Interfaces;

namespace C3WizardLayer.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BLSECUserModule.
	///</Summary>
	public partial class BLSECUserModule : C3WizardLayerConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _userModuleId;
		protected Int32? _userId;
		protected Int32? _roleId;
		protected Int32? _moduleId;
		protected Int32? _addPermission;
		protected Int32? _updatePermission;
		protected Int32? _deletePermission;
		protected Int32? _findPermission;
		protected Int32? _browsePermission;
		protected Int32? _nextPermission;
		protected Int32? _previousPermission;
		protected Int32? _tabPermission;
		protected Int32? _optionsPermission;
		protected Int32? _initPermission;
		protected Int32? _insertedBy;
		protected DateTime? _insertedOn;
		protected string _insertedMachineInfo;
		protected Int32? _updatedBy;
		protected DateTime? _updatedOn;
		protected string _updatedMachineInfo;
		protected bool? _isActive;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BLSECUserModule()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 userModuleId
		///</parameters>
		public BLSECUserModule(Int32 userModuleId)
		{
			try
			{
				DLSECUserModule dlSECUserModule = DLSECUserModule.SelectOne(userModuleId);
				_userModuleId = dlSECUserModule.UserModuleId;
				_userId = dlSECUserModule.UserId;
				_roleId = dlSECUserModule.RoleId;
				_moduleId = dlSECUserModule.ModuleId;
				_addPermission = dlSECUserModule.AddPermission;
				_updatePermission = dlSECUserModule.UpdatePermission;
				_deletePermission = dlSECUserModule.DeletePermission;
				_findPermission = dlSECUserModule.FindPermission;
				_browsePermission = dlSECUserModule.BrowsePermission;
				_nextPermission = dlSECUserModule.NextPermission;
				_previousPermission = dlSECUserModule.PreviousPermission;
				_tabPermission = dlSECUserModule.TabPermission;
				_optionsPermission = dlSECUserModule.OptionsPermission;
				_initPermission = dlSECUserModule.InitPermission;
				_insertedBy = dlSECUserModule.InsertedBy;
				_insertedOn = dlSECUserModule.InsertedOn;
				_insertedMachineInfo = dlSECUserModule.InsertedMachineInfo;
				_updatedBy = dlSECUserModule.UpdatedBy;
				_updatedOn = dlSECUserModule.UpdatedOn;
				_updatedMachineInfo = dlSECUserModule.UpdatedMachineInfo;
				_isActive = dlSECUserModule.IsActive;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DLSECUserModule
		///</parameters>
		protected internal BLSECUserModule(DLSECUserModule dlSECUserModule)
		{
			try
			{
				_userModuleId = dlSECUserModule.UserModuleId;
				_userId = dlSECUserModule.UserId;
				_roleId = dlSECUserModule.RoleId;
				_moduleId = dlSECUserModule.ModuleId;
				_addPermission = dlSECUserModule.AddPermission;
				_updatePermission = dlSECUserModule.UpdatePermission;
				_deletePermission = dlSECUserModule.DeletePermission;
				_findPermission = dlSECUserModule.FindPermission;
				_browsePermission = dlSECUserModule.BrowsePermission;
				_nextPermission = dlSECUserModule.NextPermission;
				_previousPermission = dlSECUserModule.PreviousPermission;
				_tabPermission = dlSECUserModule.TabPermission;
				_optionsPermission = dlSECUserModule.OptionsPermission;
				_initPermission = dlSECUserModule.InitPermission;
				_insertedBy = dlSECUserModule.InsertedBy;
				_insertedOn = dlSECUserModule.InsertedOn;
				_insertedMachineInfo = dlSECUserModule.InsertedMachineInfo;
				_updatedBy = dlSECUserModule.UpdatedBy;
				_updatedOn = dlSECUserModule.UpdatedOn;
				_updatedMachineInfo = dlSECUserModule.UpdatedMachineInfo;
				_isActive = dlSECUserModule.IsActive;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new SECUserModule record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DLSECUserModule dlSECUserModule = new DLSECUserModule();
			RegisterDataObject(dlSECUserModule);
			BeginTransaction("savenewBLSECUserModule");
			try
			{
				dlSECUserModule.UserId = _userId;
				dlSECUserModule.RoleId = _roleId;
				dlSECUserModule.ModuleId = _moduleId;
				dlSECUserModule.AddPermission = _addPermission;
				dlSECUserModule.UpdatePermission = _updatePermission;
				dlSECUserModule.DeletePermission = _deletePermission;
				dlSECUserModule.FindPermission = _findPermission;
				dlSECUserModule.BrowsePermission = _browsePermission;
				dlSECUserModule.NextPermission = _nextPermission;
				dlSECUserModule.PreviousPermission = _previousPermission;
				dlSECUserModule.TabPermission = _tabPermission;
				dlSECUserModule.OptionsPermission = _optionsPermission;
				dlSECUserModule.InitPermission = _initPermission;
				dlSECUserModule.InsertedBy = _insertedBy;
				dlSECUserModule.InsertedOn = _insertedOn;
				dlSECUserModule.InsertedMachineInfo = _insertedMachineInfo;
				dlSECUserModule.UpdatedBy = _updatedBy;
				dlSECUserModule.UpdatedOn = _updatedOn;
				dlSECUserModule.UpdatedMachineInfo = _updatedMachineInfo;
				dlSECUserModule.IsActive = _isActive;
				dlSECUserModule.Insert();
				CommitTransaction();
				
				_userModuleId = dlSECUserModule.UserModuleId;
				_userId = dlSECUserModule.UserId;
				_roleId = dlSECUserModule.RoleId;
				_moduleId = dlSECUserModule.ModuleId;
				_addPermission = dlSECUserModule.AddPermission;
				_updatePermission = dlSECUserModule.UpdatePermission;
				_deletePermission = dlSECUserModule.DeletePermission;
				_findPermission = dlSECUserModule.FindPermission;
				_browsePermission = dlSECUserModule.BrowsePermission;
				_nextPermission = dlSECUserModule.NextPermission;
				_previousPermission = dlSECUserModule.PreviousPermission;
				_tabPermission = dlSECUserModule.TabPermission;
				_optionsPermission = dlSECUserModule.OptionsPermission;
				_initPermission = dlSECUserModule.InitPermission;
				_insertedBy = dlSECUserModule.InsertedBy;
				_insertedOn = dlSECUserModule.InsertedOn;
				_insertedMachineInfo = dlSECUserModule.InsertedMachineInfo;
				_updatedBy = dlSECUserModule.UpdatedBy;
				_updatedOn = dlSECUserModule.UpdatedOn;
				_updatedMachineInfo = dlSECUserModule.UpdatedMachineInfo;
				_isActive = dlSECUserModule.IsActive;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBLSECUserModule");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one SECUserModule record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BLSECUserModule
		///</parameters>
		public virtual void Update()
		{
			DLSECUserModule dlSECUserModule = new DLSECUserModule();
			RegisterDataObject(dlSECUserModule);
			BeginTransaction("updateBLSECUserModule");
			try
			{
				dlSECUserModule.UserModuleId = _userModuleId;
				dlSECUserModule.UserId = _userId;
				dlSECUserModule.RoleId = _roleId;
				dlSECUserModule.ModuleId = _moduleId;
				dlSECUserModule.AddPermission = _addPermission;
				dlSECUserModule.UpdatePermission = _updatePermission;
				dlSECUserModule.DeletePermission = _deletePermission;
				dlSECUserModule.FindPermission = _findPermission;
				dlSECUserModule.BrowsePermission = _browsePermission;
				dlSECUserModule.NextPermission = _nextPermission;
				dlSECUserModule.PreviousPermission = _previousPermission;
				dlSECUserModule.TabPermission = _tabPermission;
				dlSECUserModule.OptionsPermission = _optionsPermission;
				dlSECUserModule.InitPermission = _initPermission;
				dlSECUserModule.InsertedBy = _insertedBy;
				dlSECUserModule.InsertedOn = _insertedOn;
				dlSECUserModule.InsertedMachineInfo = _insertedMachineInfo;
				dlSECUserModule.UpdatedBy = _updatedBy;
				dlSECUserModule.UpdatedOn = _updatedOn;
				dlSECUserModule.UpdatedMachineInfo = _updatedMachineInfo;
				dlSECUserModule.IsActive = _isActive;
				dlSECUserModule.Update();
				CommitTransaction();
				
				_userModuleId = dlSECUserModule.UserModuleId;
				_userId = dlSECUserModule.UserId;
				_roleId = dlSECUserModule.RoleId;
				_moduleId = dlSECUserModule.ModuleId;
				_addPermission = dlSECUserModule.AddPermission;
				_updatePermission = dlSECUserModule.UpdatePermission;
				_deletePermission = dlSECUserModule.DeletePermission;
				_findPermission = dlSECUserModule.FindPermission;
				_browsePermission = dlSECUserModule.BrowsePermission;
				_nextPermission = dlSECUserModule.NextPermission;
				_previousPermission = dlSECUserModule.PreviousPermission;
				_tabPermission = dlSECUserModule.TabPermission;
				_optionsPermission = dlSECUserModule.OptionsPermission;
				_initPermission = dlSECUserModule.InitPermission;
				_insertedBy = dlSECUserModule.InsertedBy;
				_insertedOn = dlSECUserModule.InsertedOn;
				_insertedMachineInfo = dlSECUserModule.InsertedMachineInfo;
				_updatedBy = dlSECUserModule.UpdatedBy;
				_updatedOn = dlSECUserModule.UpdatedOn;
				_updatedMachineInfo = dlSECUserModule.UpdatedMachineInfo;
				_isActive = dlSECUserModule.IsActive;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBLSECUserModule");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one SECUserModule record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DLSECUserModule dlSECUserModule = new DLSECUserModule();
			RegisterDataObject(dlSECUserModule);
			BeginTransaction("deleteBLSECUserModule");
			try
			{
				dlSECUserModule.UserModuleId = _userModuleId;
				dlSECUserModule.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBLSECUserModule");
				throw;
			}
		}
		
		///<Summary>
		///SECUserModuleCollection
		///This method returns the collection of BLSECUserModule objects
		///</Summary>
		///<returns>
		///List[BLSECUserModule]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BLSECUserModule> SECUserModuleCollection()
		{
			try
			{
				IList<BLSECUserModule> blSECUserModuleCollection = new List<BLSECUserModule>();
				IList<DLSECUserModule> dlSECUserModuleCollection = DLSECUserModule.SelectAll();
			
				foreach(DLSECUserModule dlSECUserModule in dlSECUserModuleCollection)
					blSECUserModuleCollection.Add(new BLSECUserModule(dlSECUserModule));
			
				return blSECUserModuleCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///SECUserModuleCollectionCount
		///This method returns the collection count of BLSECUserModule objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SECUserModuleCollectionCount()
		{
			try
			{
				Int32 objCount = DLSECUserModule.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BLSECUserModule>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DLSECUserModule.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///SECUserModuleCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BLSECUserModule objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> blSECUserModuleCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DLSECUserModule> dlSECUserModuleCollection = DLSECUserModule.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DLSECUserModule resdlSECUserModule in dlSECUserModuleCollection)
					blSECUserModuleCollection.Add((T)(object)new BLSECUserModule(resdlSECUserModule));
			
				return blSECUserModuleCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///SECUserModuleCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BLSECUserModule objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DLSECUserModule.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? UserModuleId
		{
			get
			{
				 return _userModuleId;
			}
			set
			{
				_userModuleId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? UserId
		{
			get
			{
				 return _userId;
			}
			set
			{
				_userId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? RoleId
		{
			get
			{
				 return _roleId;
			}
			set
			{
				_roleId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? ModuleId
		{
			get
			{
				 return _moduleId;
			}
			set
			{
				_moduleId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? AddPermission
		{
			get
			{
				 return _addPermission;
			}
			set
			{
				_addPermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? UpdatePermission
		{
			get
			{
				 return _updatePermission;
			}
			set
			{
				_updatePermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? DeletePermission
		{
			get
			{
				 return _deletePermission;
			}
			set
			{
				_deletePermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? FindPermission
		{
			get
			{
				 return _findPermission;
			}
			set
			{
				_findPermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? BrowsePermission
		{
			get
			{
				 return _browsePermission;
			}
			set
			{
				_browsePermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? NextPermission
		{
			get
			{
				 return _nextPermission;
			}
			set
			{
				_nextPermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? PreviousPermission
		{
			get
			{
				 return _previousPermission;
			}
			set
			{
				_previousPermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? TabPermission
		{
			get
			{
				 return _tabPermission;
			}
			set
			{
				_tabPermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? OptionsPermission
		{
			get
			{
				 return _optionsPermission;
			}
			set
			{
				_optionsPermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? InitPermission
		{
			get
			{
				 return _initPermission;
			}
			set
			{
				_initPermission = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? InsertedBy
		{
			get
			{
				 return _insertedBy;
			}
			set
			{
				_insertedBy = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? InsertedOn
		{
			get
			{
				 return _insertedOn;
			}
			set
			{
				_insertedOn = value;
				_isDirty = true;
			}
		}
		
		public virtual string InsertedMachineInfo
		{
			get
			{
				 return _insertedMachineInfo;
			}
			set
			{
				_insertedMachineInfo = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? UpdatedBy
		{
			get
			{
				 return _updatedBy;
			}
			set
			{
				_updatedBy = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? UpdatedOn
		{
			get
			{
				 return _updatedOn;
			}
			set
			{
				_updatedOn = value;
				_isDirty = true;
			}
		}
		
		public virtual string UpdatedMachineInfo
		{
			get
			{
				 return _updatedMachineInfo;
			}
			set
			{
				_updatedMachineInfo = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? IsActive
		{
			get
			{
				 return _isActive;
			}
			set
			{
				_isActive = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
