/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using C3WizardLayer.DataObjects;
using C3WizardLayer.DataObjects.Interfaces;
using C3WizardLayer.BusinessObjects.Interfaces;

namespace C3WizardLayer.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BLMasterEmployeeIncomes.
	///</Summary>
	public partial class BLMasterEmployeeIncomes : C3WizardLayerConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _empIncomeID;
		protected Int32? _employeeID;
		protected string _emplCode;
		protected string _incCode;
		protected Int32? _lineNo;
		protected decimal? _incRate;
        protected decimal? _wageamt;
        protected decimal? _incNumber;
		protected decimal? _incHours;
		protected Int32? _acctNo;
		protected string _department;
		protected decimal? _incQtd1;
		protected decimal? _incQtd2;
		protected decimal? _incQtd3;
		protected decimal? _incQtd4;
		protected decimal? _incYtd;
		protected decimal? _loIncAmt;
		protected decimal? _hiIncAmt;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BLMasterEmployeeIncomes()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 empIncomeID
		///</parameters>
		public BLMasterEmployeeIncomes(Int32 empIncomeID)
		{
			try
			{
				DLMasterEmployeeIncomes dlMasterEmployeeIncomes = DLMasterEmployeeIncomes.SelectOne(empIncomeID);
				_empIncomeID = dlMasterEmployeeIncomes.EmpIncomeID;
				_employeeID = dlMasterEmployeeIncomes.EmployeeID;
				_emplCode = dlMasterEmployeeIncomes.EmplCode;
				_incCode = dlMasterEmployeeIncomes.IncCode;
				_lineNo = dlMasterEmployeeIncomes.LineNo;
				_incRate = dlMasterEmployeeIncomes.IncRate;
                _wageamt = dlMasterEmployeeIncomes.Wageamt;
                _incNumber = dlMasterEmployeeIncomes.IncNumber;
				_incHours = dlMasterEmployeeIncomes.IncHours;
				_acctNo = dlMasterEmployeeIncomes.AcctNo;
				_department = dlMasterEmployeeIncomes.Department;
				_incQtd1 = dlMasterEmployeeIncomes.IncQtd1;
				_incQtd2 = dlMasterEmployeeIncomes.IncQtd2;
				_incQtd3 = dlMasterEmployeeIncomes.IncQtd3;
				_incQtd4 = dlMasterEmployeeIncomes.IncQtd4;
				_incYtd = dlMasterEmployeeIncomes.IncYtd;
				_loIncAmt = dlMasterEmployeeIncomes.LoIncAmt;
				_hiIncAmt = dlMasterEmployeeIncomes.HiIncAmt;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DLMasterEmployeeIncomes
		///</parameters>
		protected internal BLMasterEmployeeIncomes(DLMasterEmployeeIncomes dlMasterEmployeeIncomes)
		{
			try
			{
				_empIncomeID = dlMasterEmployeeIncomes.EmpIncomeID;
				_employeeID = dlMasterEmployeeIncomes.EmployeeID;
				_emplCode = dlMasterEmployeeIncomes.EmplCode;
				_incCode = dlMasterEmployeeIncomes.IncCode;
				_lineNo = dlMasterEmployeeIncomes.LineNo;
				_incRate = dlMasterEmployeeIncomes.IncRate;
                _wageamt = dlMasterEmployeeIncomes.Wageamt;
                _incNumber = dlMasterEmployeeIncomes.IncNumber;
				_incHours = dlMasterEmployeeIncomes.IncHours;
				_acctNo = dlMasterEmployeeIncomes.AcctNo;
				_department = dlMasterEmployeeIncomes.Department;
				_incQtd1 = dlMasterEmployeeIncomes.IncQtd1;
				_incQtd2 = dlMasterEmployeeIncomes.IncQtd2;
				_incQtd3 = dlMasterEmployeeIncomes.IncQtd3;
				_incQtd4 = dlMasterEmployeeIncomes.IncQtd4;
				_incYtd = dlMasterEmployeeIncomes.IncYtd;
				_loIncAmt = dlMasterEmployeeIncomes.LoIncAmt;
				_hiIncAmt = dlMasterEmployeeIncomes.HiIncAmt;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new MasterEmployeeIncomes record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DLMasterEmployeeIncomes dlMasterEmployeeIncomes = new DLMasterEmployeeIncomes();
			RegisterDataObject(dlMasterEmployeeIncomes);
			BeginTransaction("savenewBLMasterEmployeeIncomes");
			try
			{
				dlMasterEmployeeIncomes.EmployeeID = _employeeID;
				dlMasterEmployeeIncomes.EmplCode = _emplCode;
				dlMasterEmployeeIncomes.IncCode = _incCode;
				dlMasterEmployeeIncomes.LineNo = _lineNo;
				dlMasterEmployeeIncomes.IncRate = _incRate;
                dlMasterEmployeeIncomes.Wageamt = _wageamt;
                dlMasterEmployeeIncomes.IncNumber = _incNumber;
				dlMasterEmployeeIncomes.IncHours = _incHours;
				dlMasterEmployeeIncomes.AcctNo = _acctNo;
				dlMasterEmployeeIncomes.Department = _department;
				dlMasterEmployeeIncomes.IncQtd1 = _incQtd1;
				dlMasterEmployeeIncomes.IncQtd2 = _incQtd2;
				dlMasterEmployeeIncomes.IncQtd3 = _incQtd3;
				dlMasterEmployeeIncomes.IncQtd4 = _incQtd4;
				dlMasterEmployeeIncomes.IncYtd = _incYtd;
				dlMasterEmployeeIncomes.LoIncAmt = _loIncAmt;
				dlMasterEmployeeIncomes.HiIncAmt = _hiIncAmt;
				dlMasterEmployeeIncomes.Insert();
				CommitTransaction();
				
				_empIncomeID = dlMasterEmployeeIncomes.EmpIncomeID;
				_employeeID = dlMasterEmployeeIncomes.EmployeeID;
				_emplCode = dlMasterEmployeeIncomes.EmplCode;
				_incCode = dlMasterEmployeeIncomes.IncCode;
				_lineNo = dlMasterEmployeeIncomes.LineNo;
				_incRate = dlMasterEmployeeIncomes.IncRate;
                _wageamt = dlMasterEmployeeIncomes.Wageamt;
                _incNumber = dlMasterEmployeeIncomes.IncNumber;
				_incHours = dlMasterEmployeeIncomes.IncHours;
				_acctNo = dlMasterEmployeeIncomes.AcctNo;
				_department = dlMasterEmployeeIncomes.Department;
				_incQtd1 = dlMasterEmployeeIncomes.IncQtd1;
				_incQtd2 = dlMasterEmployeeIncomes.IncQtd2;
				_incQtd3 = dlMasterEmployeeIncomes.IncQtd3;
				_incQtd4 = dlMasterEmployeeIncomes.IncQtd4;
				_incYtd = dlMasterEmployeeIncomes.IncYtd;
				_loIncAmt = dlMasterEmployeeIncomes.LoIncAmt;
				_hiIncAmt = dlMasterEmployeeIncomes.HiIncAmt;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBLMasterEmployeeIncomes");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one MasterEmployeeIncomes record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BLMasterEmployeeIncomes
		///</parameters>
		public virtual void Update()
		{
			DLMasterEmployeeIncomes dlMasterEmployeeIncomes = new DLMasterEmployeeIncomes();
			RegisterDataObject(dlMasterEmployeeIncomes);
			BeginTransaction("updateBLMasterEmployeeIncomes");
			try
			{
				dlMasterEmployeeIncomes.EmpIncomeID = _empIncomeID;
				dlMasterEmployeeIncomes.EmployeeID = _employeeID;
				dlMasterEmployeeIncomes.EmplCode = _emplCode;
				dlMasterEmployeeIncomes.IncCode = _incCode;
				dlMasterEmployeeIncomes.LineNo = _lineNo;
				dlMasterEmployeeIncomes.IncRate = _incRate;
                dlMasterEmployeeIncomes.Wageamt = _wageamt;
                dlMasterEmployeeIncomes.IncNumber = _incNumber;
				dlMasterEmployeeIncomes.IncHours = _incHours;
				dlMasterEmployeeIncomes.AcctNo = _acctNo;
				dlMasterEmployeeIncomes.Department = _department;
				dlMasterEmployeeIncomes.IncQtd1 = _incQtd1;
				dlMasterEmployeeIncomes.IncQtd2 = _incQtd2;
				dlMasterEmployeeIncomes.IncQtd3 = _incQtd3;
				dlMasterEmployeeIncomes.IncQtd4 = _incQtd4;
				dlMasterEmployeeIncomes.IncYtd = _incYtd;
				dlMasterEmployeeIncomes.LoIncAmt = _loIncAmt;
				dlMasterEmployeeIncomes.HiIncAmt = _hiIncAmt;
				dlMasterEmployeeIncomes.Update();
				CommitTransaction();
				
				_empIncomeID = dlMasterEmployeeIncomes.EmpIncomeID;
				_employeeID = dlMasterEmployeeIncomes.EmployeeID;
				_emplCode = dlMasterEmployeeIncomes.EmplCode;
				_incCode = dlMasterEmployeeIncomes.IncCode;
				_lineNo = dlMasterEmployeeIncomes.LineNo;
				_incRate = dlMasterEmployeeIncomes.IncRate;
                _wageamt = dlMasterEmployeeIncomes.Wageamt;
                _incNumber = dlMasterEmployeeIncomes.IncNumber;
				_incHours = dlMasterEmployeeIncomes.IncHours;
				_acctNo = dlMasterEmployeeIncomes.AcctNo;
				_department = dlMasterEmployeeIncomes.Department;
				_incQtd1 = dlMasterEmployeeIncomes.IncQtd1;
				_incQtd2 = dlMasterEmployeeIncomes.IncQtd2;
				_incQtd3 = dlMasterEmployeeIncomes.IncQtd3;
				_incQtd4 = dlMasterEmployeeIncomes.IncQtd4;
				_incYtd = dlMasterEmployeeIncomes.IncYtd;
				_loIncAmt = dlMasterEmployeeIncomes.LoIncAmt;
				_hiIncAmt = dlMasterEmployeeIncomes.HiIncAmt;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBLMasterEmployeeIncomes");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one MasterEmployeeIncomes record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DLMasterEmployeeIncomes dlMasterEmployeeIncomes = new DLMasterEmployeeIncomes();
			RegisterDataObject(dlMasterEmployeeIncomes);
			BeginTransaction("deleteBLMasterEmployeeIncomes");
			try
			{
				dlMasterEmployeeIncomes.EmpIncomeID = _empIncomeID;
				dlMasterEmployeeIncomes.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBLMasterEmployeeIncomes");
				throw;
			}
		}
		
		///<Summary>
		///MasterEmployeeIncomesCollection
		///This method returns the collection of BLMasterEmployeeIncomes objects
		///</Summary>
		///<returns>
		///List[BLMasterEmployeeIncomes]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BLMasterEmployeeIncomes> MasterEmployeeIncomesCollection()
		{
			try
			{
				IList<BLMasterEmployeeIncomes> blMasterEmployeeIncomesCollection = new List<BLMasterEmployeeIncomes>();
				IList<DLMasterEmployeeIncomes> dlMasterEmployeeIncomesCollection = DLMasterEmployeeIncomes.SelectAll();
			
				foreach(DLMasterEmployeeIncomes dlMasterEmployeeIncomes in dlMasterEmployeeIncomesCollection)
					blMasterEmployeeIncomesCollection.Add(new BLMasterEmployeeIncomes(dlMasterEmployeeIncomes));
			
				return blMasterEmployeeIncomesCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///MasterEmployeeIncomesCollectionCount
		///This method returns the collection count of BLMasterEmployeeIncomes objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 MasterEmployeeIncomesCollectionCount()
		{
			try
			{
				Int32 objCount = DLMasterEmployeeIncomes.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BLMasterEmployeeIncomes>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DLMasterEmployeeIncomes.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///MasterEmployeeIncomesCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BLMasterEmployeeIncomes objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> blMasterEmployeeIncomesCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DLMasterEmployeeIncomes> dlMasterEmployeeIncomesCollection = DLMasterEmployeeIncomes.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DLMasterEmployeeIncomes resdlMasterEmployeeIncomes in dlMasterEmployeeIncomesCollection)
					blMasterEmployeeIncomesCollection.Add((T)(object)new BLMasterEmployeeIncomes(resdlMasterEmployeeIncomes));
			
				return blMasterEmployeeIncomesCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///MasterEmployeeIncomesCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BLMasterEmployeeIncomes objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DLMasterEmployeeIncomes.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? EmpIncomeID
		{
			get
			{
				 return _empIncomeID;
			}
			set
			{
				_empIncomeID = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? EmployeeID
		{
			get
			{
				 return _employeeID;
			}
			set
			{
				_employeeID = value;
				_isDirty = true;
			}
		}
		
		public virtual string EmplCode
		{
			get
			{
				 return _emplCode;
			}
			set
			{
				_emplCode = value;
				_isDirty = true;
			}
		}
		
		public virtual string IncCode
		{
			get
			{
				 return _incCode;
			}
			set
			{
				_incCode = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? LineNo
		{
			get
			{
				 return _lineNo;
			}
			set
			{
				_lineNo = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? IncRate
		{
			get
			{
				 return _incRate;
			}
			set
			{
				_incRate = value;
				_isDirty = true;
			}
		}
        public virtual decimal? WageAmt
        {
            get
            {
                return _wageamt;
            }
            set
            {
                _wageamt = value;
                _isDirty = true;
            }
        }

        public virtual decimal? IncNumber
		{
			get
			{
				 return _incNumber;
			}
			set
			{
				_incNumber = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? IncHours
		{
			get
			{
				 return _incHours;
			}
			set
			{
				_incHours = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? AcctNo
		{
			get
			{
				 return _acctNo;
			}
			set
			{
				_acctNo = value;
				_isDirty = true;
			}
		}
		
		public virtual string Department
		{
			get
			{
				 return _department;
			}
			set
			{
				_department = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? IncQtd1
		{
			get
			{
				 return _incQtd1;
			}
			set
			{
				_incQtd1 = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? IncQtd2
		{
			get
			{
				 return _incQtd2;
			}
			set
			{
				_incQtd2 = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? IncQtd3
		{
			get
			{
				 return _incQtd3;
			}
			set
			{
				_incQtd3 = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? IncQtd4
		{
			get
			{
				 return _incQtd4;
			}
			set
			{
				_incQtd4 = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? IncYtd
		{
			get
			{
				 return _incYtd;
			}
			set
			{
				_incYtd = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? LoIncAmt
		{
			get
			{
				 return _loIncAmt;
			}
			set
			{
				_loIncAmt = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? HiIncAmt
		{
			get
			{
				 return _hiIncAmt;
			}
			set
			{
				_hiIncAmt = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
