/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using C3WizardLayer.DataObjects.Interfaces;

namespace C3WizardLayer.DataObjects
{
	public partial class DLProcessPayDeductions : C3WizardLayerConn_BaseData
	{
		#region member variables
		protected Int32? _payDedID;
		protected Int64? _docNo;
		protected Int32? _lineNo;
		protected string _dedCode;
		protected decimal? _dedRate;
		protected decimal? _amount;
		protected Int32? _acctNo;
		protected string _department;
		protected Int16? _modFlag;
		protected string _addCode;
		protected decimal? _loDedAmt;
		protected decimal? _hiDedAmt;
		#endregion

		#region class methods
		public DLProcessPayDeductions()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table Process_PayDeductions based on the primary key(s)
		///</Summary>
		///<returns>
		///DLProcessPayDeductions
		///</returns>
		///<parameters>
		///Int32? payDedID
		///</parameters>
		public static DLProcessPayDeductions SelectOne(Int32? payDedID)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_SelectOne]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Process_PayDeductions");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@Pay_Ded_ID", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)payDedID?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				DLProcessPayDeductions retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DLProcessPayDeductions();
					retObj._payDedID					 = Convert.IsDBNull(dt.Rows[0]["Pay_Ded_ID"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Pay_Ded_ID"];
					retObj._docNo					 = Convert.IsDBNull(dt.Rows[0]["doc_no"]) ? (Int64?)null : (Int64?)dt.Rows[0]["doc_no"];
					retObj._lineNo					 = Convert.IsDBNull(dt.Rows[0]["line_no"]) ? (Int32?)null : (Int32?)dt.Rows[0]["line_no"];
					retObj._dedCode					 = Convert.IsDBNull(dt.Rows[0]["ded_code"]) ? null : (string)dt.Rows[0]["ded_code"];
					retObj._dedRate					 = Convert.IsDBNull(dt.Rows[0]["ded_rate"]) ? (decimal?)null : (decimal?)dt.Rows[0]["ded_rate"];
					retObj._amount					 = Convert.IsDBNull(dt.Rows[0]["amount"]) ? (decimal?)null : (decimal?)dt.Rows[0]["amount"];
					retObj._acctNo					 = Convert.IsDBNull(dt.Rows[0]["acct_no"]) ? (Int32?)null : (Int32?)dt.Rows[0]["acct_no"];
					retObj._department					 = Convert.IsDBNull(dt.Rows[0]["department"]) ? null : (string)dt.Rows[0]["department"];
					retObj._modFlag					 = Convert.IsDBNull(dt.Rows[0]["mod_flag"]) ? (Int16?)null : (Int16?)dt.Rows[0]["mod_flag"];
					retObj._addCode					 = Convert.IsDBNull(dt.Rows[0]["add_code"]) ? null : (string)dt.Rows[0]["add_code"];
					retObj._loDedAmt					 = Convert.IsDBNull(dt.Rows[0]["lo_ded_amt"]) ? (decimal?)null : (decimal?)dt.Rows[0]["lo_ded_amt"];
					retObj._hiDedAmt					 = Convert.IsDBNull(dt.Rows[0]["hi_ded_amt"]) ? (decimal?)null : (decimal?)dt.Rows[0]["hi_ded_amt"];
				}
				return retObj;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table Process_PayDeductions based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_DeleteOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@Pay_Ded_ID", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_payDedID?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table Process_PayDeductions
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_InsertOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@Pay_Ded_ID", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _payDedID));
				command.Parameters.Add(new SqlParameter("@doc_no", SqlDbType.BigInt, 8, ParameterDirection.InputOutput, true, 19, 0, "", DataRowVersion.Proposed, (object)_docNo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@line_no", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_lineNo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@ded_code", SqlDbType.VarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_dedCode?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@ded_rate", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_dedRate?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@amount", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_amount?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@acct_no", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_acctNo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@department", SqlDbType.VarChar, 3, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_department?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@mod_flag", SqlDbType.SmallInt, 2, ParameterDirection.InputOutput, true, 5, 0, "", DataRowVersion.Proposed, (object)_modFlag?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@add_code", SqlDbType.Char, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_addCode?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@lo_ded_amt", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_loDedAmt?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@hi_ded_amt", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_hiDedAmt?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_payDedID					 = Convert.IsDBNull(command.Parameters["@Pay_Ded_ID"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Pay_Ded_ID"].Value;
				_docNo					 = Convert.IsDBNull(command.Parameters["@doc_no"].Value) ? (Int64?)null : (Int64?)command.Parameters["@doc_no"].Value;
				_lineNo					 = Convert.IsDBNull(command.Parameters["@line_no"].Value) ? (Int32?)null : (Int32?)command.Parameters["@line_no"].Value;
				_dedCode					 = Convert.IsDBNull(command.Parameters["@ded_code"].Value) ? null : (string)command.Parameters["@ded_code"].Value;
				_dedRate					 = Convert.IsDBNull(command.Parameters["@ded_rate"].Value) ? (decimal?)null : (decimal?)command.Parameters["@ded_rate"].Value;
				_amount					 = Convert.IsDBNull(command.Parameters["@amount"].Value) ? (decimal?)null : (decimal?)command.Parameters["@amount"].Value;
				_acctNo					 = Convert.IsDBNull(command.Parameters["@acct_no"].Value) ? (Int32?)null : (Int32?)command.Parameters["@acct_no"].Value;
				_department					 = Convert.IsDBNull(command.Parameters["@department"].Value) ? null : (string)command.Parameters["@department"].Value;
				_modFlag					 = Convert.IsDBNull(command.Parameters["@mod_flag"].Value) ? (Int16?)null : (Int16?)command.Parameters["@mod_flag"].Value;
				_addCode					 = Convert.IsDBNull(command.Parameters["@add_code"].Value) ? null : (string)command.Parameters["@add_code"].Value;
				_loDedAmt					 = Convert.IsDBNull(command.Parameters["@lo_ded_amt"].Value) ? (decimal?)null : (decimal?)command.Parameters["@lo_ded_amt"].Value;
				_hiDedAmt					 = Convert.IsDBNull(command.Parameters["@hi_ded_amt"].Value) ? (decimal?)null : (decimal?)command.Parameters["@hi_ded_amt"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table Process_PayDeductions
		///</Summary>
		///<returns>
		///IList-DLProcessPayDeductions.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DLProcessPayDeductions> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_SelectAll]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Process_PayDeductions");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DLProcessPayDeductions> objList = new List<DLProcessPayDeductions>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DLProcessPayDeductions retObj = new DLProcessPayDeductions();
						retObj._payDedID					 = Convert.IsDBNull(row["Pay_Ded_ID"]) ? (Int32?)null : (Int32?)row["Pay_Ded_ID"];
						retObj._docNo					 = Convert.IsDBNull(row["doc_no"]) ? (Int64?)null : (Int64?)row["doc_no"];
						retObj._lineNo					 = Convert.IsDBNull(row["line_no"]) ? (Int32?)null : (Int32?)row["line_no"];
						retObj._dedCode					 = Convert.IsDBNull(row["ded_code"]) ? null : (string)row["ded_code"];
						retObj._dedRate					 = Convert.IsDBNull(row["ded_rate"]) ? (decimal?)null : (decimal?)row["ded_rate"];
						retObj._amount					 = Convert.IsDBNull(row["amount"]) ? (decimal?)null : (decimal?)row["amount"];
						retObj._acctNo					 = Convert.IsDBNull(row["acct_no"]) ? (Int32?)null : (Int32?)row["acct_no"];
						retObj._department					 = Convert.IsDBNull(row["department"]) ? null : (string)row["department"];
						retObj._modFlag					 = Convert.IsDBNull(row["mod_flag"]) ? (Int16?)null : (Int16?)row["mod_flag"];
						retObj._addCode					 = Convert.IsDBNull(row["add_code"]) ? null : (string)row["add_code"];
						retObj._loDedAmt					 = Convert.IsDBNull(row["lo_ded_amt"]) ? (decimal?)null : (decimal?)row["lo_ded_amt"];
						retObj._hiDedAmt					 = Convert.IsDBNull(row["hi_ded_amt"]) ? (decimal?)null : (decimal?)row["hi_ded_amt"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_SelectAllCount]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select specific fields of all rows using criteriaquery api
		///This method returns specific fields of all data rows in the table using criteriaquery apiProcess_PayDeductions
		///</Summary>
		///<returns>
		///IDictionary-string, IList-object..
		///</returns>
		///<parameters>
		///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_SelectAllByCriteriaProjection]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Process_PayDeductions");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				string fieldsField = GetProjections(listProjection);
				string whereClause = GetSelectionCriteria(listCriterion);
				string orderClause = GetSelectionOrder(listOrder);
				string skipClause = GetSelectionSkip(dataSkip);
				string takeClause = GetSelectionTake(dataTake);

				if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
					throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

				command.Parameters.Add(new SqlParameter("@FieldsField", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)fieldsField?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
				foreach (IDataProjection projection in listProjection)
				{
					IList<object> lst = new List<object>();
					dict.Add(projection.Member, lst);
					foreach (DataRow row in dt.Rows)
					{
						if (string.Compare(projection.Member, "Pay_Ded_ID", true) == 0) lst.Add(Convert.IsDBNull(row["Pay_Ded_ID"]) ? (Int32?)null : (Int32?)row["Pay_Ded_ID"]);
						if (string.Compare(projection.Member, "doc_no", true) == 0) lst.Add(Convert.IsDBNull(row["doc_no"]) ? (Int64?)null : (Int64?)row["doc_no"]);
						if (string.Compare(projection.Member, "line_no", true) == 0) lst.Add(Convert.IsDBNull(row["line_no"]) ? (Int32?)null : (Int32?)row["line_no"]);
						if (string.Compare(projection.Member, "ded_code", true) == 0) lst.Add(Convert.IsDBNull(row["ded_code"]) ? null : (string)row["ded_code"]);
						if (string.Compare(projection.Member, "ded_rate", true) == 0) lst.Add(Convert.IsDBNull(row["ded_rate"]) ? (decimal?)null : (decimal?)row["ded_rate"]);
						if (string.Compare(projection.Member, "amount", true) == 0) lst.Add(Convert.IsDBNull(row["amount"]) ? (decimal?)null : (decimal?)row["amount"]);
						if (string.Compare(projection.Member, "acct_no", true) == 0) lst.Add(Convert.IsDBNull(row["acct_no"]) ? (Int32?)null : (Int32?)row["acct_no"]);
						if (string.Compare(projection.Member, "department", true) == 0) lst.Add(Convert.IsDBNull(row["department"]) ? null : (string)row["department"]);
						if (string.Compare(projection.Member, "mod_flag", true) == 0) lst.Add(Convert.IsDBNull(row["mod_flag"]) ? (Int16?)null : (Int16?)row["mod_flag"]);
						if (string.Compare(projection.Member, "add_code", true) == 0) lst.Add(Convert.IsDBNull(row["add_code"]) ? null : (string)row["add_code"]);
						if (string.Compare(projection.Member, "lo_ded_amt", true) == 0) lst.Add(Convert.IsDBNull(row["lo_ded_amt"]) ? (decimal?)null : (decimal?)row["lo_ded_amt"]);
						if (string.Compare(projection.Member, "hi_ded_amt", true) == 0) lst.Add(Convert.IsDBNull(row["hi_ded_amt"]) ? (decimal?)null : (decimal?)row["hi_ded_amt"]);
					}
				}
				return dict;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by filter criteria
		///This method returns all data rows in the table using criteriaquery api Process_PayDeductions
		///</Summary>
		///<returns>
		///IList-DLProcessPayDeductions.
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IList<DLProcessPayDeductions> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_SelectAllByCriteria]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Process_PayDeductions");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				string whereClause = GetSelectionCriteria(listCriterion);
				string orderClause = GetSelectionOrder(listOrder);
				string skipClause = GetSelectionSkip(dataSkip);
				string takeClause = GetSelectionTake(dataTake);

				if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
					throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DLProcessPayDeductions> objList = new List<DLProcessPayDeductions>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DLProcessPayDeductions retObj = new DLProcessPayDeductions();
						retObj._payDedID					 = Convert.IsDBNull(row["Pay_Ded_ID"]) ? (Int32?)null : (Int32?)row["Pay_Ded_ID"];
						retObj._docNo					 = Convert.IsDBNull(row["doc_no"]) ? (Int64?)null : (Int64?)row["doc_no"];
						retObj._lineNo					 = Convert.IsDBNull(row["line_no"]) ? (Int32?)null : (Int32?)row["line_no"];
						retObj._dedCode					 = Convert.IsDBNull(row["ded_code"]) ? null : (string)row["ded_code"];
						retObj._dedRate					 = Convert.IsDBNull(row["ded_rate"]) ? (decimal?)null : (decimal?)row["ded_rate"];
						retObj._amount					 = Convert.IsDBNull(row["amount"]) ? (decimal?)null : (decimal?)row["amount"];
						retObj._acctNo					 = Convert.IsDBNull(row["acct_no"]) ? (Int32?)null : (Int32?)row["acct_no"];
						retObj._department					 = Convert.IsDBNull(row["department"]) ? null : (string)row["department"];
						retObj._modFlag					 = Convert.IsDBNull(row["mod_flag"]) ? (Int16?)null : (Int16?)row["mod_flag"];
						retObj._addCode					 = Convert.IsDBNull(row["add_code"]) ? null : (string)row["add_code"];
						retObj._loDedAmt					 = Convert.IsDBNull(row["lo_ded_amt"]) ? (decimal?)null : (decimal?)row["lo_ded_amt"];
						retObj._hiDedAmt					 = Convert.IsDBNull(row["hi_ded_amt"]) ? (decimal?)null : (decimal?)row["hi_ded_amt"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select count of all rows using criteriaquery api
		///This method returns all data rows in the table using criteriaquery api Process_PayDeductions
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion
		///</parameters>
		public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_SelectAllByCriteriaCount]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				string whereClause = GetSelectionCriteria(listCriterion);
				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table Process_PayDeductions based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprProcess_PayDeductions_UpdateOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@Pay_Ded_ID", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_payDedID?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@doc_no", SqlDbType.BigInt, 8, ParameterDirection.InputOutput, true, 19, 0, "", DataRowVersion.Proposed, (object)_docNo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@line_no", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_lineNo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@ded_code", SqlDbType.VarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_dedCode?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@ded_rate", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_dedRate?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@amount", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_amount?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@acct_no", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_acctNo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@department", SqlDbType.VarChar, 3, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_department?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@mod_flag", SqlDbType.SmallInt, 2, ParameterDirection.InputOutput, true, 5, 0, "", DataRowVersion.Proposed, (object)_modFlag?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@add_code", SqlDbType.Char, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_addCode?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@lo_ded_amt", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_loDedAmt?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@hi_ded_amt", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_hiDedAmt?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_payDedID					 = Convert.IsDBNull(command.Parameters["@Pay_Ded_ID"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Pay_Ded_ID"].Value;
				_docNo					 = Convert.IsDBNull(command.Parameters["@doc_no"].Value) ? (Int64?)null : (Int64?)command.Parameters["@doc_no"].Value;
				_lineNo					 = Convert.IsDBNull(command.Parameters["@line_no"].Value) ? (Int32?)null : (Int32?)command.Parameters["@line_no"].Value;
				_dedCode					 = Convert.IsDBNull(command.Parameters["@ded_code"].Value) ? null : (string)command.Parameters["@ded_code"].Value;
				_dedRate					 = Convert.IsDBNull(command.Parameters["@ded_rate"].Value) ? (decimal?)null : (decimal?)command.Parameters["@ded_rate"].Value;
				_amount					 = Convert.IsDBNull(command.Parameters["@amount"].Value) ? (decimal?)null : (decimal?)command.Parameters["@amount"].Value;
				_acctNo					 = Convert.IsDBNull(command.Parameters["@acct_no"].Value) ? (Int32?)null : (Int32?)command.Parameters["@acct_no"].Value;
				_department					 = Convert.IsDBNull(command.Parameters["@department"].Value) ? null : (string)command.Parameters["@department"].Value;
				_modFlag					 = Convert.IsDBNull(command.Parameters["@mod_flag"].Value) ? (Int16?)null : (Int16?)command.Parameters["@mod_flag"].Value;
				_addCode					 = Convert.IsDBNull(command.Parameters["@add_code"].Value) ? null : (string)command.Parameters["@add_code"].Value;
				_loDedAmt					 = Convert.IsDBNull(command.Parameters["@lo_ded_amt"].Value) ? (decimal?)null : (decimal?)command.Parameters["@lo_ded_amt"].Value;
				_hiDedAmt					 = Convert.IsDBNull(command.Parameters["@hi_ded_amt"].Value) ? (decimal?)null : (decimal?)command.Parameters["@hi_ded_amt"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? PayDedID
		{
			get
			{
				return _payDedID;
			}
			set
			{
				_payDedID = value;
			}
		}

		public Int64? DocNo
		{
			get
			{
				return _docNo;
			}
			set
			{
				_docNo = value;
			}
		}

		public Int32? LineNo
		{
			get
			{
				return _lineNo;
			}
			set
			{
				_lineNo = value;
			}
		}

		public string DedCode
		{
			get
			{
				return _dedCode;
			}
			set
			{
				_dedCode = value;
			}
		}

		public decimal? DedRate
		{
			get
			{
				return _dedRate;
			}
			set
			{
				_dedRate = value;
			}
		}

		public decimal? Amount
		{
			get
			{
				return _amount;
			}
			set
			{
				_amount = value;
			}
		}

		public Int32? AcctNo
		{
			get
			{
				return _acctNo;
			}
			set
			{
				_acctNo = value;
			}
		}

		public string Department
		{
			get
			{
				return _department;
			}
			set
			{
				_department = value;
			}
		}

		public Int16? ModFlag
		{
			get
			{
				return _modFlag;
			}
			set
			{
				_modFlag = value;
			}
		}

		public string AddCode
		{
			get
			{
				return _addCode;
			}
			set
			{
				_addCode = value;
			}
		}

		public decimal? LoDedAmt
		{
			get
			{
				return _loDedAmt;
			}
			set
			{
				_loDedAmt = value;
			}
		}

		public decimal? HiDedAmt
		{
			get
			{
				return _hiDedAmt;
			}
			set
			{
				_hiDedAmt = value;
			}
		}

		#endregion
	}
}
