/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using C3WizardLayer.DataObjects;
using C3WizardLayer.DataObjects.Interfaces;
using C3WizardLayer.BusinessObjects.Interfaces;

namespace C3WizardLayer.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BLMasterEmployee.
	///</Summary>
	public partial class BLPayrollProcessDetail : C3WizardLayerConn_BaseBusiness, IQueryableCollection
	{
        
		#region member variables
	    protected Int32? _pybatchid;
        protected Int32? _batchprocessid;
        protected string _processname;
        protected string _employeetype;
        protected DateTime? _processendedon;
        protected Int32? _recordsprocessed;
        protected Int32? _companyid;
        
		protected string _searchcriteria;
        
        protected Int32? _insertby;
		protected DateTime? _insertdate;
		protected string _insertmachineinfo;
		protected Int32? _updateby;
		protected DateTime? _updatedate;
		protected string _updatemachineinfo;
		
		protected bool _isDirty = false;
		
       /*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BLPayrollProcessDetail()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 employeeID
		///</parameters>
		public BLPayrollProcessDetail(Int32 pybatchid)
		{
			try
			{
                
                DLPayrollProcessDetails dlPayrollProcessDetails = DLPayrollProcessDetails.SelectOne(pybatchid);
                _pybatchid = dlPayrollProcessDetails.pybatchid;
                _batchprocessid = dlPayrollProcessDetails.batchprocessid;
                _processname = dlPayrollProcessDetails.processname;
                _employeetype = dlPayrollProcessDetails.employeetype;
                _processendedon = dlPayrollProcessDetails.processendedon;
                _companyid = dlPayrollProcessDetails.companyid;
                _recordsprocessed = dlPayrollProcessDetails.recordsprocessed;
                _searchcriteria = dlPayrollProcessDetails.searchcriteria;
                _insertby = dlPayrollProcessDetails.insertby;
                _insertdate = dlPayrollProcessDetails.insertdate;
                _insertmachineinfo = dlPayrollProcessDetails.insertmachineinfo;
                _updateby = dlPayrollProcessDetails.updateby;
                _updatedate = dlPayrollProcessDetails.updatedate;
                _updatemachineinfo = dlPayrollProcessDetails.updatemachineinfo;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DLMasterEmployee
		///</parameters>
        protected internal BLPayrollProcessDetail(DLPayrollProcessDetails dlPayrollProcessDetails)
		{
			try
			{
                _pybatchid = dlPayrollProcessDetails.pybatchid;
                _batchprocessid = dlPayrollProcessDetails.batchprocessid;
                _processname = dlPayrollProcessDetails.processname;
                _employeetype = dlPayrollProcessDetails.employeetype;
                _processendedon = dlPayrollProcessDetails.processendedon;
                _companyid = dlPayrollProcessDetails.companyid;
                _recordsprocessed = dlPayrollProcessDetails.recordsprocessed;
                _searchcriteria = dlPayrollProcessDetails.searchcriteria;
                _insertby = dlPayrollProcessDetails.insertby;
                _insertdate = dlPayrollProcessDetails.insertdate;
                _insertmachineinfo = dlPayrollProcessDetails.insertmachineinfo;
                _updateby = dlPayrollProcessDetails.updateby;
                _updatedate = dlPayrollProcessDetails.updatedate;
                _updatemachineinfo = dlPayrollProcessDetails.updatemachineinfo;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new MasterEmployee record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
        public virtual void SaveNew(int companyid)
        {
            DLPayrollProcessDetails dlPayrollProcessDetail = new DLPayrollProcessDetails();
            RegisterDataObject(dlPayrollProcessDetail);
            BeginTransaction("savenewBLPayrollProcessDetail");
            try
            {
                
                dlPayrollProcessDetail.batchprocessid = _batchprocessid;
                dlPayrollProcessDetail.processname = _processname;
                dlPayrollProcessDetail.employeetype = _employeetype;
                dlPayrollProcessDetail.processendedon = _processendedon;
                dlPayrollProcessDetail.companyid = _companyid;
                dlPayrollProcessDetail.recordsprocessed = _recordsprocessed;
                
                dlPayrollProcessDetail.searchcriteria = _searchcriteria;
                
                dlPayrollProcessDetail.insertby = _insertby;
                dlPayrollProcessDetail.insertdate = _insertdate;
                dlPayrollProcessDetail.insertmachineinfo = _insertmachineinfo;
                dlPayrollProcessDetail.updateby = _updateby;
                dlPayrollProcessDetail.updatedate = _updatedate;
                dlPayrollProcessDetail.updatemachineinfo = _updatemachineinfo;

               
                


                dlPayrollProcessDetail.Insert(companyid);
                CommitTransaction();
                
                _pybatchid = dlPayrollProcessDetail.pybatchid;
                _batchprocessid = dlPayrollProcessDetail.batchprocessid;
                _processname = dlPayrollProcessDetail.processname;
                _employeetype= dlPayrollProcessDetail.employeetype;
                _processendedon = dlPayrollProcessDetail.processendedon;
                _companyid = dlPayrollProcessDetail.companyid;
                _recordsprocessed = dlPayrollProcessDetail.recordsprocessed;
                
                _searchcriteria = dlPayrollProcessDetail.searchcriteria;
                
                _insertby = dlPayrollProcessDetail.insertby;
                _insertdate = dlPayrollProcessDetail.insertdate;
                _insertmachineinfo = dlPayrollProcessDetail.insertmachineinfo;
                _updateby = dlPayrollProcessDetail.updateby;
                _updatedate = dlPayrollProcessDetail.updatedate;
                _updatemachineinfo = dlPayrollProcessDetail.updatemachineinfo;
                _isDirty = false;
            }
            catch
            {
                RollbackTransaction("savenewBLPayrollProcessDetail");
                throw;
            }
        }

        ///<Summary>
        ///Update
        ///This method updates one MasterCompany record in the store
        ///</Summary>
        ///<returns>
        ///void
        ///</returns>
        ///<parameters>
        ///BLMasterCompany
        ///</parameters>
        public virtual void Update(int UserId)
        {
            DLPayrollProcessDetails dlPayrollProcessDetail = new DLPayrollProcessDetails();
            RegisterDataObject(dlPayrollProcessDetail);
            BeginTransaction("updateBLPayrollProcessDetail");
            try
            {
                
                dlPayrollProcessDetail.pybatchid = _pybatchid;
                dlPayrollProcessDetail.batchprocessid = _batchprocessid;
                dlPayrollProcessDetail.processname = _processname;
                dlPayrollProcessDetail.employeetype = _employeetype;
                dlPayrollProcessDetail.processendedon = _processendedon;
                dlPayrollProcessDetail.companyid = _companyid;
                dlPayrollProcessDetail.recordsprocessed = _recordsprocessed;
                
                dlPayrollProcessDetail.searchcriteria = _searchcriteria;
                
                dlPayrollProcessDetail.insertby = _insertby;
                dlPayrollProcessDetail.insertdate = _insertdate;
                dlPayrollProcessDetail.insertmachineinfo = _insertmachineinfo;
                dlPayrollProcessDetail.updateby = _updateby;
                dlPayrollProcessDetail.updatedate = _updatedate;
                dlPayrollProcessDetail.updatemachineinfo = _updatemachineinfo;

                dlPayrollProcessDetail.Update(UserId);
                CommitTransaction();


                _pybatchid = dlPayrollProcessDetail.pybatchid;
                _batchprocessid = dlPayrollProcessDetail.batchprocessid;
                _processname = dlPayrollProcessDetail.processname;
                _employeetype = dlPayrollProcessDetail.employeetype;
                _processendedon = dlPayrollProcessDetail.processendedon;
                _companyid = dlPayrollProcessDetail.companyid;
                _recordsprocessed = dlPayrollProcessDetail.recordsprocessed;

                _searchcriteria = dlPayrollProcessDetail.searchcriteria;

                _insertby = dlPayrollProcessDetail.insertby;
                _insertdate = dlPayrollProcessDetail.insertdate;
                _insertmachineinfo = dlPayrollProcessDetail.insertmachineinfo;
                _updateby = dlPayrollProcessDetail.updateby;
                _updatedate = dlPayrollProcessDetail.updatedate;
                _updatemachineinfo = dlPayrollProcessDetail.updatemachineinfo;
                _isDirty = false;
            }
            catch
            {
                RollbackTransaction("updateBLPayrollProcessDetail");
                throw;
            }
        }
        ///<Summary>
        ///Delete
        ///This method deletes one MasterCompany record from the store
        ///</Summary>
        ///<returns>
        ///void
        ///</returns>
        ///<parameters>
        ///
        ///</parameters>
        public virtual void Delete()
        {
            DLPayrollProcessDetails dlPayrollProcessDetails = new DLPayrollProcessDetails();
            RegisterDataObject(dlPayrollProcessDetails);
            BeginTransaction("deleteBLPayrollProcessDetail");
            try
            {
                dlPayrollProcessDetails.pybatchid = _pybatchid;
                dlPayrollProcessDetails.Delete();
                CommitTransaction();
            }
            catch
            {
                RollbackTransaction("deleteBLPayrollProcessDetail");
                throw;
            }
        }

        ///<Summary>
        ///MasterCompanyCollection
        ///This method returns the collection of BLMasterCompany objects
        ///</Summary>
        ///<returns>
        ///List[BLMasterCompany]
        ///</returns>
        ///<parameters>
        ///
        ///</parameters>
        public static IList<BLPayrollProcessDetail> MasterPayrollProcessHeaderCollection()
        {
            try
            {
                IList<BLPayrollProcessDetail> blMasterPayrollProcessHeaderCollection = new List<BLPayrollProcessDetail>();
                IList<DLPayrollProcessDetails> dlMasterPayrollProcessHeaderCollection = DLPayrollProcessDetails.SelectAll();

                foreach (DLPayrollProcessDetails dlMasterCompany in dlMasterPayrollProcessHeaderCollection)
                    blMasterPayrollProcessHeaderCollection.Add(new BLPayrollProcessDetail(dlMasterCompany));

                return blMasterPayrollProcessHeaderCollection;
            }
            catch
            {
                throw;
            }
        }


        ///<Summary>
        ///MasterCompanyCollectionCount
        ///This method returns the collection count of BLMasterCompany objects
        ///</Summary>
        ///<returns>
        ///Int32
        ///</returns>
        ///<parameters>
        ///
        ///</parameters>
        public static Int32 MasterPayrollProcessHeaderCollectionCount()
        {
            try
            {
                Int32 objCount = DLPayrollProcessDetails.SelectAllCount();
                return objCount;
            }
            catch
            {
                throw;
            }
        }


        ///<Summary>
        ///Projections
        ///This method returns the collection of projections, ordered and filtered by optional criteria
        ///</Summary>
        ///<returns>
        ///List<BLMasterCompany>
        ///</returns>
        ///<parameters>
        ///ICriteria icriteria
        ///</parameters>
        public virtual IDictionary<string, IList<object>> Projections(object o)
        {
            try
            {
                ICriteria icriteria = (ICriteria)o;
                IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
                IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
                IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
                IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
                IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
                IDictionary<string, IList<object>> retObj = DLPayrollProcessDetails.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
                return retObj;
            }
            catch
            {
                throw;
            }
        }


        ///<Summary>
        ///MasterCompanyCollection<T>
        ///This method implements the IQueryable Collection<T> method, returning a collection of BLMasterCompany objects, filtered by optional criteria
        ///</Summary>
        ///<returns>
        ///IList<T>
        ///</returns>
        ///<parameters>
        ///object o
        ///</parameters>
        public virtual IList<T> Collection<T>(object o)
        {
            try
            {
                ICriteria icriteria = (ICriteria)o;
                IList<T> blMasterCompanyCollection = new List<T>();
                IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
                IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
                IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
                IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
                IList<DLPayrollProcessDetails> dlMasterPayrollProcessHeaderCollection = DLPayrollProcessDetails.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);

                foreach (DLPayrollProcessDetails resdlMasterCompany in dlMasterPayrollProcessHeaderCollection)
                    blMasterCompanyCollection.Add((T)(object)new BLPayrollProcessDetail(resdlMasterCompany));

                return blMasterCompanyCollection;
            }
            catch
            {
                throw;
            }
        }


        ///<Summary>
        ///MasterCompanyCollectionCount
        ///This method implements the IQueryable CollectionCount method, returning a collection count of BLMasterCompany objects, filtered by optional criteria
        ///</Summary>
        ///<returns>
        ///Int32
        ///</returns>
        ///<parameters>
        ///object o
        ///</parameters>
        public virtual Int32 CollectionCount(object o)
        {
            try
            {
                ICriteria icriteria = (ICriteria)o;
                IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
                Int32 objCount = DLPayrollProcessDetails.SelectAllByCriteriaCount(lstDataCriteria);
                return objCount;
            }
            catch
            {
                throw;
            }
        }

        #endregion

        #region member properties

        public virtual Int32? pybatchid
        {
            get
            {
                return _pybatchid;
            }
            set
            {
                _pybatchid = value;
                _isDirty = true;
            }
        }

        public virtual Int32? batchprocessid
        {
            get
            {
                return _batchprocessid;
            }
            set
            {
                _batchprocessid = value;
                _isDirty = true;
            }
        }
        public virtual string processname
        {
            get
            {
                return _processname;
            }
            set
            {
                _processname = value;
                _isDirty = true;
            }
        }
        public virtual string employeetype
        {
            get
            {
                return _employeetype;
            }
            set
            {
                _employeetype = value;
                _isDirty = true;
            }
        }
        public virtual DateTime? processendedon
        {
            get
            {
                return _processendedon;
            }
            set
            {
                _processendedon = value;
                _isDirty = true;
            }
        }
        public virtual Int32? companyid
        {
            get
            {
                return _companyid;
            }
            set
            {
                _companyid = value;
                _isDirty = true;
            }
        }
        public virtual Int32? recordsprocessed
        {
            get
            {
                return _recordsprocessed;
            }
            set
            {
                _recordsprocessed = value;
                _isDirty = true;
            }
        }
        public virtual string searchcriteria
        {
            get
            {
                return _searchcriteria;
            }
            set
            {
                _searchcriteria = value;
                _isDirty = true;
            }
        }
        public virtual Int32? insertby
        {
            get
            {
                return _insertby;
            }
            set
            {
                _insertby = value;

            }
        }
        public virtual DateTime? insertdate
        {
            get
            {
                return _insertdate;
            }
            set
            {
                _insertdate = value;
                _isDirty = true;
            }
        }
        public virtual string insertmachineinfo
        {
            get
            {
                return _insertmachineinfo;
            }
            set
            {
                _insertmachineinfo = value;
                _isDirty = true;
            }
        }
        public virtual Int32? updateby
        {
            get
            {
                return _updateby;
            }
            set
            {
                _updateby = value;
                _isDirty = true;
            }
        }
        public virtual DateTime? updatedate
        {
            get
            {
                return _updatedate;
            }
            set
            {
                _updatedate = value;
                _isDirty = true;
            }
        }
        public virtual string updatemachineinfo
        {
            get
            {
                return _updatemachineinfo;
            }
            set
            {
                _updatemachineinfo = value;
                _isDirty = true;
            }
        }

        
        public virtual object Repository
        {
            get { return null; }
            set { }
        }

        public virtual bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            set
            {
                _isDirty = value;
            }
        }
        #endregion
	}
}
