-- Allow explicit legacy ID insertion for MasterCompany
-- Fixes: "cannot insert a non-DEFAULT value into column company_id"
ALTER TABLE public.c3_master_company
  ALTER COLUMN company_id SET GENERATED BY DEFAULT;