-- =====================================================
-- DROP ALL EXISTING TABLES (in correct order for FK dependencies)
-- =====================================================

-- Drop tables with foreign key dependencies first
DROP TABLE IF EXISTS "HolidayPayDates" CASCADE;
DROP TABLE IF EXISTS "MasterHolidayPayDetails" CASCADE;
DROP TABLE IF EXISTS "BonusPayDetails" CASCADE;
DROP TABLE IF EXISTS "MasterEmployeeDeductions" CASCADE;
DROP TABLE IF EXISTS "MasterEmployeeIncomes" CASCADE;
DROP TABLE IF EXISTS "MasterEmployeeObligations" CASCADE;
DROP TABLE IF EXISTS "MasterEmployerCodes" CASCADE;
DROP TABLE IF EXISTS "EmployeeTCard_Details" CASCADE;
DROP TABLE IF EXISTS "EmployeeTCard_Header" CASCADE;
DROP TABLE IF EXISTS "EmployeeWorkDurationDetails" CASCADE;
DROP TABLE IF EXISTS "Deductions_Tax_Table_Details" CASCADE;
DROP TABLE IF EXISTS "City" CASCADE;
DROP TABLE IF EXISTS "State" CASCADE;

-- Drop main tables
DROP TABLE IF EXISTS "MasterEmployee" CASCADE;
DROP TABLE IF EXISTS "MasterCompany" CASCADE;
DROP TABLE IF EXISTS "SelfEmployee" CASCADE;
DROP TABLE IF EXISTS "SECUsers" CASCADE;
DROP TABLE IF EXISTS "SECUsersProfile" CASCADE;
DROP TABLE IF EXISTS "SECRole" CASCADE;
DROP TABLE IF EXISTS "SECModule" CASCADE;
DROP TABLE IF EXISTS "SECUserModule" CASCADE;
DROP TABLE IF EXISTS "UserPermission" CASCADE;
DROP TABLE IF EXISTS "SecurityQuestionAnswer" CASCADE;
DROP TABLE IF EXISTS "UserOtp" CASCADE;
DROP TABLE IF EXISTS "UserCardDetail" CASCADE;

-- Drop C3/Contribution tables
DROP TABLE IF EXISTS "PROCESS_C3Header" CASCADE;
DROP TABLE IF EXISTS "Process_Contributions" CASCADE;
DROP TABLE IF EXISTS "PROCESS_Self_EmployedC3" CASCADE;

-- Drop Rate/Config tables
DROP TABLE IF EXISTS "Master_Rate_Setting" CASCADE;
DROP TABLE IF EXISTS "Deductions_Tax_Table_Header" CASCADE;
DROP TABLE IF EXISTS "WageCategories" CASCADE;
DROP TABLE IF EXISTS "WagesPayDetails" CASCADE;
DROP TABLE IF EXISTS "Self_Employed_Settings" CASCADE;
DROP TABLE IF EXISTS "DECEMBER_BONUS_EXEMPTED_CONTRIBUTION" CASCADE;
DROP TABLE IF EXISTS "NWD_Master_Rate_Settings" CASCADE;
DROP TABLE IF EXISTS "SiteSettings" CASCADE;

-- Drop Payroll tables
DROP TABLE IF EXISTS "Payroll_Process_Header" CASCADE;
DROP TABLE IF EXISTS "Payroll_Process_Details" CASCADE;
DROP TABLE IF EXISTS "Process_PayEmployee" CASCADE;
DROP TABLE IF EXISTS "Process_PayDeductions" CASCADE;
DROP TABLE IF EXISTS "Process_PayIncomes" CASCADE;
DROP TABLE IF EXISTS "Process_Payobligations" CASCADE;

-- Drop Payment tables
DROP TABLE IF EXISTS "OnlinePayments" CASCADE;
DROP TABLE IF EXISTS "BankPaymentsMain" CASCADE;
DROP TABLE IF EXISTS "Reconciliation_Cyber_Space" CASCADE;
DROP TABLE IF EXISTS "Reconciliation_Cyber_Space_Column" CASCADE;
DROP TABLE IF EXISTS "ReconciliationPayment_Details" CASCADE;

-- Drop Code/Lookup tables
DROP TABLE IF EXISTS "MasterDeductionCodes" CASCADE;
DROP TABLE IF EXISTS "MasterIncCodes" CASCADE;
DROP TABLE IF EXISTS "MasterObligationCodes" CASCADE;
DROP TABLE IF EXISTS "MasterEmpType" CASCADE;
DROP TABLE IF EXISTS "Country" CASCADE;

-- Drop Audit/Log tables
DROP TABLE IF EXISTS "AuditLogs" CASCADE;
DROP TABLE IF EXISTS "LoginLog" CASCADE;
DROP TABLE IF EXISTS "CustomErrorLogs" CASCADE;
DROP TABLE IF EXISTS "ErrorLog" CASCADE;
DROP TABLE IF EXISTS "Exception_log" CASCADE;
DROP TABLE IF EXISTS "ContactUs_Log" CASCADE;

-- Drop CMS tables
DROP TABLE IF EXISTS "AboutUs" CASCADE;

-- Drop user_roles if exists
DROP TABLE IF EXISTS "user_roles" CASCADE;
DROP TYPE IF EXISTS app_role CASCADE;

-- =====================================================
-- CREATE SECRole FIRST (referenced by SECUsers)
-- =====================================================
CREATE TABLE "SECRole" (
  "RoleId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleName" VARCHAR(100) NOT NULL,
  "RoleDescription" VARCHAR(500),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(255),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(255),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "ParentRoleId" INTEGER
);

-- =====================================================
-- CREATE SECModule (for permissions)
-- =====================================================
CREATE TABLE "SECModule" (
  "ModuleId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ModuleName" VARCHAR(100) NOT NULL,
  "ModuleDescription" VARCHAR(500),
  "ModuleCode" VARCHAR(50),
  "ModuleUrl" VARCHAR(500),
  "ModuleIcon" VARCHAR(100),
  "ParentModuleId" INTEGER,
  "SortOrder" INTEGER DEFAULT 0,
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(255),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(255),
  "IsMenuItem" BOOLEAN DEFAULT TRUE
);

-- =====================================================
-- CREATE MasterCompany (exact MS SQL column names)
-- =====================================================
CREATE TABLE "MasterCompany" (
  "Company_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_Name" VARCHAR(255) NOT NULL,
  "Trade_Name" VARCHAR(255),
  "REG_NUMBER" VARCHAR(50),
  "Address1" VARCHAR(255),
  "Address2" VARCHAR(255),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "ZIP" VARCHAR(20),
  "Country" VARCHAR(100),
  "Mobile" VARCHAR(50),
  "Landline" VARCHAR(50),
  "FAX" VARCHAR(50),
  "Contact_Person" VARCHAR(255),
  "Email" VARCHAR(255),
  "CompanyLogo" TEXT,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(255),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(255),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "IsLevyExempt" BOOLEAN DEFAULT FALSE,
  "Parent_Id" INTEGER DEFAULT 0,
  "Tokan" VARCHAR(255),
  "IsVerified" BOOLEAN DEFAULT TRUE,
  "regDate" TIMESTAMP WITH TIME ZONE,
  "Checked" VARCHAR(10),
  "officeCode" VARCHAR(10)
);

-- =====================================================
-- CREATE SelfEmployee (exact MS SQL column names)
-- =====================================================
CREATE TABLE "SelfEmployee" (
  "SelfEmpID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "REG_NUMBER" VARCHAR(50),
  "Soc_Sec_Num" VARCHAR(20),
  "First_Name" VARCHAR(100) NOT NULL,
  "Middle_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100) NOT NULL,
  "BirthDate" DATE,
  "Gender" VARCHAR(1),
  "Marital_Stat" VARCHAR(1),
  "Address1" VARCHAR(255),
  "Address2" VARCHAR(255),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Country" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Phone" VARCHAR(50),
  "Mobile" VARCHAR(50),
  "Email" VARCHAR(255),
  "TIN" VARCHAR(50),
  "BusinessName" VARCHAR(255),
  "BusinessType" VARCHAR(100),
  "Occupation" VARCHAR(100),
  "Industry" VARCHAR(100),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(255),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(255),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Tokan" VARCHAR(255),
  "IsVerified" BOOLEAN DEFAULT TRUE,
  "regDate" TIMESTAMP WITH TIME ZONE,
  "Checked" VARCHAR(10),
  "officeCode" VARCHAR(10),
  "Category_Type" INTEGER,
  "Is_Wage_Category_From_API" BOOLEAN DEFAULT FALSE,
  "Annual_Salary" NUMERIC(18,2),
  "Pay_Period" VARCHAR(10),
  "Joining_Date" TIMESTAMP WITH TIME ZONE,
  "Termination_Date" TIMESTAMP WITH TIME ZONE,
  "LastLoginTime" TIMESTAMP WITH TIME ZONE,
  "IsLoggedIn" BOOLEAN DEFAULT FALSE,
  "UserExpiresOn" TIMESTAMP WITH TIME ZONE,
  "PwdExpiresOn" TIMESTAMP WITH TIME ZONE,
  "LastPwdUpddate" TIMESTAMP WITH TIME ZONE
);

-- =====================================================
-- CREATE SECUsers (exact MS SQL column names)
-- =====================================================
CREATE TABLE "SECUsers" (
  "UserId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" VARCHAR(100) NOT NULL,
  "LastName" VARCHAR(100) NOT NULL,
  "MiddleName" VARCHAR(100),
  "LoginId" VARCHAR(100) NOT NULL,
  "Password" VARCHAR(255),
  "EmailId" VARCHAR(255),
  "SelfEmpID" VARCHAR(20) DEFAULT '0',
  "EmpId" VARCHAR(20),
  "Department" VARCHAR(100),
  "RoleId" INTEGER REFERENCES "SECRole"("RoleId"),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(255),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(255),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "IsSelfEmployee" BOOLEAN DEFAULT FALSE,
  "LastLoginTime" TIMESTAMP WITH TIME ZONE,
  "IsLoggedIn" BOOLEAN DEFAULT FALSE,
  "UserExpiresOn" TIMESTAMP WITH TIME ZONE,
  "PwdExpiresOn" TIMESTAMP WITH TIME ZONE,
  "LastPwdUpddate" TIMESTAMP WITH TIME ZONE,
  "Status" INTEGER DEFAULT 1,
  "UserImage" TEXT,
  "parentuserid" INTEGER DEFAULT 0,
  "IsPPOC" BOOLEAN DEFAULT TRUE,
  "REG_NUMBER" VARCHAR(50),
  "token" VARCHAR(255),
  "userstts" VARCHAR(10) DEFAULT 'A'
);

-- =====================================================
-- CREATE SECUsersProfile (exact MS SQL column names)
-- =====================================================
CREATE TABLE "SECUsersProfile" (
  "ProfileId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" INTEGER REFERENCES "SECUsers"("UserId"),
  "Address1" VARCHAR(255),
  "Address2" VARCHAR(255),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Country" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Phone" VARCHAR(50),
  "Mobile" VARCHAR(50),
  "Fax" VARCHAR(50),
  "ProfileImage" TEXT,
  "IsActive" BOOLEAN DEFAULT TRUE
);

-- =====================================================
-- CREATE MasterEmployee (exact MS SQL column names)
-- =====================================================
CREATE TABLE "MasterEmployee" (
  "EmployeeID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Empl_Code" VARCHAR(50),
  "Soc_Sec_Num" VARCHAR(20),
  "First_Name" VARCHAR(100) NOT NULL,
  "Middle_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100) NOT NULL,
  "Type_Code" VARCHAR(10),
  "BirthDate" TIMESTAMP WITH TIME ZONE,
  "Gender" VARCHAR(1),
  "Address1" VARCHAR(255),
  "Address2" VARCHAR(255),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Country" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Phone" VARCHAR(50),
  "Mobile" VARCHAR(50),
  "Email" VARCHAR(255),
  "TIN" VARCHAR(50),
  "Appint_Date" TIMESTAMP WITH TIME ZONE,
  "Last_Pay_Date" TIMESTAMP WITH TIME ZONE,
  "Wages_Pay_Date" TIMESTAMP WITH TIME ZONE,
  "Terminated" TIMESTAMP WITH TIME ZONE,
  "Empl_Status" VARCHAR(10),
  "Pay_Period" VARCHAR(10),
  "AllowAnces" NUMERIC(18,2),
  "State_Allow" NUMERIC(18,2),
  "Marital_Stat" VARCHAR(1),
  "Hold_Pymnt" BOOLEAN,
  "Bank_Acct_No" VARCHAR(50),
  "State_udf" VARCHAR(50),
  "FlexDeptAcctType" VARCHAR(50),
  "Last_Inc_Date" TIMESTAMP WITH TIME ZONE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(255),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(255),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "occupation" VARCHAR(100),
  "CompanyId" INTEGER REFERENCES "MasterCompany"("Company_Id"),
  "IsdirectorOnly" BOOLEAN DEFAULT FALSE,
  "isemployeeDirector" BOOLEAN DEFAULT FALSE,
  "IsLevyExempt" BOOLEAN DEFAULT FALSE,
  "department" VARCHAR(100),
  "isFileCreatedEmp" BOOLEAN DEFAULT FALSE
);