-- ===========================================
-- DROP ALL EXISTING c3_ TABLES
-- ===========================================

DROP TABLE IF EXISTS public.c3_reconciliation_payment_details CASCADE;
DROP TABLE IF EXISTS public.c3_reconciliation_cyber_space_column CASCADE;
DROP TABLE IF EXISTS public.c3_reconciliation_cyber_space CASCADE;
DROP TABLE IF EXISTS public.c3_process_self_employed_c3 CASCADE;
DROP TABLE IF EXISTS public.c3_process_pay_obligations CASCADE;
DROP TABLE IF EXISTS public.c3_process_pay_incomes CASCADE;
DROP TABLE IF EXISTS public.c3_process_pay_employee CASCADE;
DROP TABLE IF EXISTS public.c3_process_pay_deductions CASCADE;
DROP TABLE IF EXISTS public.c3_process_contributions CASCADE;
DROP TABLE IF EXISTS public.c3_process_c3_header CASCADE;
DROP TABLE IF EXISTS public.c3_payroll_process_details CASCADE;
DROP TABLE IF EXISTS public.c3_payroll_process_header CASCADE;
DROP TABLE IF EXISTS public.c3_online_payments CASCADE;
DROP TABLE IF EXISTS public.c3_nwd_master_rate_settings CASCADE;
DROP TABLE IF EXISTS public.c3_master_rate_setting CASCADE;
DROP TABLE IF EXISTS public.c3_master_obligation_codes CASCADE;
DROP TABLE IF EXISTS public.c3_master_inc_codes CASCADE;
DROP TABLE IF EXISTS public.c3_master_holiday_pay_details CASCADE;
DROP TABLE IF EXISTS public.c3_master_employer_codes CASCADE;
DROP TABLE IF EXISTS public.c3_master_employee_obligations CASCADE;
DROP TABLE IF EXISTS public.c3_master_employee_incomes CASCADE;
DROP TABLE IF EXISTS public.c3_master_employee_deductions CASCADE;
DROP TABLE IF EXISTS public.c3_master_employee CASCADE;
DROP TABLE IF EXISTS public.c3_master_emp_type CASCADE;
DROP TABLE IF EXISTS public.c3_master_deduction_codes CASCADE;
DROP TABLE IF EXISTS public.c3_master_company CASCADE;
DROP TABLE IF EXISTS public.c3_login_log CASCADE;
DROP TABLE IF EXISTS public.c3_holiday_pay_dates CASCADE;
DROP TABLE IF EXISTS public.c3_exception_log CASCADE;
DROP TABLE IF EXISTS public.c3_error_log CASCADE;
DROP TABLE IF EXISTS public.c3_employee_work_duration_details CASCADE;
DROP TABLE IF EXISTS public.c3_employee_tcard_header CASCADE;
DROP TABLE IF EXISTS public.c3_employee_tcard_details CASCADE;
DROP TABLE IF EXISTS public.c3_deductions_tax_table_header CASCADE;
DROP TABLE IF EXISTS public.c3_deductions_tax_table_details CASCADE;
DROP TABLE IF EXISTS public.c3_december_bonus_exempted_contribution CASCADE;
DROP TABLE IF EXISTS public.c3_custom_error_logs CASCADE;
DROP TABLE IF EXISTS public.c3_country CASCADE;
DROP TABLE IF EXISTS public.c3_contact_us_log CASCADE;
DROP TABLE IF EXISTS public.c3_city CASCADE;
DROP TABLE IF EXISTS public.c3_bonus_pay_details CASCADE;
DROP TABLE IF EXISTS public.c3_bank_payments_main CASCADE;
DROP TABLE IF EXISTS public.c3_audit_logs CASCADE;
DROP TABLE IF EXISTS public.c3_about_us CASCADE;
DROP TABLE IF EXISTS public.c3_wages_pay_details CASCADE;
DROP TABLE IF EXISTS public.c3_wage_categories CASCADE;
DROP TABLE IF EXISTS public.c3_user_permission CASCADE;
DROP TABLE IF EXISTS public.c3_user_otp CASCADE;
DROP TABLE IF EXISTS public.c3_user_card_detail CASCADE;
DROP TABLE IF EXISTS public.c3_state CASCADE;
DROP TABLE IF EXISTS public.c3_site_settings CASCADE;
DROP TABLE IF EXISTS public.c3_self_employee CASCADE;
DROP TABLE IF EXISTS public.c3_self_employed_settings CASCADE;
DROP TABLE IF EXISTS public.c3_sec_users_profile CASCADE;
DROP TABLE IF EXISTS public.c3_sec_users CASCADE;
DROP TABLE IF EXISTS public.c3_sec_user_module CASCADE;
DROP TABLE IF EXISTS public.c3_sec_role CASCADE;
DROP TABLE IF EXISTS public.c3_sec_module CASCADE;
DROP TABLE IF EXISTS public.c3_security_question_answer CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TYPE IF EXISTS public.app_role CASCADE;

-- ===========================================
-- CREATE LEGACY TABLES WITH EXACT MS SQL NAMES
-- Using BOOLEAN instead of BIT (PostgreSQL compatible)
-- Phase 1: Reference/Lookup Tables
-- ===========================================

-- Country table
CREATE TABLE public."Country" (
  "ConId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "Name" VARCHAR(100),
  "Description" VARCHAR(50),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" VARCHAR(20),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- State table
CREATE TABLE public."State" (
  "StateID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "StateName" VARCHAR(100),
  "StateCode" VARCHAR(10),
  "ConId" INTEGER REFERENCES public."Country"("ConId"),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- City table
CREATE TABLE public."City" (
  "CityID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "CityName" VARCHAR(100),
  "CityCode" VARCHAR(10),
  "StateID" INTEGER REFERENCES public."State"("StateID"),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- ===========================================
-- Phase 2: Auth/Security Tables
-- ===========================================

-- SECRole table
CREATE TABLE public."SECRole" (
  "RoleID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "RoleName" VARCHAR(100) NOT NULL,
  "Description" VARCHAR(500),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- SECModule table
CREATE TABLE public."SECModule" (
  "ModuleID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "ModuleName" VARCHAR(100),
  "ModuleDescription" VARCHAR(500),
  "ParentModuleID" INTEGER,
  "ModuleURL" VARCHAR(500),
  "DisplayOrder" INTEGER,
  "Icon" VARCHAR(100),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500),
  "IsMenu" BOOLEAN DEFAULT TRUE,
  "RoleID" INTEGER
);

-- MasterCompany table (create before SECUsers for FK)
CREATE TABLE public."MasterCompany" (
  "CompanyID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "CompanyName" VARCHAR(200) NOT NULL,
  "TradeName" VARCHAR(200),
  "RegNumber" VARCHAR(50),
  "RegDate" TIMESTAMP WITH TIME ZONE,
  "Address1" VARCHAR(500),
  "Address2" VARCHAR(500),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Country" VARCHAR(100),
  "Landline" VARCHAR(50),
  "Mobile" VARCHAR(50),
  "Fax" VARCHAR(50),
  "Email" VARCHAR(200),
  "ContactPerson" VARCHAR(200),
  "OfficeCode" VARCHAR(50),
  "CompanyLogo" TEXT,
  "IsActive" BOOLEAN DEFAULT TRUE,
  "IsVerified" BOOLEAN DEFAULT FALSE,
  "IsLevyExempt" BOOLEAN DEFAULT FALSE,
  "ParentID" INTEGER,
  "Checked" VARCHAR(10),
  "Tokan" VARCHAR(500),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- SelfEmployee table (create before SECUsers for FK)
CREATE TABLE public."SelfEmployee" (
  "SelfEmployeeID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "Soc_Sec_Num" VARCHAR(50),
  "First_Name" VARCHAR(100) NOT NULL,
  "Middle_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100) NOT NULL,
  "BirthDate" TIMESTAMP WITH TIME ZONE,
  "Gender" VARCHAR(10),
  "Marital_Stat" VARCHAR(20),
  "Address1" VARCHAR(500),
  "Address2" VARCHAR(500),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Country" VARCHAR(100),
  "Phone" VARCHAR(50),
  "Mobile" VARCHAR(50),
  "Email" VARCHAR(200),
  "TIN" VARCHAR(50),
  "BusinessName" VARCHAR(200),
  "BusinessType" VARCHAR(100),
  "Occupation" VARCHAR(200),
  "Industry" VARCHAR(200),
  "WageCategoryID" INTEGER,
  "RegNumber" VARCHAR(50),
  "RegDate" TIMESTAMP WITH TIME ZONE,
  "IsActive" BOOLEAN DEFAULT TRUE,
  "IsVerified" BOOLEAN DEFAULT FALSE,
  "Status" VARCHAR(20),
  "Tokan" VARCHAR(500),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500),
  "EffectiveDate" TIMESTAMP WITH TIME ZONE,
  "EndDate" TIMESTAMP WITH TIME ZONE,
  "AnnualIncome" NUMERIC(18,2),
  "MonthlyIncome" NUMERIC(18,2),
  "WeeklyIncome" NUMERIC(18,2),
  "DailyIncome" NUMERIC(18,2),
  "PayPeriod" VARCHAR(20),
  "IsLevyExempt" BOOLEAN DEFAULT FALSE,
  "ParentID" INTEGER,
  "OfficeCode" VARCHAR(50),
  "Checked" VARCHAR(10)
);

-- SECUsers table
CREATE TABLE public."SECUsers" (
  "UserID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "UserName" VARCHAR(100),
  "Password" VARCHAR(500),
  "Email" VARCHAR(200),
  "FirstName" VARCHAR(100),
  "LastName" VARCHAR(100),
  "Phone" VARCHAR(50),
  "Mobile" VARCHAR(50),
  "RoleID" INTEGER REFERENCES public."SECRole"("RoleID"),
  "CompanyID" INTEGER REFERENCES public."MasterCompany"("CompanyID"),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "IsLocked" BOOLEAN DEFAULT FALSE,
  "LastLoginDate" TIMESTAMP WITH TIME ZONE,
  "PasswordExpiryDate" TIMESTAMP WITH TIME ZONE,
  "FailedLoginAttempts" INTEGER DEFAULT 0,
  "IsPasswordReset" BOOLEAN DEFAULT FALSE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500),
  "Token" VARCHAR(500),
  "TokenExpiry" TIMESTAMP WITH TIME ZONE,
  "SelfEmployeeID" INTEGER REFERENCES public."SelfEmployee"("SelfEmployeeID"),
  "IsVerified" BOOLEAN DEFAULT FALSE,
  "VerificationToken" VARCHAR(500),
  "VerificationTokenExpiry" TIMESTAMP WITH TIME ZONE
);

-- SECUsersProfile table
CREATE TABLE public."SECUsersProfile" (
  "ProfileID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "UserID" INTEGER REFERENCES public."SECUsers"("UserID"),
  "Address1" VARCHAR(500),
  "Address2" VARCHAR(500),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Country" VARCHAR(100),
  "ProfileImage" VARCHAR(500),
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedMachineInfo" VARCHAR(500)
);

-- SECUserModule table
CREATE TABLE public."SECUserModule" (
  "UserModuleID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "UserID" INTEGER REFERENCES public."SECUsers"("UserID"),
  "ModuleID" INTEGER REFERENCES public."SECModule"("ModuleID"),
  "RoleID" INTEGER REFERENCES public."SECRole"("RoleID"),
  "CanView" BOOLEAN DEFAULT FALSE,
  "CanAdd" BOOLEAN DEFAULT FALSE,
  "CanEdit" BOOLEAN DEFAULT FALSE,
  "CanDelete" BOOLEAN DEFAULT FALSE,
  "CanPrint" BOOLEAN DEFAULT FALSE,
  "CanExport" BOOLEAN DEFAULT FALSE,
  "CanImport" BOOLEAN DEFAULT FALSE,
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500),
  "CanApprove" BOOLEAN DEFAULT FALSE,
  "CanReject" BOOLEAN DEFAULT FALSE,
  "CanSubmit" BOOLEAN DEFAULT FALSE,
  "CanProcess" BOOLEAN DEFAULT FALSE,
  "CanViewAll" BOOLEAN DEFAULT FALSE,
  "CanViewOwn" BOOLEAN DEFAULT FALSE,
  "CanViewCompany" BOOLEAN DEFAULT FALSE
);

-- SecurityQuestionAnswer table
CREATE TABLE public."SecurityQuestionAnswer" (
  "SQAID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "UserID" INTEGER REFERENCES public."SECUsers"("UserID"),
  "Question1" VARCHAR(500),
  "Answer1" VARCHAR(500),
  "Question2" VARCHAR(500),
  "Answer2" VARCHAR(500),
  "Question3" VARCHAR(500),
  "Answer3" VARCHAR(500),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- UserPermission table
CREATE TABLE public."UserPermission" (
  "PermissionID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "UserID" INTEGER REFERENCES public."SECUsers"("UserID"),
  "PermissionName" VARCHAR(200),
  "IsAllowed" BOOLEAN DEFAULT TRUE,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- UserOtp table
CREATE TABLE public."UserOtp" (
  "OtpID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "UserID" INTEGER REFERENCES public."SECUsers"("UserID"),
  "OtpCode" VARCHAR(10),
  "ExpiryDate" TIMESTAMP WITH TIME ZONE,
  "IsUsed" BOOLEAN DEFAULT FALSE,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ===========================================
-- Phase 3: Employee Tables
-- ===========================================

-- MasterEmpType table
CREATE TABLE public."MasterEmpType" (
  "EmpTypeID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "EmpTypeName" VARCHAR(100) NOT NULL,
  "Description" VARCHAR(500),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- MasterEmployee table
CREATE TABLE public."MasterEmployee" (
  "EmpID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "CompanyID" INTEGER REFERENCES public."MasterCompany"("CompanyID"),
  "Soc_Sec_Num" VARCHAR(50),
  "First_Name" VARCHAR(100) NOT NULL,
  "Middle_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100) NOT NULL,
  "BirthDate" TIMESTAMP WITH TIME ZONE,
  "Gender" VARCHAR(10),
  "Marital_Stat" VARCHAR(20),
  "Address1" VARCHAR(500),
  "Address2" VARCHAR(500),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Country" VARCHAR(100),
  "Phone" VARCHAR(50),
  "Mobile" VARCHAR(50),
  "Email" VARCHAR(200),
  "TIN" VARCHAR(50),
  "Occupation" VARCHAR(200),
  "Empl_Code" VARCHAR(50),
  "Empl_Status" VARCHAR(20),
  "Pay_Period" VARCHAR(20),
  "Joining_Date" TIMESTAMP WITH TIME ZONE,
  "Termination_Date" TIMESTAMP WITH TIME ZONE,
  "Last_Pay_Date" TIMESTAMP WITH TIME ZONE,
  "Last_Inc_Date" TIMESTAMP WITH TIME ZONE,
  "Annual_Salary" NUMERIC(18,2),
  "Allowances" NUMERIC(18,2),
  "State_Allow" INTEGER,
  "State_UDF" VARCHAR(50),
  "Bank_Acct_No" VARCHAR(50),
  "Flex_Dept_Acct_Type" VARCHAR(50),
  "OfficeCode" VARCHAR(50),
  "Category_Type" INTEGER,
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Is_Levy_Exempt" BOOLEAN DEFAULT FALSE,
  "Is_Employee_Director" BOOLEAN DEFAULT FALSE,
  "Is_Director_Only" BOOLEAN DEFAULT FALSE,
  "Is_Wage_Category_From_API" BOOLEAN DEFAULT FALSE,
  "Checked" VARCHAR(10),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- MasterEmployerCodes table
CREATE TABLE public."MasterEmployerCodes" (
  "EmployerCodeID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "CompanyID" INTEGER REFERENCES public."MasterCompany"("CompanyID"),
  "Code" VARCHAR(50),
  "Description" VARCHAR(500),
  "IsActive" BOOLEAN DEFAULT TRUE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);