-- ===========================================
-- Phase 7: C3 Form/Contribution Tables
-- ===========================================

-- PROCESS_C3Header table
CREATE TABLE public."PROCESS_C3Header" (
  "C3HeaderID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "CompanyID" INTEGER REFERENCES public."MasterCompany"("CompanyID"),
  "Period_Year" VARCHAR(10),
  "Period_Month" VARCHAR(10),
  "RegNumber" VARCHAR(50),
  "CompanyName" VARCHAR(200),
  "Address1" VARCHAR(500),
  "Address2" VARCHAR(500),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Phone" VARCHAR(50),
  "Fax" VARCHAR(50),
  "Email" VARCHAR(200),
  "TotalEmployees" INTEGER,
  "TotalInsurable" NUMERIC(18,2),
  "TotalSS_EE" NUMERIC(18,2),
  "TotalSS_ER" NUMERIC(18,2),
  "TotalSeverance" NUMERIC(18,2),
  "TotalLevy_EE" NUMERIC(18,2),
  "TotalLevy_ER" NUMERIC(18,2),
  "TotalContribution" NUMERIC(18,2),
  "Penalty" NUMERIC(18,2),
  "Fine" NUMERIC(18,2),
  "GrandTotal" NUMERIC(18,2),
  "Status" VARCHAR(50),
  "SubmittedDate" TIMESTAMP WITH TIME ZONE,
  "ApprovedDate" TIMESTAMP WITH TIME ZONE,
  "ApprovedBy" INTEGER,
  "RejectedDate" TIMESTAMP WITH TIME ZONE,
  "RejectedBy" INTEGER,
  "RejectReason" TEXT,
  "PaymentStatus" VARCHAR(50),
  "PaymentDate" TIMESTAMP WITH TIME ZONE,
  "PaymentReference" VARCHAR(100),
  "IsFiled" BOOLEAN DEFAULT FALSE,
  "IsLocked" BOOLEAN DEFAULT FALSE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500),
  "C3Type" VARCHAR(50),
  "Remarks" TEXT
);

-- Process_Contributions table
CREATE TABLE public."Process_Contributions" (
  "ContributionID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "C3HeaderID" INTEGER REFERENCES public."PROCESS_C3Header"("C3HeaderID"),
  "CompanyID" INTEGER,
  "EmployeeID" INTEGER REFERENCES public."MasterEmployee"("EmpID"),
  "Period_Year" VARCHAR(10),
  "Period_Month" VARCHAR(10),
  "Soc_Sec_Num" VARCHAR(50),
  "First_Name" VARCHAR(100),
  "Middle_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100),
  "BirthDate" TIMESTAMP WITH TIME ZONE,
  "Gender" VARCHAR(10),
  "WageCategory" VARCHAR(100),
  "InsurableEarnings" NUMERIC(18,2),
  "SS_EE_Rate" NUMERIC(10,4),
  "SS_ER_Rate" NUMERIC(10,4),
  "SS_EE" NUMERIC(18,2),
  "SS_ER" NUMERIC(18,2),
  "Severance_Rate" NUMERIC(10,4),
  "Severance" NUMERIC(18,2),
  "Levy_EE_Rate" NUMERIC(10,4),
  "Levy_ER_Rate" NUMERIC(10,4),
  "Levy_EE" NUMERIC(18,2),
  "Levy_ER" NUMERIC(18,2),
  "TotalContribution" NUMERIC(18,2),
  "IsDirector" BOOLEAN DEFAULT FALSE,
  "IsDirectorOnly" BOOLEAN DEFAULT FALSE,
  "IsLevyExempt" BOOLEAN DEFAULT FALSE,
  "WeeksWorked" INTEGER,
  "DaysWorked" INTEGER,
  "HoursWorked" NUMERIC(18,2),
  "Status" VARCHAR(50),
  "Remarks" TEXT,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500),
  "Empl_Code" VARCHAR(50),
  "Pay_Period" VARCHAR(20),
  "Joining_Date" TIMESTAMP WITH TIME ZONE,
  "Termination_Date" TIMESTAMP WITH TIME ZONE
);

-- PROCESS_Self_EmployedC3 table
CREATE TABLE public."PROCESS_Self_EmployedC3" (
  "SelfC3ID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "SelfEmployeeID" INTEGER REFERENCES public."SelfEmployee"("SelfEmployeeID"),
  "Period_Year" VARCHAR(10),
  "Period_Month" VARCHAR(10),
  "Soc_Sec_Num" VARCHAR(50),
  "First_Name" VARCHAR(100),
  "Middle_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100),
  "BirthDate" TIMESTAMP WITH TIME ZONE,
  "Gender" VARCHAR(10),
  "Address1" VARCHAR(500),
  "Address2" VARCHAR(500),
  "City" VARCHAR(100),
  "State" VARCHAR(100),
  "Zip" VARCHAR(20),
  "Phone" VARCHAR(50),
  "Email" VARCHAR(200),
  "BusinessName" VARCHAR(200),
  "Occupation" VARCHAR(200),
  "WageCategoryID" INTEGER,
  "WageCategory" VARCHAR(200),
  "InsurableEarnings" NUMERIC(18,2),
  "SS_EE_Rate" NUMERIC(10,4),
  "SS_ER_Rate" NUMERIC(10,4),
  "SS_EE" NUMERIC(18,2),
  "SS_ER" NUMERIC(18,2),
  "Severance_Rate" NUMERIC(10,4),
  "Severance" NUMERIC(18,2),
  "Levy_EE_Rate" NUMERIC(10,4),
  "Levy_EE" NUMERIC(18,2),
  "TotalContribution" NUMERIC(18,2),
  "Penalty" NUMERIC(18,2),
  "Fine" NUMERIC(18,2),
  "GrandTotal" NUMERIC(18,2),
  "Status" VARCHAR(50),
  "SubmittedDate" TIMESTAMP WITH TIME ZONE,
  "ApprovedDate" TIMESTAMP WITH TIME ZONE,
  "ApprovedBy" INTEGER,
  "PaymentStatus" VARCHAR(50),
  "PaymentDate" TIMESTAMP WITH TIME ZONE,
  "PaymentReference" VARCHAR(100),
  "IsFiled" BOOLEAN DEFAULT FALSE,
  "IsLocked" BOOLEAN DEFAULT FALSE,
  "Deletable" BOOLEAN DEFAULT TRUE,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500),
  "Remarks" TEXT
);

-- ===========================================
-- Phase 8: Payroll Tables
-- ===========================================

-- Payroll_Process_Header table
CREATE TABLE public."Payroll_Process_Header" (
  "PayrollHeaderID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "CompanyID" INTEGER REFERENCES public."MasterCompany"("CompanyID"),
  "PayrollDate" TIMESTAMP WITH TIME ZONE,
  "Period_Year" VARCHAR(10),
  "Period_Month" VARCHAR(10),
  "PayPeriod" VARCHAR(20),
  "StartDate" TIMESTAMP WITH TIME ZONE,
  "EndDate" TIMESTAMP WITH TIME ZONE,
  "TotalEmployees" INTEGER,
  "TotalGross" NUMERIC(18,2),
  "TotalDeductions" NUMERIC(18,2),
  "TotalNet" NUMERIC(18,2),
  "Status" VARCHAR(50),
  "IsProcessed" BOOLEAN DEFAULT FALSE,
  "ProcessedDate" TIMESTAMP WITH TIME ZONE,
  "ProcessedBy" INTEGER,
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- Payroll_Process_Details table
CREATE TABLE public."Payroll_Process_Details" (
  "PayrollDetailID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "PayrollHeaderID" INTEGER REFERENCES public."Payroll_Process_Header"("PayrollHeaderID"),
  "EmployeeID" INTEGER REFERENCES public."MasterEmployee"("EmpID"),
  "GrossAmount" NUMERIC(18,2),
  "TotalDeductions" NUMERIC(18,2),
  "NetAmount" NUMERIC(18,2),
  "Status" VARCHAR(50),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- Process_PayEmployee table
CREATE TABLE public."Process_PayEmployee" (
  "PayEmployeeID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "PayrollHeaderID" INTEGER,
  "EmployeeID" INTEGER,
  "CompanyID" INTEGER,
  "Period_Year" VARCHAR(10),
  "Period_Month" VARCHAR(10),
  "PayPeriod" VARCHAR(20),
  "GrossPay" NUMERIC(18,2),
  "TotalIncomes" NUMERIC(18,2),
  "TotalDeductions" NUMERIC(18,2),
  "TotalObligations" NUMERIC(18,2),
  "NetPay" NUMERIC(18,2),
  "Status" VARCHAR(50),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500),
  "Soc_Sec_Num" VARCHAR(50),
  "First_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100),
  "BirthDate" TIMESTAMP WITH TIME ZONE,
  "HoursWorked" NUMERIC(18,2),
  "DaysWorked" INTEGER,
  "WeeksWorked" INTEGER,
  "OvertimeHours" NUMERIC(18,2),
  "OvertimePay" NUMERIC(18,2),
  "BonusPay" NUMERIC(18,2),
  "HolidayPay" NUMERIC(18,2),
  "VacationPay" NUMERIC(18,2),
  "SickPay" NUMERIC(18,2)
);

-- Process_PayIncomes table
CREATE TABLE public."Process_PayIncomes" (
  "PayIncomeID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "PayEmployeeID" INTEGER,
  "EmployeeID" INTEGER,
  "IncCodeID" INTEGER,
  "IncCode" VARCHAR(50),
  "IncDescription" VARCHAR(200),
  "Amount" NUMERIC(18,2),
  "Hours" NUMERIC(18,2),
  "Rate" NUMERIC(18,4),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- Process_PayDeductions table
CREATE TABLE public."Process_PayDeductions" (
  "PayDeductionID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "PayEmployeeID" INTEGER,
  "EmployeeID" INTEGER,
  "DedCodeID" INTEGER,
  "DedCode" VARCHAR(50),
  "DedDescription" VARCHAR(200),
  "Amount" NUMERIC(18,2),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- Process_Payobligations table
CREATE TABLE public."Process_Payobligations" (
  "PayObligationID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "PayEmployeeID" INTEGER,
  "EmployeeID" INTEGER,
  "OblCodeID" INTEGER,
  "OblCode" VARCHAR(50),
  "OblDescription" VARCHAR(200),
  "Amount" NUMERIC(18,2),
  "InsertedBy" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InsertedMachineInfo" VARCHAR(500),
  "UpdatedBy" INTEGER,
  "UpdatedOn" TIMESTAMP WITH TIME ZONE,
  "UpdatedMachineInfo" VARCHAR(500)
);

-- ===========================================
-- Phase 9: Time Card Tables
-- ===========================================

-- EmployeeTCard_Header table
CREATE TABLE public."EmployeeTCard_Header" (
  "TCardHeaderID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "CompanyID" INTEGER,
  "EmployeeID" INTEGER,
  "PeriodStart" TIMESTAMP WITH TIME ZONE,
  "PeriodEnd" TIMESTAMP WITH TIME ZONE,
  "TotalHours" NUMERIC(18,2),
  "Status" VARCHAR(50),
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "UpdatedOn" TIMESTAMP WITH TIME ZONE
);

-- EmployeeTCard_Details table
CREATE TABLE public."EmployeeTCard_Details" (
  "TCardDetailID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "TCardHeaderID" INTEGER REFERENCES public."EmployeeTCard_Header"("TCardHeaderID"),
  "WorkDate" TIMESTAMP WITH TIME ZONE,
  "TimeIn" TIMESTAMP WITH TIME ZONE,
  "TimeOut" TIMESTAMP WITH TIME ZONE,
  "BreakHours" NUMERIC(18,2),
  "HoursWorked" NUMERIC(18,2),
  "OvertimeHours" NUMERIC(18,2),
  "Notes" TEXT
);

-- EmployeeWorkDurationDetails table
CREATE TABLE public."EmployeeWorkDurationDetails" (
  "WorkDurationID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "CompanyID" INTEGER,
  "EmployeeID" INTEGER,
  "Period_Year" VARCHAR(10),
  "Period_Month" VARCHAR(10),
  "WeeksWorked" INTEGER,
  "DaysWorked" INTEGER,
  "HoursWorked" NUMERIC(18,2),
  "OvertimeHours" NUMERIC(18,2),
  "VacationDays" INTEGER,
  "SickDays" INTEGER,
  "InsertedOn" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "UpdatedOn" TIMESTAMP WITH TIME ZONE
);