/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Data.SqlClient;
using System.Collections.Generic;
using C3WizardLayer.DataObjects.Interfaces;

namespace C3WizardLayer.DataObjects
{
  public partial class DLMasterEmployee : C3WizardLayerConn_BaseData
  {
    #region member variables
    protected Int32? _employeeID;
    protected string _emplCode;
    protected string _socSecNum;
    protected string _firstName;
    protected string _middleName;
    protected string _lastName;
    protected string _typeCode;
    protected DateTime? _birthDate;
    protected string _gender;
    protected string _address1;
    protected string _address2;
    protected string _city;
    protected string _state;
    protected string _country;
    protected string _zip;
    protected string _phone;
    protected string _mobile;
    protected string _email;
    protected string _tin;
    protected DateTime? _appintDate;
    protected DateTime? _lastpaydate;
    protected DateTime? _terminated;
    protected DateTime? _wagespayDate;
    protected string _emplStatus;
    protected string _payPeriod;
    protected string _payPeriodforlist;
    protected Int32? _allowAnces;
    protected Int32? _stateAllow;
    protected string _maritalStat;
    protected string _holdPymnt;
    protected string _bankAcctNo;
    protected decimal? _stateUdf;
    protected string _flexDeptAcctType;
    protected DateTime? _lastIncDate;
    protected Int32? _insertedBy;
    protected DateTime? _insertedOn;
    protected string _insertedMachineInfo;
    protected Int32? _updatedBy;
    protected DateTime? _updatedOn;
    protected string _updatedMachineInfo;
    protected bool? _isActive;
    protected string _occupation;
    protected Int32? _companyid;
    protected decimal? _wadeg;
    protected decimal? _wage_Amt;
    protected string _ApDate;
    protected string _TrDate;
    protected bool? _IsdirectorOnly;
    protected bool? _IsemployeeDirector;
    protected bool? _isLevyExempt;
    protected string _IsempDirector;
    protected string _IsempDirectorimg;
    protected string _emptype;
    protected Int32 _emp_S_no;
    protected string _department;
    #endregion

    #region class methods
    public DLMasterEmployee()
    {
    }
    ///<Summary>
    ///Select one row by primary key(s)
    ///This method returns one row from the table MasterEmployee based on the primary key(s)
    ///</Summary>
    ///<returns>
    ///DLMasterEmployee
    ///</returns>
    ///<parameters>
    ///Int32? employeeID
    ///</parameters>
    public static DLMasterEmployee SelectOne(Int32? employeeID)
    {


      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_SelectOne]";
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;

      DataTable dt = new DataTable("MasterEmployee");
      SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
      try
      {
        command.Parameters.Add(new SqlParameter("@EmployeeID", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)employeeID ?? (object)DBNull.Value));

        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        sqlAdapter.Fill(dt);

        DLMasterEmployee retObj = null;
        if (dt.Rows.Count > 0)
        {
          retObj = new DLMasterEmployee();
          retObj._employeeID = Convert.IsDBNull(dt.Rows[0]["EmployeeID"]) ? (Int32?)null : (Int32?)dt.Rows[0]["EmployeeID"];
          retObj._emplCode = Convert.IsDBNull(dt.Rows[0]["Empl_Code"]) ? null : (string)dt.Rows[0]["Empl_Code"];
          retObj._socSecNum = Convert.IsDBNull(dt.Rows[0]["Soc_Sec_Num"]) ? null : (string)dt.Rows[0]["Soc_Sec_Num"];
          retObj._firstName = Convert.IsDBNull(dt.Rows[0]["First_Name"]) ? null : (string)dt.Rows[0]["First_Name"];
          retObj._middleName = Convert.IsDBNull(dt.Rows[0]["Middle_Name"]) ? null : (string)dt.Rows[0]["Middle_Name"];
          retObj._lastName = Convert.IsDBNull(dt.Rows[0]["Last_Name"]) ? null : (string)dt.Rows[0]["Last_Name"];
          retObj._typeCode = Convert.IsDBNull(dt.Rows[0]["Type_Code"]) ? null : (string)dt.Rows[0]["Type_Code"];
          retObj._birthDate = Convert.IsDBNull(dt.Rows[0]["BirthDate"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["BirthDate"];
          retObj._gender = Convert.IsDBNull(dt.Rows[0]["Gender"]) ? null : (string)dt.Rows[0]["Gender"];
          retObj._address1 = Convert.IsDBNull(dt.Rows[0]["Address1"]) ? null : (string)dt.Rows[0]["Address1"];
          retObj._address2 = Convert.IsDBNull(dt.Rows[0]["Address2"]) ? null : (string)dt.Rows[0]["Address2"];
          retObj._city = Convert.IsDBNull(dt.Rows[0]["City"]) ? null : (string)dt.Rows[0]["City"];
          retObj._state = Convert.IsDBNull(dt.Rows[0]["State"]) ? null : (string)dt.Rows[0]["State"];
          retObj._country = Convert.IsDBNull(dt.Rows[0]["Country"]) ? null : (string)dt.Rows[0]["Country"];
          retObj._zip = Convert.IsDBNull(dt.Rows[0]["Zip"]) ? null : (string)dt.Rows[0]["Zip"];
          retObj._phone = Convert.IsDBNull(dt.Rows[0]["Phone"]) ? null : (string)dt.Rows[0]["Phone"];
          retObj._mobile = Convert.IsDBNull(dt.Rows[0]["Mobile"]) ? null : (string)dt.Rows[0]["Mobile"];
          retObj._email = Convert.IsDBNull(dt.Rows[0]["Email"]) ? null : (string)dt.Rows[0]["Email"];
          retObj._tin = Convert.IsDBNull(dt.Rows[0]["TIN"]) ? null : (string)dt.Rows[0]["TIN"];
          retObj._appintDate = Convert.IsDBNull(dt.Rows[0]["Appint_Date"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["Appint_Date"];
          retObj._lastpaydate = Convert.IsDBNull(dt.Rows[0]["Last_Pay_Date"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["Last_Pay_Date"];
          retObj._terminated = Convert.IsDBNull(dt.Rows[0]["Terminated"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["Terminated"];
          retObj._wagespayDate = Convert.IsDBNull(dt.Rows[0]["Wages_Pay_Date"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["Wages_Pay_Date"];
          retObj._emplStatus = Convert.IsDBNull(dt.Rows[0]["Empl_Status"]) ? null : (string)dt.Rows[0]["Empl_Status"];
          retObj._payPeriod = Convert.IsDBNull(dt.Rows[0]["Pay_Period"]) ? null : (string)dt.Rows[0]["Pay_Period"];
          retObj._allowAnces = Convert.IsDBNull(dt.Rows[0]["AllowAnces"]) ? (Int32?)null : (Int32?)dt.Rows[0]["AllowAnces"];
          retObj._stateAllow = Convert.IsDBNull(dt.Rows[0]["State_Allow"]) ? (Int32?)null : (Int32?)dt.Rows[0]["State_Allow"];
          retObj._maritalStat = Convert.IsDBNull(dt.Rows[0]["Marital_Stat"]) ? null : (string)dt.Rows[0]["Marital_Stat"];
          retObj._holdPymnt = Convert.IsDBNull(dt.Rows[0]["Hold_Pymnt"]) ? null : (string)dt.Rows[0]["Hold_Pymnt"];
          retObj._bankAcctNo = Convert.IsDBNull(dt.Rows[0]["Bank_Acct_No"]) ? null : (string)dt.Rows[0]["Bank_Acct_No"];
          retObj._stateUdf = Convert.IsDBNull(dt.Rows[0]["State_udf"]) ? (decimal?)null : (decimal?)dt.Rows[0]["State_udf"];
          retObj._flexDeptAcctType = Convert.IsDBNull(dt.Rows[0]["FlexDeptAcctType"]) ? null : (string)dt.Rows[0]["FlexDeptAcctType"];
          retObj._lastIncDate = Convert.IsDBNull(dt.Rows[0]["Last_Inc_Date"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["Last_Inc_Date"];
          retObj._insertedBy = Convert.IsDBNull(dt.Rows[0]["InsertedBy"]) ? (Int32?)null : (Int32?)dt.Rows[0]["InsertedBy"];
          retObj._insertedOn = Convert.IsDBNull(dt.Rows[0]["InsertedOn"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["InsertedOn"];
          retObj._insertedMachineInfo = Convert.IsDBNull(dt.Rows[0]["InsertedMachineInfo"]) ? null : (string)dt.Rows[0]["InsertedMachineInfo"];
          retObj._updatedBy = Convert.IsDBNull(dt.Rows[0]["UpdatedBy"]) ? (Int32?)null : (Int32?)dt.Rows[0]["UpdatedBy"];
          retObj._updatedOn = Convert.IsDBNull(dt.Rows[0]["UpdatedOn"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["UpdatedOn"];
          retObj._updatedMachineInfo = Convert.IsDBNull(dt.Rows[0]["UpdatedMachineInfo"]) ? null : (string)dt.Rows[0]["UpdatedMachineInfo"];
          retObj._isActive = Convert.IsDBNull(dt.Rows[0]["IsActive"]) ? (bool?)null : (bool?)dt.Rows[0]["IsActive"];
          retObj._occupation = Convert.IsDBNull(dt.Rows[0]["occupation"]) ? null : (string)dt.Rows[0]["occupation"];
          retObj._companyid = Convert.IsDBNull(dt.Rows[0]["CompanyId"]) ? (Int32?)null : (Int32?)dt.Rows[0]["CompanyId"];
          retObj._IsemployeeDirector = Convert.IsDBNull(dt.Rows[0]["IsemployeeDirector"]) ? (bool?)null : (bool?)dt.Rows[0]["IsemployeeDirector"];
          retObj._IsdirectorOnly = Convert.IsDBNull(dt.Rows[0]["IsdirectorOnly"]) ? (bool?)null : (bool?)dt.Rows[0]["IsdirectorOnly"];
          retObj._isLevyExempt = Convert.IsDBNull(dt.Rows[0]["IsLevyExempt"]) ? (bool?)null : (bool?)dt.Rows[0]["IsLevyExempt"];
          retObj._department = Convert.IsDBNull(dt.Rows[0]["Department"]) ? null : (string)dt.Rows[0]["Department"];
        }
        return retObj;
      }
      catch
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }

    ///<Summary>
    ///Delete one row by primary key(s)
    ///this method allows the object to delete itself from the table MasterEmployee based on its primary key
    ///</Summary>
    ///<returns>
    ///void
    ///</returns>
    ///<parameters>
    ///
    ///</parameters>
    public virtual void Delete()
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_DeleteOne]";
      command.CommandType = CommandType.StoredProcedure;
      command.Connection = _connectionProvider.Connection;
      command.Transaction = _connectionProvider.CurrentTransaction;

      try
      {
        command.Parameters.Add(new SqlParameter("@EmployeeID", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_employeeID ?? (object)DBNull.Value));

        command.ExecuteNonQuery();

      }
      catch
      {
        throw;
      }
      finally
      {
        command.Dispose();
      }
    }

    ///<Summary>
    ///Insert a new row
    ///This method saves a new object to the table MasterEmployee
    ///</Summary>
    ///<returns>
    ///void
    ///</returns>
    ///<parameters>
    ///
    ///</parameters>
    public virtual void Insert()
    {
            
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_InsertOne]";
      command.CommandType = CommandType.StoredProcedure;
      command.Connection = _connectionProvider.Connection;
      command.Transaction = _connectionProvider.CurrentTransaction;

      try
      {
        command.Parameters.Add(new SqlParameter("@EmployeeID", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _employeeID));
        command.Parameters.Add(new SqlParameter("@Empl_Code", SqlDbType.NVarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_emplCode ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Soc_Sec_Num", SqlDbType.NVarChar, 15, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_socSecNum ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@First_Name", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_firstName ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Middle_Name", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_middleName ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Last_Name", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_lastName ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Type_Code", SqlDbType.NVarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_typeCode ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@BirthDate", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_birthDate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Gender", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_gender ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Address1", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_address1 ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Address2", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_address2 ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@City", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_city ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@State", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_state ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Country", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_country ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Zip", SqlDbType.NVarChar, 10, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_zip ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Phone", SqlDbType.NVarChar, 20, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_phone ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Mobile", SqlDbType.NVarChar, 20, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_mobile ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Email", SqlDbType.NVarChar, 40, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_email ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@TIN", SqlDbType.NVarChar, 20, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_tin ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Appint_Date", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_appintDate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Last_Pay_Date", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_lastpaydate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Terminated", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_terminated ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@WagesPayDate", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_wagespayDate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Empl_Status", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_emplStatus ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Pay_Period", SqlDbType.NVarChar, 3, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_payPeriod ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@AllowAnces", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_allowAnces ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@State_Allow", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_stateAllow ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Marital_Stat", SqlDbType.NVarChar, 2, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_maritalStat ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Hold_Pymnt", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_holdPymnt ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Bank_Acct_No", SqlDbType.NVarChar, 17, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_bankAcctNo ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@State_udf", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_stateUdf ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@FlexDeptAcctType", SqlDbType.NVarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_flexDeptAcctType ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Last_Inc_Date", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_lastIncDate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@InsertedBy", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_insertedBy ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@InsertedOn", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertedOn ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@InsertedMachineInfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertedMachineInfo ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@UpdatedBy", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_updatedBy ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@UpdatedOn", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedOn ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@UpdatedMachineInfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedMachineInfo ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@IsActive", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_isActive ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@occupation", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_occupation ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@CompanyId", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_companyid ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@IsdirectorOnly", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_IsdirectorOnly ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@IsemployeeDirector", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_IsemployeeDirector ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@IsLevyExempt", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_isLevyExempt ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Department", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_department ?? (object)DBNull.Value));
        command.ExecuteNonQuery();

        _employeeID = Convert.IsDBNull(command.Parameters["@EmployeeID"].Value) ? (Int32?)null : (Int32?)command.Parameters["@EmployeeID"].Value;
        _emplCode = Convert.IsDBNull(command.Parameters["@Empl_Code"].Value) ? null : (string)command.Parameters["@Empl_Code"].Value;
        _socSecNum = Convert.IsDBNull(command.Parameters["@Soc_Sec_Num"].Value) ? null : (string)command.Parameters["@Soc_Sec_Num"].Value;
        _firstName = Convert.IsDBNull(command.Parameters["@First_Name"].Value) ? null : (string)command.Parameters["@First_Name"].Value;
        _middleName = Convert.IsDBNull(command.Parameters["@Middle_Name"].Value) ? null : (string)command.Parameters["@Middle_Name"].Value;
        _lastName = Convert.IsDBNull(command.Parameters["@Last_Name"].Value) ? null : (string)command.Parameters["@Last_Name"].Value;
        _typeCode = Convert.IsDBNull(command.Parameters["@Type_Code"].Value) ? null : (string)command.Parameters["@Type_Code"].Value;
        _birthDate = Convert.IsDBNull(command.Parameters["@BirthDate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@BirthDate"].Value;
        _gender = Convert.IsDBNull(command.Parameters["@Gender"].Value) ? null : (string)command.Parameters["@Gender"].Value;
        _address1 = Convert.IsDBNull(command.Parameters["@Address1"].Value) ? null : (string)command.Parameters["@Address1"].Value;
        _address2 = Convert.IsDBNull(command.Parameters["@Address2"].Value) ? null : (string)command.Parameters["@Address2"].Value;
        _city = Convert.IsDBNull(command.Parameters["@City"].Value) ? null : (string)command.Parameters["@City"].Value;
        _state = Convert.IsDBNull(command.Parameters["@State"].Value) ? null : (string)command.Parameters["@State"].Value;
        _country = Convert.IsDBNull(command.Parameters["@Country"].Value) ? null : (string)command.Parameters["@Country"].Value;
        _zip = Convert.IsDBNull(command.Parameters["@Zip"].Value) ? null : (string)command.Parameters["@Zip"].Value;
        _phone = Convert.IsDBNull(command.Parameters["@Phone"].Value) ? null : (string)command.Parameters["@Phone"].Value;
        _mobile = Convert.IsDBNull(command.Parameters["@Mobile"].Value) ? null : (string)command.Parameters["@Mobile"].Value;
        _email = Convert.IsDBNull(command.Parameters["@Email"].Value) ? null : (string)command.Parameters["@Email"].Value;
        _tin = Convert.IsDBNull(command.Parameters["@TIN"].Value) ? null : (string)command.Parameters["@TIN"].Value;
        _appintDate = Convert.IsDBNull(command.Parameters["@Appint_Date"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@Appint_Date"].Value;
        _lastpaydate = Convert.IsDBNull(command.Parameters["@Last_Pay_Date"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@Last_Pay_Date"].Value;
        _terminated = Convert.IsDBNull(command.Parameters["@Terminated"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@Terminated"].Value;
        _wagespayDate = Convert.IsDBNull(command.Parameters["@WagesPayDate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@WagesPayDate"].Value;
        _emplStatus = Convert.IsDBNull(command.Parameters["@Empl_Status"].Value) ? null : (string)command.Parameters["@Empl_Status"].Value;
        _payPeriod = Convert.IsDBNull(command.Parameters["@Pay_Period"].Value) ? null : (string)command.Parameters["@Pay_Period"].Value;
        _allowAnces = Convert.IsDBNull(command.Parameters["@AllowAnces"].Value) ? (Int32?)null : (Int32?)command.Parameters["@AllowAnces"].Value;
        _stateAllow = Convert.IsDBNull(command.Parameters["@State_Allow"].Value) ? (Int32?)null : (Int32?)command.Parameters["@State_Allow"].Value;
        _maritalStat = Convert.IsDBNull(command.Parameters["@Marital_Stat"].Value) ? null : (string)command.Parameters["@Marital_Stat"].Value;
        _holdPymnt = Convert.IsDBNull(command.Parameters["@Hold_Pymnt"].Value) ? null : (string)command.Parameters["@Hold_Pymnt"].Value;
        _bankAcctNo = Convert.IsDBNull(command.Parameters["@Bank_Acct_No"].Value) ? null : (string)command.Parameters["@Bank_Acct_No"].Value;
        _stateUdf = Convert.IsDBNull(command.Parameters["@State_udf"].Value) ? (decimal?)null : (decimal?)command.Parameters["@State_udf"].Value;
        _flexDeptAcctType = Convert.IsDBNull(command.Parameters["@FlexDeptAcctType"].Value) ? null : (string)command.Parameters["@FlexDeptAcctType"].Value;
        _lastIncDate = Convert.IsDBNull(command.Parameters["@Last_Inc_Date"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@Last_Inc_Date"].Value;
        _insertedBy = Convert.IsDBNull(command.Parameters["@InsertedBy"].Value) ? (Int32?)null : (Int32?)command.Parameters["@InsertedBy"].Value;
        _insertedOn = Convert.IsDBNull(command.Parameters["@InsertedOn"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@InsertedOn"].Value;
        _insertedMachineInfo = Convert.IsDBNull(command.Parameters["@InsertedMachineInfo"].Value) ? null : (string)command.Parameters["@InsertedMachineInfo"].Value;
        _updatedBy = Convert.IsDBNull(command.Parameters["@UpdatedBy"].Value) ? (Int32?)null : (Int32?)command.Parameters["@UpdatedBy"].Value;
        _updatedOn = Convert.IsDBNull(command.Parameters["@UpdatedOn"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@UpdatedOn"].Value;
        _updatedMachineInfo = Convert.IsDBNull(command.Parameters["@UpdatedMachineInfo"].Value) ? null : (string)command.Parameters["@UpdatedMachineInfo"].Value;
        _isActive = Convert.IsDBNull(command.Parameters["@IsActive"].Value) ? (bool?)null : (bool?)command.Parameters["@IsActive"].Value;
        _occupation = Convert.IsDBNull(command.Parameters["@occupation"].Value) ? null : (string)command.Parameters["@occupation"].Value;
        _companyid = Convert.IsDBNull(command.Parameters["@CompanyId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@CompanyId"].Value;
        _IsdirectorOnly = Convert.IsDBNull(command.Parameters["@IsdirectorOnly"].Value) ? (bool?)null : (bool?)command.Parameters["@IsdirectorOnly"].Value;
        _IsemployeeDirector = Convert.IsDBNull(command.Parameters["@IsemployeeDirector"].Value) ? (bool?)null : (bool?)command.Parameters["@IsemployeeDirector"].Value;
        _isLevyExempt = Convert.IsDBNull(command.Parameters["@IsLevyExempt"].Value) ? (bool?)null : (bool?)command.Parameters["@IsLevyExempt"].Value;
        _department = Convert.IsDBNull(command.Parameters["@Department"].Value) ? null : (string)command.Parameters["@Department"].Value;
      }
      catch
      {
        throw;
      }
      finally
      {
        command.Dispose();
      }
    }

    ///<Summary>
    ///Select all rows
    ///This method returns all data rows in the table MasterEmployee
    ///</Summary>
    ///<returns>
    ///IList-DLMasterEmployee.
    ///</returns>
    ///<parameters>
    ///
    ///</parameters>
    public static IList<DLMasterEmployee> SelectAll()
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_SelectAll]";
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;

      DataTable dt = new DataTable("MasterEmployee");
      SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
      try
      {
        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        sqlAdapter.Fill(dt);
        List<DLMasterEmployee> objList = new List<DLMasterEmployee>();
        if (dt.Rows.Count > 0)
        {
          foreach (DataRow row in dt.Rows) //IsLevyExempt
          {
            DLMasterEmployee retObj = new DLMasterEmployee();
            retObj._employeeID = Convert.IsDBNull(row["EmployeeID"]) ? (Int32?)null : (Int32?)row["EmployeeID"];
            retObj._emplCode = Convert.IsDBNull(row["Empl_Code"]) ? null : (string)row["Empl_Code"];
            retObj._socSecNum = Convert.IsDBNull(row["Soc_Sec_Num"]) ? null : (string)row["Soc_Sec_Num"];
            retObj._firstName = Convert.IsDBNull(row["First_Name"]) ? null : (string)row["First_Name"];
            retObj._middleName = Convert.IsDBNull(row["Middle_Name"]) ? null : (string)row["Middle_Name"];
            retObj._lastName = Convert.IsDBNull(row["Last_Name"]) ? null : (string)row["Last_Name"];
            retObj._typeCode = Convert.IsDBNull(row["Type_Code"]) ? null : (string)row["Type_Code"];
            retObj._birthDate = Convert.IsDBNull(row["BirthDate"]) ? (DateTime?)null : (DateTime?)row["BirthDate"];
            retObj._gender = Convert.IsDBNull(row["Gender"]) ? null : (string)row["Gender"];
            retObj._address1 = Convert.IsDBNull(row["Address1"]) ? null : (string)row["Address1"];
            retObj._address2 = Convert.IsDBNull(row["Address2"]) ? null : (string)row["Address2"];
            retObj._city = Convert.IsDBNull(row["City"]) ? null : (string)row["City"];
            retObj._state = Convert.IsDBNull(row["State"]) ? null : (string)row["State"];
            retObj._country = Convert.IsDBNull(row["Country"]) ? null : (string)row["Country"];
            retObj._zip = Convert.IsDBNull(row["Zip"]) ? null : (string)row["Zip"];
            retObj._phone = Convert.IsDBNull(row["Phone"]) ? null : (string)row["Phone"];
            retObj._mobile = Convert.IsDBNull(row["Mobile"]) ? null : (string)row["Mobile"];
            retObj._email = Convert.IsDBNull(row["Email"]) ? null : (string)row["Email"];
            retObj._tin = Convert.IsDBNull(row["TIN"]) ? null : (string)row["TIN"];
            retObj._appintDate = Convert.IsDBNull(row["Appint_Date"]) ? (DateTime?)null : (DateTime?)row["Appint_Date"];
            retObj._lastpaydate = Convert.IsDBNull(row["Last_Pay_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Pay_Date"];
            retObj._terminated = Convert.IsDBNull(row["Terminated"]) ? (DateTime?)null : (DateTime?)row["Terminated"];
            retObj._wagespayDate = Convert.IsDBNull(row["Wages_Pay_Date"]) ? (DateTime?)null : (DateTime?)row["Wages_Pay_Date"];
            retObj._emplStatus = Convert.IsDBNull(row["Empl_Status"]) ? null : (string)row["Empl_Status"];
            retObj._payPeriod = Convert.IsDBNull(row["Pay_Period"]) ? null : (string)row["Pay_Period"];
            retObj._allowAnces = Convert.IsDBNull(row["AllowAnces"]) ? (Int32?)null : (Int32?)row["AllowAnces"];
            retObj._stateAllow = Convert.IsDBNull(row["State_Allow"]) ? (Int32?)null : (Int32?)row["State_Allow"];
            retObj._maritalStat = Convert.IsDBNull(row["Marital_Stat"]) ? null : (string)row["Marital_Stat"];
            retObj._holdPymnt = Convert.IsDBNull(row["Hold_Pymnt"]) ? null : (string)row["Hold_Pymnt"];
            retObj._bankAcctNo = Convert.IsDBNull(row["Bank_Acct_No"]) ? null : (string)row["Bank_Acct_No"];
            retObj._stateUdf = Convert.IsDBNull(row["State_udf"]) ? (decimal?)null : (decimal?)row["State_udf"];
            retObj._flexDeptAcctType = Convert.IsDBNull(row["FlexDeptAcctType"]) ? null : (string)row["FlexDeptAcctType"];
            retObj._lastIncDate = Convert.IsDBNull(row["Last_Inc_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Inc_Date"];
            retObj._insertedBy = Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"];
            retObj._insertedOn = Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"];
            retObj._insertedMachineInfo = Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"];
            retObj._updatedBy = Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"];
            retObj._updatedOn = Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"];
            retObj._updatedMachineInfo = Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"];
            retObj._isActive = Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"];
            retObj._occupation = Convert.IsDBNull(row["occupation"]) ? null : (string)row["occupation"];
            retObj._companyid = Convert.IsDBNull(row["CompanyId"]) ? (Int32?)null : (Int32?)row["CompanyId"];
            retObj._IsemployeeDirector = Convert.IsDBNull(row["IsemployeeDirector"]) ? (bool?)null : (bool?)row["IsemployeeDirector"];
            retObj._IsdirectorOnly = Convert.IsDBNull(row["IsdirectorOnly"]) ? (bool?)null : (bool?)row["IsdirectorOnly"];
            retObj._isLevyExempt = Convert.IsDBNull(row["IsLevyExempt"]) ? (bool?)null : (bool?)row["IsLevyExempt"];
            retObj._department = Convert.IsDBNull(row["Department"]) ? null : (string)row["Department"];
            objList.Add(retObj);
          }
        }
        return objList;
      }
      catch
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }

    ///<Summary>
    ///Select all rows
    ///This method returns all data rows in the table MasterEmployee
    ///</Summary>
    ///<returns>
    ///IList-DLMasterEmployee.
    ///</returns>
    ///<parameters>
    ///
    ///</parameters>
    public static IList<DLMasterEmployee> SelectAll_grid(int id)
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_SelectAll_grid]";
      command.Parameters.Add(new SqlParameter("@CompanyId", SqlDbType.Int, 18, ParameterDirection.Input, false, 18, 0, "", DataRowVersion.Proposed, (object)id ?? (object)DBNull.Value));
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;

      DataTable dt = new DataTable("MasterEmployee");
      SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
      try
      {
        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        sqlAdapter.Fill(dt);
        List<DLMasterEmployee> objList = new List<DLMasterEmployee>();
        if (dt.Rows.Count > 0)
        {
          int count = 0;
          foreach (DataRow row in dt.Rows)
          {
            DLMasterEmployee retObj = new DLMasterEmployee();
            retObj._employeeID = Convert.IsDBNull(row["EmployeeID"]) ? (Int32?)null : (Int32?)row["EmployeeID"];
            retObj._emplCode = Convert.IsDBNull(row["Empl_Code"]) ? null : (string)row["Empl_Code"];
            retObj._socSecNum = Convert.IsDBNull(row["Soc_Sec_Num"]) ? null : (string)row["Soc_Sec_Num"];
            retObj._firstName = Convert.IsDBNull(row["First_Name"]) ? null : (string)row["First_Name"];
            retObj._middleName = Convert.IsDBNull(row["Middle_Name"]) ? null : (string)row["Middle_Name"];
            retObj._lastName = Convert.IsDBNull(row["Last_Name"]) ? null : (string)row["Last_Name"];
            retObj._typeCode = Convert.IsDBNull(row["Type_Code"]) ? null : (string)row["Type_Code"];
            retObj._birthDate = Convert.IsDBNull(row["BirthDate"]) ? (DateTime?)null : (DateTime?)row["BirthDate"];
            retObj._gender = Convert.IsDBNull(row["Gender"]) ? null : (string)row["Gender"];
            retObj._address1 = Convert.IsDBNull(row["Address1"]) ? null : (string)row["Address1"];
            retObj._address2 = Convert.IsDBNull(row["Address2"]) ? null : (string)row["Address2"];
            retObj._city = Convert.IsDBNull(row["City"]) ? null : (string)row["City"];
            retObj._state = Convert.IsDBNull(row["State"]) ? null : (string)row["State"];
            retObj._country = Convert.IsDBNull(row["Country"]) ? null : (string)row["Country"];
            retObj._zip = Convert.IsDBNull(row["Zip"]) ? null : (string)row["Zip"];
            retObj._phone = Convert.IsDBNull(row["Phone"]) ? null : (string)row["Phone"];
            retObj._mobile = Convert.IsDBNull(row["Mobile"]) ? null : (string)row["Mobile"];
            retObj._email = Convert.IsDBNull(row["Email"]) ? null : (string)row["Email"];
            retObj._tin = Convert.IsDBNull(row["TIN"]) ? null : (string)row["TIN"];
            retObj._appintDate = Convert.IsDBNull(row["Appint_Date"]) ? (DateTime?)null : (DateTime?)row["Appint_Date"];
            retObj._lastpaydate = Convert.IsDBNull(row["Last_Pay_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Pay_Date"];
            retObj._terminated = Convert.IsDBNull(row["Terminated"]) ? (DateTime?)null : (DateTime?)row["Terminated"];
            retObj._wagespayDate = Convert.IsDBNull(row["Wages_Pay_Date"]) ? (DateTime?)null : (DateTime?)row["Wages_Pay_Date"];
            retObj._ApDate = Convert.IsDBNull(row["Appint_Date"]) ? null : ((DateTime)row["Appint_Date"]).ToString("dd-MM-yyyy");
            retObj._TrDate = Convert.IsDBNull(row["Terminated"]) ? null : ((DateTime)row["Terminated"]).ToString("dd-MM-yyyy");
            retObj._emplStatus = Convert.IsDBNull(row["Empl_Status"]) ? null : (string)row["Empl_Status"];
            retObj._payPeriod = Convert.IsDBNull(row["Pay_Period"]) ? null : (string)row["Pay_Period"];
           
            if (retObj._payPeriod != null)
            {
              if (retObj._payPeriod == "W")
                retObj._payPeriodforlist = "W - Weekly";
              if (retObj._payPeriod == "M")
                retObj._payPeriodforlist = "M - Monthly";
              if (retObj._payPeriod == "E2W")
                retObj._payPeriodforlist = "E2W - Every Two Weeks"; // retObj._payPeriodforlist = "Every Two Weeks"; Old Code             
              if (retObj._payPeriod == "2M")
                retObj._payPeriodforlist = "2M - Twice Monthly"; //retObj._payPeriodforlist = "Twice Monthly";
            }


            retObj._allowAnces = Convert.IsDBNull(row["AllowAnces"]) ? (Int32?)null : (Int32?)row["AllowAnces"];
            retObj._stateAllow = Convert.IsDBNull(row["State_Allow"]) ? (Int32?)null : (Int32?)row["State_Allow"];
            retObj._maritalStat = Convert.IsDBNull(row["Marital_Stat"]) ? null : (string)row["Marital_Stat"];
            retObj._holdPymnt = Convert.IsDBNull(row["Hold_Pymnt"]) ? null : (string)row["Hold_Pymnt"];
            retObj._bankAcctNo = Convert.IsDBNull(row["Bank_Acct_No"]) ? null : (string)row["Bank_Acct_No"];
            retObj._stateUdf = Convert.IsDBNull(row["State_udf"]) ? (decimal?)null : (decimal?)row["State_udf"];
            retObj._flexDeptAcctType = Convert.IsDBNull(row["FlexDeptAcctType"]) ? null : (string)row["FlexDeptAcctType"];
            retObj._lastIncDate = Convert.IsDBNull(row["Last_Inc_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Inc_Date"];
            retObj._insertedBy = Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"];
            retObj._insertedOn = Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"];
            retObj._insertedMachineInfo = Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"];
            retObj._updatedBy = Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"];
            retObj._updatedOn = Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"];
            retObj._updatedMachineInfo = Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"];
            retObj._isActive = Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"];
            retObj._occupation = Convert.IsDBNull(row["occupation"]) ? null : (string)row["occupation"];
            retObj._companyid = Convert.IsDBNull(row["CompanyId"]) ? (Int32?)null : (Int32?)row["CompanyId"];
            retObj._wadeg = Convert.IsDBNull(row["Wadeg"]) ? (decimal?)null : decimal.Parse(String.Format("{0:0.00}", (decimal?)row["Wadeg"]));
            retObj._wage_Amt = Convert.IsDBNull(row["WageAmt"]) ? (decimal?)null : decimal.Parse(String.Format("{0:0.00}", (decimal?)row["WageAmt"]));
            retObj._IsemployeeDirector = Convert.IsDBNull(row["IsemployeeDirector"]) ? (bool?)null : (bool?)row["IsemployeeDirector"];
            retObj._IsdirectorOnly = Convert.IsDBNull(row["IsdirectorOnly"]) ? (bool?)null : (bool?)row["IsdirectorOnly"];
            retObj._isLevyExempt = Convert.IsDBNull(row["IsLevyExempt"]) ? (bool?)null : (bool?)row["IsLevyExempt"];
            retObj._IsdirectorOnly = Convert.IsDBNull(row["IsdirectorOnly"]) ? (bool?)null : (bool?)row["IsdirectorOnly"];
            retObj._IsempDirector = (bool)retObj._IsemployeeDirector ? "Visible" : "Hidden";
            retObj._IsempDirectorimg = (bool)retObj._IsemployeeDirector ? "/img/RightSine.png" : "/img/close.png";
            retObj._emptype = (bool)retObj._IsemployeeDirector ? "Employee Directors" : "Employees";
            retObj._department = Convert.IsDBNull(row["Department"]) ? null : (string)row["Department"];
            retObj._emp_S_no = count + 1;
            count++;
            objList.Add(retObj);
          }
        }
        return objList;
      }
      catch
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }
    public static IList<DLMasterEmployee> SelectAllNWDirector_grid(int id)
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_SelectAllNWDirector_grid]";
      command.Parameters.Add(new SqlParameter("@CompanyId", SqlDbType.Int, 18, ParameterDirection.Input, false, 18, 0, "", DataRowVersion.Proposed, (object)id ?? (object)DBNull.Value));
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;

      DataTable dt = new DataTable("MasterEmployee");
      SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
      try
      {
        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        sqlAdapter.Fill(dt);
        List<DLMasterEmployee> objList = new List<DLMasterEmployee>();
        if (dt.Rows.Count > 0)
        {
          foreach (DataRow row in dt.Rows)
          {
            DLMasterEmployee retObj = new DLMasterEmployee();
            retObj._employeeID = Convert.IsDBNull(row["EmployeeID"]) ? (Int32?)null : (Int32?)row["EmployeeID"];
            retObj._emplCode = Convert.IsDBNull(row["Empl_Code"]) ? null : (string)row["Empl_Code"];
            retObj._socSecNum = Convert.IsDBNull(row["Soc_Sec_Num"]) ? null : (string)row["Soc_Sec_Num"];
            retObj._firstName = Convert.IsDBNull(row["First_Name"]) ? null : (string)row["First_Name"];
            retObj._middleName = Convert.IsDBNull(row["Middle_Name"]) ? null : (string)row["Middle_Name"];
            retObj._lastName = Convert.IsDBNull(row["Last_Name"]) ? null : (string)row["Last_Name"];
            retObj._typeCode = Convert.IsDBNull(row["Type_Code"]) ? null : (string)row["Type_Code"];
            retObj._birthDate = Convert.IsDBNull(row["BirthDate"]) ? (DateTime?)null : (DateTime?)row["BirthDate"];
            retObj._gender = Convert.IsDBNull(row["Gender"]) ? null : (string)row["Gender"];
            retObj._address1 = Convert.IsDBNull(row["Address1"]) ? null : (string)row["Address1"];
            retObj._address2 = Convert.IsDBNull(row["Address2"]) ? null : (string)row["Address2"];
            retObj._city = Convert.IsDBNull(row["City"]) ? null : (string)row["City"];
            retObj._state = Convert.IsDBNull(row["State"]) ? null : (string)row["State"];
            retObj._country = Convert.IsDBNull(row["Country"]) ? null : (string)row["Country"];
            retObj._zip = Convert.IsDBNull(row["Zip"]) ? null : (string)row["Zip"];
            retObj._phone = Convert.IsDBNull(row["Phone"]) ? null : (string)row["Phone"];
            retObj._mobile = Convert.IsDBNull(row["Mobile"]) ? null : (string)row["Mobile"];
            retObj._email = Convert.IsDBNull(row["Email"]) ? null : (string)row["Email"];
            retObj._tin = Convert.IsDBNull(row["TIN"]) ? null : (string)row["TIN"];
            retObj._appintDate = Convert.IsDBNull(row["Appint_Date"]) ? (DateTime?)null : (DateTime?)row["Appint_Date"];
            retObj._lastpaydate = Convert.IsDBNull(row["Last_Pay_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Pay_Date"];
            retObj._terminated = Convert.IsDBNull(row["Terminated"]) ? (DateTime?)null : (DateTime?)row["Terminated"];
            retObj._ApDate = Convert.IsDBNull(row["Appint_Date"]) ? null : ((DateTime)row["Appint_Date"]).ToString("dd-MM-yyyy");
            retObj._TrDate = Convert.IsDBNull(row["Terminated"]) ? null : ((DateTime)row["Terminated"]).ToString("dd-MM-yyyy");
            retObj._emplStatus = Convert.IsDBNull(row["Empl_Status"]) ? null : (string)row["Empl_Status"];
            retObj._payPeriod = Convert.IsDBNull(row["Pay_Period"]) ? null : (string)row["Pay_Period"];
            retObj._allowAnces = Convert.IsDBNull(row["AllowAnces"]) ? (Int32?)null : (Int32?)row["AllowAnces"];
            retObj._stateAllow = Convert.IsDBNull(row["State_Allow"]) ? (Int32?)null : (Int32?)row["State_Allow"];
            retObj._maritalStat = Convert.IsDBNull(row["Marital_Stat"]) ? null : (string)row["Marital_Stat"];
            retObj._holdPymnt = Convert.IsDBNull(row["Hold_Pymnt"]) ? null : (string)row["Hold_Pymnt"];
            retObj._bankAcctNo = Convert.IsDBNull(row["Bank_Acct_No"]) ? null : (string)row["Bank_Acct_No"];
            retObj._stateUdf = Convert.IsDBNull(row["State_udf"]) ? (decimal?)null : (decimal?)row["State_udf"];
            retObj._flexDeptAcctType = Convert.IsDBNull(row["FlexDeptAcctType"]) ? null : (string)row["FlexDeptAcctType"];
            retObj._lastIncDate = Convert.IsDBNull(row["Last_Inc_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Inc_Date"];
            retObj._insertedBy = Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"];
            retObj._insertedOn = Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"];
            retObj._insertedMachineInfo = Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"];
            retObj._updatedBy = Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"];
            retObj._updatedOn = Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"];
            retObj._updatedMachineInfo = Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"];
            retObj._isActive = Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"];
            retObj._occupation = Convert.IsDBNull(row["occupation"]) ? null : (string)row["occupation"];
            retObj._companyid = Convert.IsDBNull(row["CompanyId"]) ? (Int32?)null : (Int32?)row["CompanyId"];
            retObj._wadeg = Convert.IsDBNull(row["Wadeg"]) ? (decimal?)null : decimal.Parse(String.Format("{0:0.00}", (decimal?)row["Wadeg"]));
            retObj._IsemployeeDirector = Convert.IsDBNull(row["IsemployeeDirector"]) ? (bool?)null : (bool?)row["IsemployeeDirector"];
            retObj._IsdirectorOnly = Convert.IsDBNull(row["IsdirectorOnly"]) ? (bool?)null : (bool?)row["IsdirectorOnly"];
            retObj._department = Convert.IsDBNull(row["department"]) ? null : (string)row["department"];
            //retObj._isLevyExempt = Convert.IsDBNull(row["IsLevyExempt"]) ? (bool?)null : (bool?)row["IsLevyExempt"];
            objList.Add(retObj);
          }
        }
        return objList;
      }
      catch
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }
    public static IList<DLMasterEmployee> SelectEmplyeeDetails_grid(int ssn)
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_EmplyeeDetails_grid]";
      command.Parameters.Add(new SqlParameter("@Soc_Sec_Num", SqlDbType.Int, 18, ParameterDirection.Input, false, 18, 0, "", DataRowVersion.Proposed, (object)ssn ?? (object)DBNull.Value));
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;

      DataTable dt = new DataTable("MasterEmployee");
      SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
      try
      {
        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        sqlAdapter.Fill(dt);
        List<DLMasterEmployee> objList = new List<DLMasterEmployee>();
        if (dt.Rows.Count > 0)
        {
          foreach (DataRow row in dt.Rows)
          {
            DLMasterEmployee retObj = new DLMasterEmployee();
            retObj._employeeID = Convert.IsDBNull(row["EmployeeID"]) ? (Int32?)null : (Int32?)row["EmployeeID"];
            retObj._emplCode = Convert.IsDBNull(row["Empl_Code"]) ? null : (string)row["Empl_Code"];
            retObj._socSecNum = Convert.IsDBNull(row["Soc_Sec_Num"]) ? null : (string)row["Soc_Sec_Num"];
            retObj._firstName = Convert.IsDBNull(row["First_Name"]) ? null : (string)row["First_Name"];
            retObj._middleName = Convert.IsDBNull(row["Middle_Name"]) ? null : (string)row["Middle_Name"];
            retObj._lastName = Convert.IsDBNull(row["Last_Name"]) ? null : (string)row["Last_Name"];
            retObj._typeCode = Convert.IsDBNull(row["Type_Code"]) ? null : (string)row["Type_Code"];
            retObj._birthDate = Convert.IsDBNull(row["BirthDate"]) ? (DateTime?)null : (DateTime?)row["BirthDate"];
            retObj._gender = Convert.IsDBNull(row["Gender"]) ? null : (string)row["Gender"];
            retObj._address1 = Convert.IsDBNull(row["Address1"]) ? null : (string)row["Address1"];
            retObj._address2 = Convert.IsDBNull(row["Address2"]) ? null : (string)row["Address2"];
            retObj._city = Convert.IsDBNull(row["City"]) ? null : (string)row["City"];
            retObj._state = Convert.IsDBNull(row["State"]) ? null : (string)row["State"];
            retObj._country = Convert.IsDBNull(row["Country"]) ? null : (string)row["Country"];
            retObj._zip = Convert.IsDBNull(row["Zip"]) ? null : (string)row["Zip"];
            retObj._phone = Convert.IsDBNull(row["Phone"]) ? null : (string)row["Phone"];
            retObj._mobile = Convert.IsDBNull(row["Mobile"]) ? null : (string)row["Mobile"];
            retObj._email = Convert.IsDBNull(row["Email"]) ? null : (string)row["Email"];
            retObj._tin = Convert.IsDBNull(row["TIN"]) ? null : (string)row["TIN"];
            retObj._appintDate = Convert.IsDBNull(row["Appint_Date"]) ? (DateTime?)null : (DateTime?)row["Appint_Date"];
            retObj._terminated = Convert.IsDBNull(row["Terminated"]) ? (DateTime?)null : (DateTime?)row["Terminated"];
            retObj._wagespayDate = Convert.IsDBNull(row["Wages_Pay_Date"]) ? (DateTime?)null : (DateTime?)row["Wages_Pay_Date"];
            retObj._emplStatus = Convert.IsDBNull(row["Empl_Status"]) ? null : (string)row["Empl_Status"];
            retObj._payPeriod = Convert.IsDBNull(row["Pay_Period"]) ? null : (string)row["Pay_Period"];
            retObj._allowAnces = Convert.IsDBNull(row["AllowAnces"]) ? (Int32?)null : (Int32?)row["AllowAnces"];
            retObj._stateAllow = Convert.IsDBNull(row["State_Allow"]) ? (Int32?)null : (Int32?)row["State_Allow"];
            retObj._maritalStat = Convert.IsDBNull(row["Marital_Stat"]) ? null : (string)row["Marital_Stat"];
            retObj._holdPymnt = Convert.IsDBNull(row["Hold_Pymnt"]) ? null : (string)row["Hold_Pymnt"];
            retObj._bankAcctNo = Convert.IsDBNull(row["Bank_Acct_No"]) ? null : (string)row["Bank_Acct_No"];
            retObj._stateUdf = Convert.IsDBNull(row["State_udf"]) ? (decimal?)null : (decimal?)row["State_udf"];
            retObj._flexDeptAcctType = Convert.IsDBNull(row["FlexDeptAcctType"]) ? null : (string)row["FlexDeptAcctType"];
            retObj._lastIncDate = Convert.IsDBNull(row["Last_Inc_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Inc_Date"];
            retObj._insertedBy = Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"];
            retObj._insertedOn = Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"];
            retObj._insertedMachineInfo = Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"];
            retObj._updatedBy = Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"];
            retObj._updatedOn = Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"];
            retObj._updatedMachineInfo = Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"];
            retObj._isActive = Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"];
            retObj._occupation = Convert.IsDBNull(row["occupation"]) ? null : (string)row["occupation"];
            retObj._companyid = Convert.IsDBNull(row["CompanyId"]) ? (Int32?)null : (Int32?)row["CompanyId"];
            retObj._IsemployeeDirector = Convert.IsDBNull(row["IsemployeeDirector"]) ? (bool?)null : (bool?)row["IsemployeeDirector"];
            retObj._IsdirectorOnly = Convert.IsDBNull(row["IsdirectorOnly"]) ? (bool?)null : (bool?)row["IsdirectorOnly"];
            retObj._department = Convert.IsDBNull(row["Department"]) ? null : (string)row["Department"];
            // retObj._isLevyExempt = Convert.IsDBNull(row["IsLevyExempt"]) ? (bool?)null : (bool?)row["IsLevyExempt"];
            objList.Add(retObj);
          }
        }
        return objList;
      }
      catch (Exception ex)
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }
    ///<Summary>
    ///</Summary>
    ///<returns>
    ///Int32
    ///</returns>
    ///<parameters>
    ///
    ///</parameters>
    public static Int32 SelectAllCount()
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_SelectAllCount]";
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;
      try
      {
        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        Int32 retCount = (Int32)command.ExecuteScalar();
        return retCount;
      }
      catch
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }

    ///<Summary>
    ///Select specific fields of all rows using criteriaquery api
    ///This method returns specific fields of all data rows in the table using criteriaquery apiMasterEmployee
    ///</Summary>
    ///<returns>
    ///IDictionary-string, IList-object..
    ///</returns>
    ///<parameters>
    ///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
    ///</parameters>
    public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_SelectAllByCriteriaProjection]";
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;

      DataTable dt = new DataTable("MasterEmployee");
      SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
      try
      {
        string fieldsField = GetProjections(listProjection);
        string whereClause = GetSelectionCriteria(listCriterion);
        string orderClause = GetSelectionOrder(listOrder);
        string skipClause = GetSelectionSkip(dataSkip);
        string takeClause = GetSelectionTake(dataTake);

        if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
          throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

        command.Parameters.Add(new SqlParameter("@FieldsField", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)fieldsField ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause ?? (object)DBNull.Value));

        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        sqlAdapter.Fill(dt);

        IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
        foreach (IDataProjection projection in listProjection)
        {
          IList<object> lst = new List<object>();
          dict.Add(projection.Member, lst);
          foreach (DataRow row in dt.Rows)
          {
            if (string.Compare(projection.Member, "EmployeeID", true) == 0) lst.Add(Convert.IsDBNull(row["EmployeeID"]) ? (Int32?)null : (Int32?)row["EmployeeID"]);
            if (string.Compare(projection.Member, "Empl_Code", true) == 0) lst.Add(Convert.IsDBNull(row["Empl_Code"]) ? null : (string)row["Empl_Code"]);
            if (string.Compare(projection.Member, "Soc_Sec_Num", true) == 0) lst.Add(Convert.IsDBNull(row["Soc_Sec_Num"]) ? null : (string)row["Soc_Sec_Num"]);
            if (string.Compare(projection.Member, "First_Name", true) == 0) lst.Add(Convert.IsDBNull(row["First_Name"]) ? null : (string)row["First_Name"]);
            if (string.Compare(projection.Member, "Middle_Name", true) == 0) lst.Add(Convert.IsDBNull(row["Middle_Name"]) ? null : (string)row["Middle_Name"]);
            if (string.Compare(projection.Member, "Last_Name", true) == 0) lst.Add(Convert.IsDBNull(row["Last_Name"]) ? null : (string)row["Last_Name"]);
            if (string.Compare(projection.Member, "Type_Code", true) == 0) lst.Add(Convert.IsDBNull(row["Type_Code"]) ? null : (string)row["Type_Code"]);
            if (string.Compare(projection.Member, "BirthDate", true) == 0) lst.Add(Convert.IsDBNull(row["BirthDate"]) ? (DateTime?)null : (DateTime?)row["BirthDate"]);
            if (string.Compare(projection.Member, "Gender", true) == 0) lst.Add(Convert.IsDBNull(row["Gender"]) ? null : (string)row["Gender"]);
            if (string.Compare(projection.Member, "Address1", true) == 0) lst.Add(Convert.IsDBNull(row["Address1"]) ? null : (string)row["Address1"]);
            if (string.Compare(projection.Member, "Address2", true) == 0) lst.Add(Convert.IsDBNull(row["Address2"]) ? null : (string)row["Address2"]);
            if (string.Compare(projection.Member, "City", true) == 0) lst.Add(Convert.IsDBNull(row["City"]) ? null : (string)row["City"]);
            if (string.Compare(projection.Member, "State", true) == 0) lst.Add(Convert.IsDBNull(row["State"]) ? null : (string)row["State"]);
            if (string.Compare(projection.Member, "Country", true) == 0) lst.Add(Convert.IsDBNull(row["Country"]) ? null : (string)row["Country"]);
            if (string.Compare(projection.Member, "Zip", true) == 0) lst.Add(Convert.IsDBNull(row["Zip"]) ? null : (string)row["Zip"]);
            if (string.Compare(projection.Member, "Phone", true) == 0) lst.Add(Convert.IsDBNull(row["Phone"]) ? null : (string)row["Phone"]);
            if (string.Compare(projection.Member, "Mobile", true) == 0) lst.Add(Convert.IsDBNull(row["Mobile"]) ? null : (string)row["Mobile"]);
            if (string.Compare(projection.Member, "Email", true) == 0) lst.Add(Convert.IsDBNull(row["Email"]) ? null : (string)row["Email"]);
            if (string.Compare(projection.Member, "TIN", true) == 0) lst.Add(Convert.IsDBNull(row["TIN"]) ? null : (string)row["TIN"]);
            if (string.Compare(projection.Member, "Appint_Date", true) == 0) lst.Add(Convert.IsDBNull(row["Appint_Date"]) ? (DateTime?)null : (DateTime?)row["Appint_Date"]);
            if (string.Compare(projection.Member, "Terminated", true) == 0) lst.Add(Convert.IsDBNull(row["Terminated"]) ? (DateTime?)null : (DateTime?)row["Terminated"]);
            if (string.Compare(projection.Member, "Empl_Status", true) == 0) lst.Add(Convert.IsDBNull(row["Empl_Status"]) ? null : (string)row["Empl_Status"]);
            if (string.Compare(projection.Member, "Pay_Period", true) == 0) lst.Add(Convert.IsDBNull(row["Pay_Period"]) ? null : (string)row["Pay_Period"]);
            if (string.Compare(projection.Member, "AllowAnces", true) == 0) lst.Add(Convert.IsDBNull(row["AllowAnces"]) ? (Int32?)null : (Int32?)row["AllowAnces"]);
            if (string.Compare(projection.Member, "State_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["State_Allow"]) ? (Int32?)null : (Int32?)row["State_Allow"]);
            if (string.Compare(projection.Member, "Marital_Stat", true) == 0) lst.Add(Convert.IsDBNull(row["Marital_Stat"]) ? null : (string)row["Marital_Stat"]);
            if (string.Compare(projection.Member, "Hold_Pymnt", true) == 0) lst.Add(Convert.IsDBNull(row["Hold_Pymnt"]) ? null : (string)row["Hold_Pymnt"]);
            if (string.Compare(projection.Member, "Bank_Acct_No", true) == 0) lst.Add(Convert.IsDBNull(row["Bank_Acct_No"]) ? null : (string)row["Bank_Acct_No"]);
            if (string.Compare(projection.Member, "State_udf", true) == 0) lst.Add(Convert.IsDBNull(row["State_udf"]) ? (decimal?)null : (decimal?)row["State_udf"]);
            if (string.Compare(projection.Member, "FlexDeptAcctType", true) == 0) lst.Add(Convert.IsDBNull(row["FlexDeptAcctType"]) ? null : (string)row["FlexDeptAcctType"]);
            if (string.Compare(projection.Member, "Last_Inc_Date", true) == 0) lst.Add(Convert.IsDBNull(row["Last_Inc_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Inc_Date"]);
            if (string.Compare(projection.Member, "InsertedBy", true) == 0) lst.Add(Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"]);
            if (string.Compare(projection.Member, "InsertedOn", true) == 0) lst.Add(Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"]);
            if (string.Compare(projection.Member, "InsertedMachineInfo", true) == 0) lst.Add(Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"]);
            if (string.Compare(projection.Member, "UpdatedBy", true) == 0) lst.Add(Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"]);
            if (string.Compare(projection.Member, "UpdatedOn", true) == 0) lst.Add(Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"]);
            if (string.Compare(projection.Member, "UpdatedMachineInfo", true) == 0) lst.Add(Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"]);
            if (string.Compare(projection.Member, "IsActive", true) == 0) lst.Add(Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"]);
            if (string.Compare(projection.Member, "occupation", true) == 0) lst.Add(Convert.IsDBNull(row["occupation"]) ? null : (string)row["occupation"]);
            if (string.Compare(projection.Member, "CompanyId", true) == 0) lst.Add(Convert.IsDBNull(row["CompanyId"]) ? (Int32?)null : (Int32?)row["CompanyId"]);
            if (string.Compare(projection.Member, "IsemployeeDirector", true) == 0) lst.Add(Convert.IsDBNull(row["IsemployeeDirector"]) ? (bool?)null : (bool?)row["IsemployeeDirector"]);
            if (string.Compare(projection.Member, "IsdirectorOnly", true) == 0) lst.Add(Convert.IsDBNull(row["IsdirectorOnly"]) ? (bool?)null : (bool?)row["IsdirectorOnly"]);
            if (string.Compare(projection.Member, "IsLevyExempt", true) == 0) lst.Add(Convert.IsDBNull(row["IsLevyExempt"]) ? (bool?)null : (bool?)row["IsLevyExempt"]);
            if (string.Compare(projection.Member, "Department", true) == 0) lst.Add(Convert.IsDBNull(row["Department"]) ? null : (string)row["Department"]);
          }
        }
        return dict;
      }
      catch
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }

    ///<Summary>
    ///Select all rows by filter criteria
    ///This method returns all data rows in the table using criteriaquery api MasterEmployee
    ///</Summary>
    ///<returns>
    ///IList-DLMasterEmployee.
    ///</returns>
    ///<parameters>
    ///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
    ///</parameters>
    public static IList<DLMasterEmployee> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_SelectAllByCriteria]";
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;

      DataTable dt = new DataTable("MasterEmployee");
      SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
      try
      {
        string whereClause = GetSelectionCriteria(listCriterion);
        string orderClause = GetSelectionOrder(listOrder);
        string skipClause = GetSelectionSkip(dataSkip);
        string takeClause = GetSelectionTake(dataTake);

        if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
          throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

        command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause ?? (object)DBNull.Value));

        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        sqlAdapter.Fill(dt);

        List<DLMasterEmployee> objList = new List<DLMasterEmployee>();
        if (dt.Rows.Count > 0)
        {
          foreach (DataRow row in dt.Rows)
          {
            DLMasterEmployee retObj = new DLMasterEmployee();
            retObj._employeeID = Convert.IsDBNull(row["EmployeeID"]) ? (Int32?)null : (Int32?)row["EmployeeID"];
            retObj._emplCode = Convert.IsDBNull(row["Empl_Code"]) ? null : (string)row["Empl_Code"];
            retObj._socSecNum = Convert.IsDBNull(row["Soc_Sec_Num"]) ? null : (string)row["Soc_Sec_Num"];
            retObj._firstName = Convert.IsDBNull(row["First_Name"]) ? null : (string)row["First_Name"];
            retObj._middleName = Convert.IsDBNull(row["Middle_Name"]) ? null : (string)row["Middle_Name"];
            retObj._lastName = Convert.IsDBNull(row["Last_Name"]) ? null : (string)row["Last_Name"];
            retObj._typeCode = Convert.IsDBNull(row["Type_Code"]) ? null : (string)row["Type_Code"];
            retObj._birthDate = Convert.IsDBNull(row["BirthDate"]) ? (DateTime?)null : (DateTime?)row["BirthDate"];
            retObj._gender = Convert.IsDBNull(row["Gender"]) ? null : (string)row["Gender"];
            retObj._address1 = Convert.IsDBNull(row["Address1"]) ? null : (string)row["Address1"];
            retObj._address2 = Convert.IsDBNull(row["Address2"]) ? null : (string)row["Address2"];
            retObj._city = Convert.IsDBNull(row["City"]) ? null : (string)row["City"];
            retObj._state = Convert.IsDBNull(row["State"]) ? null : (string)row["State"];
            retObj._country = Convert.IsDBNull(row["Country"]) ? null : (string)row["Country"];
            retObj._zip = Convert.IsDBNull(row["Zip"]) ? null : (string)row["Zip"];
            retObj._phone = Convert.IsDBNull(row["Phone"]) ? null : (string)row["Phone"];
            retObj._mobile = Convert.IsDBNull(row["Mobile"]) ? null : (string)row["Mobile"];
            retObj._email = Convert.IsDBNull(row["Email"]) ? null : (string)row["Email"];
            retObj._tin = Convert.IsDBNull(row["TIN"]) ? null : (string)row["TIN"];
            retObj._appintDate = Convert.IsDBNull(row["Appint_Date"]) ? (DateTime?)null : (DateTime?)row["Appint_Date"];
            retObj._terminated = Convert.IsDBNull(row["Terminated"]) ? (DateTime?)null : (DateTime?)row["Terminated"];
            retObj._emplStatus = Convert.IsDBNull(row["Empl_Status"]) ? null : (string)row["Empl_Status"];
            retObj._payPeriod = Convert.IsDBNull(row["Pay_Period"]) ? null : (string)row["Pay_Period"];
            retObj._allowAnces = Convert.IsDBNull(row["AllowAnces"]) ? (Int32?)null : (Int32?)row["AllowAnces"];
            retObj._stateAllow = Convert.IsDBNull(row["State_Allow"]) ? (Int32?)null : (Int32?)row["State_Allow"];
            retObj._maritalStat = Convert.IsDBNull(row["Marital_Stat"]) ? null : (string)row["Marital_Stat"];
            retObj._holdPymnt = Convert.IsDBNull(row["Hold_Pymnt"]) ? null : (string)row["Hold_Pymnt"];
            retObj._bankAcctNo = Convert.IsDBNull(row["Bank_Acct_No"]) ? null : (string)row["Bank_Acct_No"];
            retObj._stateUdf = Convert.IsDBNull(row["State_udf"]) ? (decimal?)null : (decimal?)row["State_udf"];
            retObj._flexDeptAcctType = Convert.IsDBNull(row["FlexDeptAcctType"]) ? null : (string)row["FlexDeptAcctType"];
            retObj._lastIncDate = Convert.IsDBNull(row["Last_Inc_Date"]) ? (DateTime?)null : (DateTime?)row["Last_Inc_Date"];
            retObj._insertedBy = Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"];
            retObj._insertedOn = Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"];
            retObj._insertedMachineInfo = Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"];
            retObj._updatedBy = Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"];
            retObj._updatedOn = Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"];
            retObj._updatedMachineInfo = Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"];
            retObj._isActive = Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"];
            retObj._occupation = Convert.IsDBNull(row["occupation"]) ? null : (string)row["occupation"];
            retObj._companyid = Convert.IsDBNull(row["CompanyId"]) ? (Int32?)null : (Int32?)row["CompanyId"];
            retObj._IsemployeeDirector = Convert.IsDBNull(row["IsemployeeDirector"]) ? (bool?)null : (bool?)row["IsemployeeDirector"];
            retObj._IsdirectorOnly = Convert.IsDBNull(row["IsdirectorOnly"]) ? (bool?)null : (bool?)row["IsdirectorOnly"];
            retObj._isLevyExempt = Convert.IsDBNull(row["IsLevyExempt"]) ? (bool?)null : (bool?)row["IsLevyExempt"];
            retObj._department = Convert.IsDBNull(row["Department"]) ? null : (string)row["Department"];
            objList.Add(retObj);
          }
        }
        return objList;
      }
      catch
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }

    ///<Summary>
    ///Select count of all rows using criteriaquery api
    ///This method returns all data rows in the table using criteriaquery api MasterEmployee
    ///</Summary>
    ///<returns>
    ///Int32
    ///</returns>
    ///<parameters>
    ///IList<IDataCriterion> listCriterion
    ///</parameters>
    public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_SelectAllByCriteriaCount]";
      command.CommandType = CommandType.StoredProcedure;
      SqlConnection staticConnection = StaticSqlConnection;
      command.Connection = staticConnection;

      try
      {
        string whereClause = GetSelectionCriteria(listCriterion);
        command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));

        if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
        Int32 retCount = (Int32)command.ExecuteScalar();

        return retCount;
      }
      catch
      {
        throw;
      }
      finally
      {
        staticConnection.Close();
        command.Dispose();
      }
    }

    ///<Summary>
    ///Update one row by primary key(s)
    ///This method allows the object to update itself in the table MasterEmployee based on its primary key(s)
    ///</Summary>
    ///<returns>
    ///void
    ///</returns>
    ///<parameters>
    ///
    ///</parameters>
    public virtual void Update()
    {
      SqlCommand command = new SqlCommand();
      command.CommandText = "[dbo].[ctprMasterEmployee_UpdateOne]";
      command.CommandType = CommandType.StoredProcedure;
      command.Connection = _connectionProvider.Connection;
      command.Transaction = _connectionProvider.CurrentTransaction;

      try
      {
        command.Parameters.Add(new SqlParameter("@EmployeeID", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_employeeID ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Empl_Code", SqlDbType.NVarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_emplCode ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Soc_Sec_Num", SqlDbType.NVarChar, 15, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_socSecNum ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@First_Name", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_firstName ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Middle_Name", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_middleName ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Last_Name", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_lastName ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Type_Code", SqlDbType.NVarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_typeCode ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@BirthDate", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_birthDate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Gender", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_gender ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Address1", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_address1 ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Address2", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_address2 ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@City", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_city ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@State", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_state ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Country", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_country ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Zip", SqlDbType.NVarChar, 10, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_zip ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Phone", SqlDbType.NVarChar, 20, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_phone ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Mobile", SqlDbType.NVarChar, 20, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_mobile ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Email", SqlDbType.NVarChar, 40, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_email ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@TIN", SqlDbType.NVarChar, 20, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_tin ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Appint_Date", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_appintDate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Last_Pay_Date", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_lastpaydate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Terminated", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_terminated ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@WagesPayDate", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_wagespayDate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Empl_Status", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_emplStatus ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Pay_Period", SqlDbType.NVarChar, 3, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_payPeriod ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@AllowAnces", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_allowAnces ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@State_Allow", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_stateAllow ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Marital_Stat", SqlDbType.NVarChar, 2, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_maritalStat ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Hold_Pymnt", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_holdPymnt ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Bank_Acct_No", SqlDbType.NVarChar, 17, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_bankAcctNo ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@State_udf", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 8, "", DataRowVersion.Proposed, (object)_stateUdf ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@FlexDeptAcctType", SqlDbType.NVarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_flexDeptAcctType ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Last_Inc_Date", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_lastIncDate ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@InsertedBy", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_insertedBy ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@InsertedOn", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertedOn ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@InsertedMachineInfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertedMachineInfo ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@UpdatedBy", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_updatedBy ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@UpdatedOn", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedOn ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@UpdatedMachineInfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedMachineInfo ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@IsActive", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_isActive ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@occupation", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_occupation ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@CompanyId", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_companyid ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@IsdirectorOnly", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_IsdirectorOnly ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@IsemployeeDirector", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_IsemployeeDirector ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@IsLevyExempt", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_isLevyExempt ?? (object)DBNull.Value));
        command.Parameters.Add(new SqlParameter("@Department", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_department ?? (object)DBNull.Value));
        command.ExecuteNonQuery();

        _employeeID = Convert.IsDBNull(command.Parameters["@EmployeeID"].Value) ? (Int32?)null : (Int32?)command.Parameters["@EmployeeID"].Value;
        _emplCode = Convert.IsDBNull(command.Parameters["@Empl_Code"].Value) ? null : (string)command.Parameters["@Empl_Code"].Value;
        _socSecNum = Convert.IsDBNull(command.Parameters["@Soc_Sec_Num"].Value) ? null : (string)command.Parameters["@Soc_Sec_Num"].Value;
        _firstName = Convert.IsDBNull(command.Parameters["@First_Name"].Value) ? null : (string)command.Parameters["@First_Name"].Value;
        _middleName = Convert.IsDBNull(command.Parameters["@Middle_Name"].Value) ? null : (string)command.Parameters["@Middle_Name"].Value;
        _lastName = Convert.IsDBNull(command.Parameters["@Last_Name"].Value) ? null : (string)command.Parameters["@Last_Name"].Value;
        _typeCode = Convert.IsDBNull(command.Parameters["@Type_Code"].Value) ? null : (string)command.Parameters["@Type_Code"].Value;
        _birthDate = Convert.IsDBNull(command.Parameters["@BirthDate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@BirthDate"].Value;
        _gender = Convert.IsDBNull(command.Parameters["@Gender"].Value) ? null : (string)command.Parameters["@Gender"].Value;
        _address1 = Convert.IsDBNull(command.Parameters["@Address1"].Value) ? null : (string)command.Parameters["@Address1"].Value;
        _address2 = Convert.IsDBNull(command.Parameters["@Address2"].Value) ? null : (string)command.Parameters["@Address2"].Value;
        _city = Convert.IsDBNull(command.Parameters["@City"].Value) ? null : (string)command.Parameters["@City"].Value;
        _state = Convert.IsDBNull(command.Parameters["@State"].Value) ? null : (string)command.Parameters["@State"].Value;
        _country = Convert.IsDBNull(command.Parameters["@Country"].Value) ? null : (string)command.Parameters["@Country"].Value;
        _zip = Convert.IsDBNull(command.Parameters["@Zip"].Value) ? null : (string)command.Parameters["@Zip"].Value;
        _phone = Convert.IsDBNull(command.Parameters["@Phone"].Value) ? null : (string)command.Parameters["@Phone"].Value;
        _mobile = Convert.IsDBNull(command.Parameters["@Mobile"].Value) ? null : (string)command.Parameters["@Mobile"].Value;
        _email = Convert.IsDBNull(command.Parameters["@Email"].Value) ? null : (string)command.Parameters["@Email"].Value;
        _tin = Convert.IsDBNull(command.Parameters["@TIN"].Value) ? null : (string)command.Parameters["@TIN"].Value;
        _appintDate = Convert.IsDBNull(command.Parameters["@Appint_Date"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@Appint_Date"].Value;
        _lastpaydate = Convert.IsDBNull(command.Parameters["@Last_Pay_Date"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@Last_Pay_Date"].Value;
        _terminated = Convert.IsDBNull(command.Parameters["@Terminated"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@Terminated"].Value;
        _wagespayDate = Convert.IsDBNull(command.Parameters["@WagesPayDate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@WagesPayDate"].Value;
        _emplStatus = Convert.IsDBNull(command.Parameters["@Empl_Status"].Value) ? null : (string)command.Parameters["@Empl_Status"].Value;
        _payPeriod = Convert.IsDBNull(command.Parameters["@Pay_Period"].Value) ? null : (string)command.Parameters["@Pay_Period"].Value;
        _allowAnces = Convert.IsDBNull(command.Parameters["@AllowAnces"].Value) ? (Int32?)null : (Int32?)command.Parameters["@AllowAnces"].Value;
        _stateAllow = Convert.IsDBNull(command.Parameters["@State_Allow"].Value) ? (Int32?)null : (Int32?)command.Parameters["@State_Allow"].Value;
        _maritalStat = Convert.IsDBNull(command.Parameters["@Marital_Stat"].Value) ? null : (string)command.Parameters["@Marital_Stat"].Value;
        _holdPymnt = Convert.IsDBNull(command.Parameters["@Hold_Pymnt"].Value) ? null : (string)command.Parameters["@Hold_Pymnt"].Value;
        _bankAcctNo = Convert.IsDBNull(command.Parameters["@Bank_Acct_No"].Value) ? null : (string)command.Parameters["@Bank_Acct_No"].Value;
        _stateUdf = Convert.IsDBNull(command.Parameters["@State_udf"].Value) ? (decimal?)null : (decimal?)command.Parameters["@State_udf"].Value;
        _flexDeptAcctType = Convert.IsDBNull(command.Parameters["@FlexDeptAcctType"].Value) ? null : (string)command.Parameters["@FlexDeptAcctType"].Value;
        _lastIncDate = Convert.IsDBNull(command.Parameters["@Last_Inc_Date"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@Last_Inc_Date"].Value;
        _insertedBy = Convert.IsDBNull(command.Parameters["@InsertedBy"].Value) ? (Int32?)null : (Int32?)command.Parameters["@InsertedBy"].Value;
        _insertedOn = Convert.IsDBNull(command.Parameters["@InsertedOn"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@InsertedOn"].Value;
        _insertedMachineInfo = Convert.IsDBNull(command.Parameters["@InsertedMachineInfo"].Value) ? null : (string)command.Parameters["@InsertedMachineInfo"].Value;
        _updatedBy = Convert.IsDBNull(command.Parameters["@UpdatedBy"].Value) ? (Int32?)null : (Int32?)command.Parameters["@UpdatedBy"].Value;
        _updatedOn = Convert.IsDBNull(command.Parameters["@UpdatedOn"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@UpdatedOn"].Value;
        _updatedMachineInfo = Convert.IsDBNull(command.Parameters["@UpdatedMachineInfo"].Value) ? null : (string)command.Parameters["@UpdatedMachineInfo"].Value;
        _isActive = Convert.IsDBNull(command.Parameters["@IsActive"].Value) ? (bool?)null : (bool?)command.Parameters["@IsActive"].Value;
        _occupation = Convert.IsDBNull(command.Parameters["@occupation"].Value) ? null : (string)command.Parameters["@occupation"].Value;
        _insertedBy = Convert.IsDBNull(command.Parameters["@CompanyId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@CompanyId"].Value;
        _IsdirectorOnly = Convert.IsDBNull(command.Parameters["@IsdirectorOnly"].Value) ? (bool?)null : (bool?)command.Parameters["@IsdirectorOnly"].Value;
        _IsemployeeDirector = Convert.IsDBNull(command.Parameters["@IsemployeeDirector"].Value) ? (bool?)null : (bool?)command.Parameters["@IsemployeeDirector"].Value;
        _isLevyExempt = Convert.IsDBNull(command.Parameters["@IsLevyExempt"].Value) ? (bool?)null : (bool?)command.Parameters["@IsLevyExempt"].Value;
        _department = Convert.IsDBNull(command.Parameters["@Department"].Value) ? null : (string)command.Parameters["@Department"].Value;
      }
      catch
      {
        throw;
      }
      finally
      {
        command.Dispose();
      }
    }

    #endregion

    #region member properties

    public Int32? EmployeeID
    {
      get
      {
        return _employeeID;
      }
      set
      {
        _employeeID = value;
      }
    }

    public string EmplCode
    {
      get
      {
        return _emplCode;
      }
      set
      {
        _emplCode = value;
      }
    }

    public string SocSecNum
    {
      get
      {
        return _socSecNum;
      }
      set
      {
        _socSecNum = value;
      }
    }

    public string FirstName
    {
      get
      {
        return _firstName;
      }
      set
      {
        _firstName = value;
      }
    }

    public string MiddleName
    {
      get
      {
        return _middleName;
      }
      set
      {
        _middleName = value;
      }
    }

    public string LastName
    {
      get
      {
        return _lastName;
      }
      set
      {
        _lastName = value;
      }
    }

    public string TypeCode
    {
      get
      {
        return _typeCode;
      }
      set
      {
        _typeCode = value;
      }
    }

    public DateTime? BirthDate
    {
      get
      {
        return _birthDate;
      }
      set
      {
        _birthDate = value;
      }
    }

    public string Gender
    {
      get
      {
        return _gender;
      }
      set
      {
        _gender = value;
      }
    }

    public string Address1
    {
      get
      {
        return _address1;
      }
      set
      {
        _address1 = value;
      }
    }

    public string Address2
    {
      get
      {
        return _address2;
      }
      set
      {
        _address2 = value;
      }
    }

    public string City
    {
      get
      {
        return _city;
      }
      set
      {
        _city = value;
      }
    }

    public string State
    {
      get
      {
        return _state;
      }
      set
      {
        _state = value;
      }
    }

    public string Country
    {
      get
      {
        return _country;
      }
      set
      {
        _country = value;
      }
    }

    public string Zip
    {
      get
      {
        return _zip;
      }
      set
      {
        _zip = value;
      }
    }

    public string Phone
    {
      get
      {
        return _phone;
      }
      set
      {
        _phone = value;
      }
    }

    public string Mobile
    {
      get
      {
        return _mobile;
      }
      set
      {
        _mobile = value;
      }
    }

    public string Email
    {
      get
      {
        return _email;
      }
      set
      {
        _email = value;
      }
    }

    public string Tin
    {
      get
      {
        return _tin;
      }
      set
      {
        _tin = value;
      }
    }

    public DateTime? AppintDate
    {
      get
      {
        return _appintDate;
      }
      set
      {
        _appintDate = value;
      }
    }
    public DateTime? Last_Pay_Date
    {
      get
      {
        return _lastpaydate;
      }
      set
      {
        _lastpaydate = value;
      }
    }

    public DateTime? Terminated
    {
      get
      {
        return _terminated;
      }
      set
      {
        _terminated = value;
      }
    }
    public virtual DateTime? WagesPayDate
    {
      get
      {
        return _wagespayDate;
      }
      set
      {
        _wagespayDate = value;
      }
    }
    public string EmplStatus
    {
      get
      {
        return _emplStatus;
      }
      set
      {
        _emplStatus = value;
      }
    }

    public string PayPeriodforlist
    {
      get
      {
        return _payPeriodforlist;
      }
      set
      {
        _payPeriodforlist = value;
      }
    }
    public string PayPeriod
    {
      get
      {
        return _payPeriod;
      }
      set
      {
        _payPeriod = value;
      }
    }
    public Int32? AllowAnces
    {
      get
      {
        return _allowAnces;
      }
      set
      {
        _allowAnces = value;
      }
    }

    public Int32? StateAllow
    {
      get
      {
        return _stateAllow;
      }
      set
      {
        _stateAllow = value;
      }
    }

    public string MaritalStat
    {
      get
      {
        return _maritalStat;
      }
      set
      {
        _maritalStat = value;
      }
    }

    public string HoldPymnt
    {
      get
      {
        return _holdPymnt;
      }
      set
      {
        _holdPymnt = value;
      }
    }

    public string BankAcctNo
    {
      get
      {
        return _bankAcctNo;
      }
      set
      {
        _bankAcctNo = value;
      }
    }

    public decimal? StateUdf
    {
      get
      {
        return _stateUdf;
      }
      set
      {
        _stateUdf = value;
      }
    }

    public string FlexDeptAcctType
    {
      get
      {
        return _flexDeptAcctType;
      }
      set
      {
        _flexDeptAcctType = value;
      }
    }

    public DateTime? LastIncDate
    {
      get
      {
        return _lastIncDate;
      }
      set
      {
        _lastIncDate = value;
      }
    }

    public Int32? InsertedBy
    {
      get
      {
        return _insertedBy;
      }
      set
      {
        _insertedBy = value;
      }
    }

    public DateTime? InsertedOn
    {
      get
      {
        return _insertedOn;
      }
      set
      {
        _insertedOn = value;
      }
    }

    public string InsertedMachineInfo
    {
      get
      {
        return _insertedMachineInfo;
      }
      set
      {
        _insertedMachineInfo = value;
      }
    }

    public Int32? UpdatedBy
    {
      get
      {
        return _updatedBy;
      }
      set
      {
        _updatedBy = value;
      }
    }

    public DateTime? UpdatedOn
    {
      get
      {
        return _updatedOn;
      }
      set
      {
        _updatedOn = value;
      }
    }

    public string UpdatedMachineInfo
    {
      get
      {
        return _updatedMachineInfo;
      }
      set
      {
        _updatedMachineInfo = value;
      }
    }

    public bool? IsActive
    {
      get
      {
        return _isActive;
      }
      set
      {
        _isActive = value;
      }
    }

    public string occupation
    {
      get
      {
        return _occupation;
      }
      set
      {
        _occupation = value;
      }
    }
    public string Department
    {
      get
      {
        return _department;
      }
      set
      {
        _department = value;
      }
    }
    public Int32? CompanyId
    {
      get
      {
        return _companyid;
      }
      set
      {
        _companyid = value;
      }
    }
    public decimal? Wadeg
    {
      get
      {
        return _wadeg;
      }
      set
      {
        _wadeg = value;
      }
    }
    public decimal? wage_Amt
    {
      get
      {
        return _wage_Amt;
      }
      set
      {
        _wage_Amt = value;
      }
    }
    public string ApDate
    {
      get
      {
        return _ApDate;
      }
      set
      {
        _ApDate = value;
      }
    }
    public string TrDate
    {
      get
      {
        return _TrDate;
      }
      set
      {
        _TrDate = value;
      }
    }
    public virtual bool? IsdirectorOnly
    {
      get
      {
        return _IsdirectorOnly;
      }
      set
      {
        _IsdirectorOnly = value;
      }
    }
    public virtual bool? IsemployeeDirector
    {
      get
      {
        return _IsemployeeDirector;
      }
      set
      {
        _IsemployeeDirector = value;
      }
    }
    public bool? IsLevyExempt
    {
      get
      {
        return _isLevyExempt;
      }
      set
      {
        _isLevyExempt = value;
      }
    }
    public string IsempDirector
    {
      get
      {
        return _IsempDirector;
      }
      set
      {
        _IsempDirector = value;
      }
    }
    public string IsempDirectorimg
    {
      get
      {
        return _IsempDirectorimg;
      }
      set
      {
        _IsempDirectorimg = value;
      }
    }
    public string emptype
    {
      get
      {
        return _emptype;
      }
      set
      {
        _emptype = value;
      }
    }
    public Int32 emp_S_no
    {
      get
      {
        return _emp_S_no;
      }
      set
      {
        _emp_S_no = value;
      }
    }
    #endregion
  }
}
