/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using C3WizardLayer.DataObjects.Interfaces;

namespace C3WizardLayer.DataObjects
{
	public partial class DLPayrollProcessDetails : C3WizardLayerConn_BaseData
	{
		#region member variables

        protected Int32? _pybatchid;
        protected Int32? _batchprocessid;
        protected string _processname;
        protected string _employeetype;
        protected DateTime? _processendedon;
        protected Int32? _companyid;
        protected Int32? _recordsprocessed;
       protected string _searchcriteria;
        protected Int32? _insertby;
		protected DateTime? _insertdate;
		protected string _insertmachineinfo;
		protected Int32? _updateby;
		protected DateTime? _updatedate;
		protected string _updatemachineinfo;


        
		#endregion

		#region class methods
        public DLPayrollProcessDetails()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table MasterCompany based on the primary key(s)
		///</Summary>
		///<returns>
		///DLMasterCompany
		///</returns>
		///<parameters>
		///Int32? companyId
		///</parameters>
        public static DLPayrollProcessDetails SelectOne(Int32? pybatchid)
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Detail_SelectOne]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

            DataTable dt = new DataTable("Payroll_Process_Detail");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
                command.Parameters.Add(new SqlParameter("@pybatchid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)pybatchid ?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

                DLPayrollProcessDetails retObj = null;
				if(dt.Rows.Count > 0)
				{
                     
                    retObj = new DLPayrollProcessDetails();
                    retObj._pybatchid = Convert.IsDBNull(dt.Rows[0]["pybatchid"]) ? (Int32?)null : (Int32?)dt.Rows[0]["pybatchid"];
                    retObj._batchprocessid = Convert.IsDBNull(dt.Rows[0]["batchprocessid"]) ? (Int32?)null : (Int32?)dt.Rows[0]["batchprocessid"];
                    retObj._processname= Convert.IsDBNull(dt.Rows[0]["processname"]) ? null : (string)dt.Rows[0]["processname"];
                    retObj._employeetype	= Convert.IsDBNull(dt.Rows[0]["employeetype"]) ? null : (string)dt.Rows[0]["employeetype"];
                    retObj._processendedon= Convert.IsDBNull(dt.Rows[0]["processendedon"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["processendedon"];
                    retObj._companyid= Convert.IsDBNull(dt.Rows[0]["companyid"]) ? (Int32?)null : (Int32?)dt.Rows[0]["companyid"];
                    retObj._recordsprocessed= Convert.IsDBNull(dt.Rows[0]["recordsprocessed"]) ? (Int32?)null : (Int32?)dt.Rows[0]["recordsprocessed"];
                    retObj._searchcriteria= Convert.IsDBNull(dt.Rows[0]["searchcriteria"]) ? null : (string)dt.Rows[0]["searchcriteria"];
                    retObj._insertby= Convert.IsDBNull(dt.Rows[0]["insertby"]) ? (Int32?)null : (Int32?)dt.Rows[0]["insertby"];
					retObj._insertdate= Convert.IsDBNull(dt.Rows[0]["insertdate"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["insertdate"];
					retObj._insertmachineinfo= Convert.IsDBNull(dt.Rows[0]["insertmachineinfo"]) ? null : (string)dt.Rows[0]["insertmachineinfo"];
					retObj._updateby= Convert.IsDBNull(dt.Rows[0]["updateby"]) ? (Int32?)null : (Int32?)dt.Rows[0]["updateby"];
					retObj._updatedate= Convert.IsDBNull(dt.Rows[0]["updatedate"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["updatedate"];
					retObj._updatemachineinfo= Convert.IsDBNull(dt.Rows[0]["updatemachineinfo"]) ? null : (string)dt.Rows[0]["updatemachineinfo"];
				}
				return retObj;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table MasterCompany based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Detail_DeleteOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
                command.Parameters.Add(new SqlParameter("@pybatchid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_pybatchid ?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table MasterCompany
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
        public virtual void Insert(int companyid)
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Details_InsertOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
             
				command.Parameters.Add(new SqlParameter("@pybatchid", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _pybatchid));
                command.Parameters.Add(new SqlParameter("@batchprocessid", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_batchprocessid?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@processname", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_processname?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@employeetype", SqlDbType.NVarChar, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_employeetype?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@processendedon", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_processendedon?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@recordsprocessed", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_recordsprocessed ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@companyid", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)companyid?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@searchcriteria", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_searchcriteria?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@insertby", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_insertby?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@insertdate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertdate?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@insertmachineinfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertmachineinfo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@updateby", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_updateby?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@updatedate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedate?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@updatemachineinfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatemachineinfo?? (object)DBNull.Value));

				command.ExecuteNonQuery();
                
                _pybatchid = Convert.IsDBNull(command.Parameters["@pybatchid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@pybatchid"].Value;
                _batchprocessid = Convert.IsDBNull(command.Parameters["@batchprocessid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@batchprocessid"].Value;
                _processname = Convert.IsDBNull(command.Parameters["@processname"].Value) ? null : (string)command.Parameters["@processname"].Value;
                _employeetype = Convert.IsDBNull(command.Parameters["@employeetype"].Value) ? null : (string)command.Parameters["@employeetype"].Value;
                _processendedon = Convert.IsDBNull(command.Parameters["@processendedon"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@processendedon"].Value;
                _companyid = Convert.IsDBNull(command.Parameters["@companyid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@companyid"].Value;
                _recordsprocessed = Convert.IsDBNull(command.Parameters["@recordsprocessed"].Value) ? (Int32?)null : (Int32?)command.Parameters["@recordsprocessed"].Value;
                _searchcriteria = Convert.IsDBNull(command.Parameters["@searchcriteria"].Value) ? null : (string)command.Parameters["@searchcriteria"].Value;
                _insertby = Convert.IsDBNull(command.Parameters["@insertby"].Value) ? (Int32?)null : (Int32?)command.Parameters["@insertby"].Value;
                _insertdate = Convert.IsDBNull(command.Parameters["@insertdate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@insertdate"].Value;
                _insertmachineinfo = Convert.IsDBNull(command.Parameters["@insertmachineinfo"].Value) ? null : (string)command.Parameters["@insertmachineinfo"].Value;
                _updateby = Convert.IsDBNull(command.Parameters["@updateby"].Value) ? (Int32?)null : (Int32?)command.Parameters["@updateby"].Value;
                _updatedate = Convert.IsDBNull(command.Parameters["@updatedate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@updatedate"].Value;
                _updatemachineinfo = Convert.IsDBNull(command.Parameters["@updatemachineinfo"].Value) ? null : (string)command.Parameters["@updatemachineinfo"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table MasterCompany
		///</Summary>
		///<returns>
		///IList-DLMasterCompany.
		///</returns>
		///<parameters>
		///
		///</parameters>
        public static IList<DLPayrollProcessDetails> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Detail_SelectAll]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

            DataTable dt = new DataTable("Payroll_Process_Detail");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

                List<DLPayrollProcessDetails> objList = new List<DLPayrollProcessDetails>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
                        DLPayrollProcessDetails retObj = new DLPayrollProcessDetails();


                        retObj._pybatchid = Convert.IsDBNull(row["pybatchid"]) ? (Int32?)null : (Int32?)row["pybatchid"];
                        retObj._batchprocessid = Convert.IsDBNull(row["batchprocessid"]) ? (Int32?)null : (Int32?)row["batchprocessid"];
                        retObj._processname = Convert.IsDBNull(row["processname"]) ? null : (string)row["processname"];
                        retObj._employeetype = Convert.IsDBNull(row["employeetype"]) ? null : (string)row["employeetype"];
                        retObj._processendedon = Convert.IsDBNull(row["processendedon"]) ? (DateTime?)null : (DateTime?)row["processendedon"];
                        retObj._companyid = Convert.IsDBNull(row["companyid"]) ? (Int32?)null : (Int32?)row["companyid"];
                        retObj._recordsprocessed = Convert.IsDBNull(row["recordsprocessed"]) ? (Int32?)null : (Int32?)row["recordsprocessed"];
                        retObj._searchcriteria = Convert.IsDBNull(row["searchcriteria"]) ? null : (string)row["searchcriteria"];
                        retObj._insertby = Convert.IsDBNull(row["insertby"]) ? (Int32?)null : (Int32?)row["insertby"];
                        retObj._insertdate = Convert.IsDBNull(row["insertdate"]) ? (DateTime?)null : (DateTime?)row["insertdate"];
                        retObj._insertmachineinfo = Convert.IsDBNull(row["insertmachineinfo"]) ? null : (string)row["insertmachineinfo"];
                        retObj._updateby = Convert.IsDBNull(row["updateby"]) ? (Int32?)null : (Int32?)row["updateby"];
                        retObj._updatedate = Convert.IsDBNull(row["updatedate"]) ? (DateTime?)null : (DateTime?)row["updatedate"];
                        retObj._updatemachineinfo = Convert.IsDBNull(row["updatemachineinfo"]) ? null : (string)row["updatemachineinfo"];


						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Details_SelectAllCount]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

        ///<Summary>
        ///Select specific fields of all rows using criteriaquery api
        ///This method returns specific fields of all data rows in the table using criteriaquery apiMasterCompany
        ///</Summary>
        ///<returns>
        ///IDictionary-string, IList-object..
        ///</returns>
        ///<parameters>
        ///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
        ///</parameters>
        public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
        {
            SqlCommand command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Detail_SelectAllByCriteriaProjection]";
            command.CommandType = CommandType.StoredProcedure;
            SqlConnection staticConnection = StaticSqlConnection;
            command.Connection = staticConnection;

            DataTable dt = new DataTable("Payroll_Process_Detail");
            SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
            try
            {
                string fieldsField = GetProjections(listProjection);
                string whereClause = GetSelectionCriteria(listCriterion);
                string orderClause = GetSelectionOrder(listOrder);
                string skipClause = GetSelectionSkip(dataSkip);
                string takeClause = GetSelectionTake(dataTake);

                if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
                    throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

                command.Parameters.Add(new SqlParameter("@FieldsField", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)fieldsField ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause ?? (object)DBNull.Value));

                if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
                sqlAdapter.Fill(dt);

                IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
                foreach (IDataProjection projection in listProjection)
                {
                    IList<object> lst = new List<object>();
                    dict.Add(projection.Member, lst);
                    foreach (DataRow row in dt.Rows)
                    {
                     
                        if (string.Compare(projection.Member, "pybatchid", true) == 0) lst.Add(Convert.IsDBNull(row["pybatchid"]) ? (Int32?)null : (Int32?)row["pybatchid"]);
                        if (string.Compare(projection.Member, "batchprocessid", true) == 0) lst.Add(Convert.IsDBNull(row["batchprocessid"]) ? (Int32?)null : (Int32?)row["batchprocessid"]);
                        if (string.Compare(projection.Member, "processname", true) == 0) lst.Add(Convert.IsDBNull(row["processname"]) ? null : (string)row["processname"]);
                         if (string.Compare(projection.Member, "employeetype", true) == 0) lst.Add(Convert.IsDBNull(row["employeetype"]) ? null : (string)row["employeetype"]);
                         if (string.Compare(projection.Member, "processendedon", true) == 0) lst.Add(Convert.IsDBNull(row["processendedon"]) ? (DateTime?)null : (DateTime?)row["processendedon"]);

                        
                        if (string.Compare(projection.Member, "companyid", true) == 0) lst.Add(Convert.IsDBNull(row["companyid"]) ? (Int32?)null : (Int32?)row["companyid"]);
                        if (string.Compare(projection.Member, "recordsprocessed", true) == 0) lst.Add(Convert.IsDBNull(row["recordsprocessed"]) ? (Int32?)null : (Int32?)row["recordsprocessed"]);
                        
                        if (string.Compare(projection.Member, "searchcriteria", true) == 0) lst.Add(Convert.IsDBNull(row["searchcriteria"]) ? null : (string)row["searchcriteria"]);

                        
                        
                        if (string.Compare(projection.Member, "insertby", true) == 0) lst.Add(Convert.IsDBNull(row["insertby"]) ? (Int32?)null : (Int32?)row["insertby"]);
                        if (string.Compare(projection.Member, "insertdate", true) == 0) lst.Add(Convert.IsDBNull(row["insertdate"]) ? (DateTime?)null : (DateTime?)row["insertdate"]);
                        if (string.Compare(projection.Member, "insertmachineinfo", true) == 0) lst.Add(Convert.IsDBNull(row["insertmachineinfo"]) ? null : (string)row["insertmachineinfo"]);
                        if (string.Compare(projection.Member, "updateby", true) == 0) lst.Add(Convert.IsDBNull(row["updateby"]) ? (Int32?)null : (Int32?)row["updateby"]);
                        if (string.Compare(projection.Member, "updatedate", true) == 0) lst.Add(Convert.IsDBNull(row["updatedate"]) ? (DateTime?)null : (DateTime?)row["updatedate"]);
                        if (string.Compare(projection.Member, "updatemachineinfo", true) == 0) lst.Add(Convert.IsDBNull(row["updatemachineinfo"]) ? null : (string)row["updatemachineinfo"]);
                        
                    }
                }
                return dict;
            }
            catch
            {
                throw;
            }
            finally
            {
                staticConnection.Close();
                command.Dispose();
            }
        }
        ///<Summary>
        ///Select all rows by filter criteria
        ///This method returns all data rows in the table using criteriaquery api MasterCompany
        ///</Summary>
        ///<returns>
        ///IList-DLMasterCompany.
        ///</returns>
        ///<parameters>
        ///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
        ///</parameters>
        public static IList<DLPayrollProcessDetails> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
        {
            SqlCommand command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Detail_SelectAllByCriteria]";
            command.CommandType = CommandType.StoredProcedure;
            SqlConnection staticConnection = StaticSqlConnection;
            command.Connection = staticConnection;

            DataTable dt = new DataTable("Payroll_Process_Detail");
            SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
            try
            {
                string whereClause = GetSelectionCriteria(listCriterion);
                string orderClause = GetSelectionOrder(listOrder);
                string skipClause = GetSelectionSkip(dataSkip);
                string takeClause = GetSelectionTake(dataTake);

                if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
                    throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

                command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause ?? (object)DBNull.Value));

                if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
                sqlAdapter.Fill(dt);

                List<DLPayrollProcessDetails> objList = new List<DLPayrollProcessDetails>();
                if (dt.Rows.Count > 0)
                {
                    foreach (DataRow row in dt.Rows)
                    {
                        DLPayrollProcessDetails retObj = new DLPayrollProcessDetails();
                        retObj._pybatchid = Convert.IsDBNull(row["pybatchid"]) ? (Int32?)null : (Int32?)row["pybatchid"];
                        retObj._batchprocessid = Convert.IsDBNull(row["batchprocessid"]) ? (Int32?)null : (Int32?)row["batchprocessid"];
                        retObj._processname = Convert.IsDBNull(row["processname"]) ? null : (string)row["processname"];
                        retObj._employeetype = Convert.IsDBNull(row["employeetype"]) ? null : (string)row["employeetype"];
                        retObj._processendedon = Convert.IsDBNull(row["processendedon"]) ? (DateTime?)null : (DateTime?)row["processendedon"];
                        retObj._companyid = Convert.IsDBNull(row["companyid"]) ? (Int32?)null : (Int32?)row["companyid"];
                        retObj._recordsprocessed = Convert.IsDBNull(row["recordsprocessed"]) ? (Int32?)null : (Int32?)row["recordsprocessed"];
                        retObj._searchcriteria = Convert.IsDBNull(row["searchcriteria"]) ? null : (string)row["searchcriteria"];
                        retObj._insertby = Convert.IsDBNull(row["insertby"]) ? (Int32?)null : (Int32?)row["insertby"];
                        retObj._insertdate = Convert.IsDBNull(row["insertdate"]) ? (DateTime?)null : (DateTime?)row["insertdate"];
                        retObj._insertmachineinfo = Convert.IsDBNull(row["insertmachineinfo"]) ? null : (string)row["insertmachineinfo"];
                        retObj._updateby = Convert.IsDBNull(row["updateby"]) ? (Int32?)null : (Int32?)row["updateby"];
                        retObj._updatedate = Convert.IsDBNull(row["updatedate"]) ? (DateTime?)null : (DateTime?)row["updatedate"];
                        retObj._updatemachineinfo = Convert.IsDBNull(row["updatemachineinfo"]) ? null : (string)row["updatemachineinfo"];
                        objList.Add(retObj);
                    }
                }
                return objList;
            }
            catch
            {
                throw;
            }
            finally
            {
                staticConnection.Close();
                command.Dispose();
            }
        }

        ///<Summary>
        ///Select count of all rows using criteriaquery api
        ///This method returns all data rows in the table using criteriaquery api MasterCompany
        ///</Summary>
        ///<returns>
        ///Int32
        ///</returns>
        ///<parameters>
        ///IList<IDataCriterion> listCriterion
        ///</parameters>
        public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
        {
            SqlCommand command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Detail_SelectAllByCriteriaCount]";
            command.CommandType = CommandType.StoredProcedure;
            SqlConnection staticConnection = StaticSqlConnection;
            command.Connection = staticConnection;

            try
            {
                string whereClause = GetSelectionCriteria(listCriterion);
                command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));

                if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
                Int32 retCount = (Int32)command.ExecuteScalar();

                return retCount;
            }
            catch
            {
                throw;
            }
            finally
            {
                staticConnection.Close();
                command.Dispose();
            }
        }

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table MasterCompany based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update(int UserId)
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Detail_UpdateOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
                 
                command.Parameters.Add(new SqlParameter("@pybatchid", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _pybatchid));
                command.Parameters.Add(new SqlParameter("@batchprocessid", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _batchprocessid));
                command.Parameters.Add(new SqlParameter("@processname", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_processname ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@employeetype", SqlDbType.NVarChar, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_employeetype ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@processendedon", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_processendedon ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@recordsprocessed", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_recordsprocessed ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@companyid", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)UserId ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@searchcriteria", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_searchcriteria ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@insertby", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_insertby ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@insertdate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertdate ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@insertmachineinfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertmachineinfo ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@updateby", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_updateby ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@updatedate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedate ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@updatemachineinfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatemachineinfo ?? (object)DBNull.Value));

				command.ExecuteNonQuery();

                _pybatchid = Convert.IsDBNull(command.Parameters["@pybatchid "].Value) ? (Int32?)null : (Int32?)command.Parameters["@pybatchid"].Value;
                _batchprocessid = Convert.IsDBNull(command.Parameters["@batchprocessid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@batchprocessid"].Value;
                _processname = Convert.IsDBNull(command.Parameters["@processname"].Value) ? null : (string)command.Parameters["@processname"].Value;
                _employeetype = Convert.IsDBNull(command.Parameters["@employeetype"].Value) ? null : (string)command.Parameters["@employeetype"].Value;
                _processendedon = Convert.IsDBNull(command.Parameters["@processendedon"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@processendedon"].Value;
                _companyid = Convert.IsDBNull(command.Parameters["@companyid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@companyid"].Value;
                _recordsprocessed = Convert.IsDBNull(command.Parameters["@recordsprocessed"].Value) ? (Int32?)null : (Int32?)command.Parameters["@recordsprocessed"].Value;
                _searchcriteria = Convert.IsDBNull(command.Parameters["@searchcriteria"].Value) ? null : (string)command.Parameters["@searchcriteria"].Value;
                _insertby = Convert.IsDBNull(command.Parameters["@insertby"].Value) ? (Int32?)null : (Int32?)command.Parameters["@insertby"].Value;
                _insertdate = Convert.IsDBNull(command.Parameters["@insertdate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@insertdate"].Value;
                _insertmachineinfo = Convert.IsDBNull(command.Parameters["@insertmachineinfo"].Value) ? null : (string)command.Parameters["@insertmachineinfo"].Value;
                _updateby = Convert.IsDBNull(command.Parameters["@updateby"].Value) ? (Int32?)null : (Int32?)command.Parameters["@updateby"].Value;
                _updatedate = Convert.IsDBNull(command.Parameters["@updatedate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@updatedate"].Value;
                _updatemachineinfo = Convert.IsDBNull(command.Parameters["@updatemachineinfo"].Value) ? null : (string)command.Parameters["@updatemachineinfo"].Value;


			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

        #region member properties

        public virtual Int32? pybatchid
        {
            get
            {
                return _pybatchid;
            }
            set
            {
                _pybatchid = value;
            
            }
        }
        public virtual Int32? batchprocessid
        {
            get
            {
                return _batchprocessid;
            }
            set
            {
                _batchprocessid = value;
            
            }
        }
        public virtual string processname
        {
            get
            {
                return _processname;
            }
            set
            {
                _processname = value;
                
            }
        }
        public virtual string employeetype
        {
            get
            {
                return _employeetype;
            }
            set
            {
                _employeetype = value;
                
            }
        }
        public virtual DateTime? processendedon
        {
            get
            {
                return _processendedon;
            }
            set
            {
                _processendedon = value;
                
            }
        }
        public virtual Int32? companyid
        {
            get
            {
                return _companyid;
            }
            set
            {
                _companyid = value;
               
            }
        }
        public virtual Int32? recordsprocessed
        {
            get
            {
                return _recordsprocessed;
            }
            set
            {
                _recordsprocessed = value;
                
            }
        }
        public virtual string searchcriteria
        {
            get
            {
                return _searchcriteria;
            }
            set
            {
                _searchcriteria = value;
                
            }
        }
        public virtual Int32? insertby
        {
            get
            {
                return _insertby;
            }
            set
            {
                _insertby = value;
                
            }
        }
        public virtual DateTime? insertdate
        {
            get
            {
                return _insertdate;
            }
            set
            {
                _insertdate = value;
                
            }
        }
        public virtual string insertmachineinfo
        {
            get
            {
                return _insertmachineinfo;
            }
            set
            {
                _insertmachineinfo = value;
              
            }
        }
        public virtual Int32? updateby
        {
            get
            {
                return _updateby;
            }
            set
            {
                _updateby = value;
                
            }
        }
        public virtual DateTime? updatedate
        {
            get
            {
                return _updatedate;
            }
            set
            {
                _updatedate = value;
                
            }
        }
        public virtual string updatemachineinfo
        {
            get
            {
                return _updatemachineinfo;
            }
            set
            {
                _updatemachineinfo = value;
                
            }
        }
        public virtual object Repository
        {
            get { return null; }
            set { }
        }
        #endregion
	}
}
