/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using C3WizardLayer.DataObjects.Interfaces;

namespace C3WizardLayer.DataObjects
{
	public partial class DLSECRole : C3WizardLayerConn_BaseData
	{
		#region member variables
		protected Int32? _roleId;
		protected string _role;
		protected string _description;
		protected Int32? _insertedBy;
		protected DateTime? _insertedOn;
		protected string _insertedMachineInfo;
		protected Int32? _updatedBy;
		protected DateTime? _updatedOn;
		protected string _updatedMachineInfo;
		protected bool? _isActive;
		protected string _deletable;
		#endregion

		#region class methods
		public DLSECRole()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table SECRole based on the primary key(s)
		///</Summary>
		///<returns>
		///DLSECRole
		///</returns>
		///<parameters>
		///Int32? roleId
		///</parameters>
		public static DLSECRole SelectOne(Int32? roleId)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_SelectOne]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("SECRole");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@RoleId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)roleId?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				DLSECRole retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DLSECRole();
					retObj._roleId					 = Convert.IsDBNull(dt.Rows[0]["RoleId"]) ? (Int32?)null : (Int32?)dt.Rows[0]["RoleId"];
					retObj._role					 = Convert.IsDBNull(dt.Rows[0]["Role"]) ? null : (string)dt.Rows[0]["Role"];
					retObj._description					 = Convert.IsDBNull(dt.Rows[0]["Description"]) ? null : (string)dt.Rows[0]["Description"];
					retObj._insertedBy					 = Convert.IsDBNull(dt.Rows[0]["InsertedBy"]) ? (Int32?)null : (Int32?)dt.Rows[0]["InsertedBy"];
					retObj._insertedOn					 = Convert.IsDBNull(dt.Rows[0]["InsertedOn"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["InsertedOn"];
					retObj._insertedMachineInfo					 = Convert.IsDBNull(dt.Rows[0]["InsertedMachineInfo"]) ? null : (string)dt.Rows[0]["InsertedMachineInfo"];
					retObj._updatedBy					 = Convert.IsDBNull(dt.Rows[0]["UpdatedBy"]) ? (Int32?)null : (Int32?)dt.Rows[0]["UpdatedBy"];
					retObj._updatedOn					 = Convert.IsDBNull(dt.Rows[0]["UpdatedOn"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["UpdatedOn"];
					retObj._updatedMachineInfo					 = Convert.IsDBNull(dt.Rows[0]["UpdatedMachineInfo"]) ? null : (string)dt.Rows[0]["UpdatedMachineInfo"];
					retObj._isActive					 = Convert.IsDBNull(dt.Rows[0]["IsActive"]) ? (bool?)null : (bool?)dt.Rows[0]["IsActive"];
					retObj._deletable					 = Convert.IsDBNull(dt.Rows[0]["Deletable"]) ? null : (string)dt.Rows[0]["Deletable"];
				}
				return retObj;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table SECRole based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_DeleteOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@RoleId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_roleId?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table SECRole
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_InsertOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@RoleId", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _roleId));
				command.Parameters.Add(new SqlParameter("@Role", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_role?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Description", SqlDbType.NVarChar, 255, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_description?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@InsertedBy", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_insertedBy?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@InsertedOn", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertedOn?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@InsertedMachineInfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertedMachineInfo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@UpdatedBy", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_updatedBy?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@UpdatedOn", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedOn?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@UpdatedMachineInfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedMachineInfo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@IsActive", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_isActive?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Deletable", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_deletable?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_roleId					 = Convert.IsDBNull(command.Parameters["@RoleId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@RoleId"].Value;
				_role					 = Convert.IsDBNull(command.Parameters["@Role"].Value) ? null : (string)command.Parameters["@Role"].Value;
				_description					 = Convert.IsDBNull(command.Parameters["@Description"].Value) ? null : (string)command.Parameters["@Description"].Value;
				_insertedBy					 = Convert.IsDBNull(command.Parameters["@InsertedBy"].Value) ? (Int32?)null : (Int32?)command.Parameters["@InsertedBy"].Value;
				_insertedOn					 = Convert.IsDBNull(command.Parameters["@InsertedOn"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@InsertedOn"].Value;
				_insertedMachineInfo					 = Convert.IsDBNull(command.Parameters["@InsertedMachineInfo"].Value) ? null : (string)command.Parameters["@InsertedMachineInfo"].Value;
				_updatedBy					 = Convert.IsDBNull(command.Parameters["@UpdatedBy"].Value) ? (Int32?)null : (Int32?)command.Parameters["@UpdatedBy"].Value;
				_updatedOn					 = Convert.IsDBNull(command.Parameters["@UpdatedOn"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@UpdatedOn"].Value;
				_updatedMachineInfo					 = Convert.IsDBNull(command.Parameters["@UpdatedMachineInfo"].Value) ? null : (string)command.Parameters["@UpdatedMachineInfo"].Value;
				_isActive					 = Convert.IsDBNull(command.Parameters["@IsActive"].Value) ? (bool?)null : (bool?)command.Parameters["@IsActive"].Value;
				_deletable					 = Convert.IsDBNull(command.Parameters["@Deletable"].Value) ? null : (string)command.Parameters["@Deletable"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table SECRole
		///</Summary>
		///<returns>
		///IList-DLSECRole.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DLSECRole> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_SelectAll]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("SECRole");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DLSECRole> objList = new List<DLSECRole>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DLSECRole retObj = new DLSECRole();
						retObj._roleId					 = Convert.IsDBNull(row["RoleId"]) ? (Int32?)null : (Int32?)row["RoleId"];
						retObj._role					 = Convert.IsDBNull(row["Role"]) ? null : (string)row["Role"];
						retObj._description					 = Convert.IsDBNull(row["Description"]) ? null : (string)row["Description"];
						retObj._insertedBy					 = Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"];
						retObj._insertedOn					 = Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"];
						retObj._insertedMachineInfo					 = Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"];
						retObj._updatedBy					 = Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"];
						retObj._updatedOn					 = Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"];
						retObj._updatedMachineInfo					 = Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"];
						retObj._isActive					 = Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"];
						retObj._deletable					 = Convert.IsDBNull(row["Deletable"]) ? null : (string)row["Deletable"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_SelectAllCount]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select specific fields of all rows using criteriaquery api
		///This method returns specific fields of all data rows in the table using criteriaquery apiSECRole
		///</Summary>
		///<returns>
		///IDictionary-string, IList-object..
		///</returns>
		///<parameters>
		///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_SelectAllByCriteriaProjection]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("SECRole");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				string fieldsField = GetProjections(listProjection);
				string whereClause = GetSelectionCriteria(listCriterion);
				string orderClause = GetSelectionOrder(listOrder);
				string skipClause = GetSelectionSkip(dataSkip);
				string takeClause = GetSelectionTake(dataTake);

				if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
					throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

				command.Parameters.Add(new SqlParameter("@FieldsField", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)fieldsField?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
				foreach (IDataProjection projection in listProjection)
				{
					IList<object> lst = new List<object>();
					dict.Add(projection.Member, lst);
					foreach (DataRow row in dt.Rows)
					{
						if (string.Compare(projection.Member, "RoleId", true) == 0) lst.Add(Convert.IsDBNull(row["RoleId"]) ? (Int32?)null : (Int32?)row["RoleId"]);
						if (string.Compare(projection.Member, "Role", true) == 0) lst.Add(Convert.IsDBNull(row["Role"]) ? null : (string)row["Role"]);
						if (string.Compare(projection.Member, "Description", true) == 0) lst.Add(Convert.IsDBNull(row["Description"]) ? null : (string)row["Description"]);
						if (string.Compare(projection.Member, "InsertedBy", true) == 0) lst.Add(Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"]);
						if (string.Compare(projection.Member, "InsertedOn", true) == 0) lst.Add(Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"]);
						if (string.Compare(projection.Member, "InsertedMachineInfo", true) == 0) lst.Add(Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"]);
						if (string.Compare(projection.Member, "UpdatedBy", true) == 0) lst.Add(Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"]);
						if (string.Compare(projection.Member, "UpdatedOn", true) == 0) lst.Add(Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"]);
						if (string.Compare(projection.Member, "UpdatedMachineInfo", true) == 0) lst.Add(Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"]);
						if (string.Compare(projection.Member, "IsActive", true) == 0) lst.Add(Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"]);
						if (string.Compare(projection.Member, "Deletable", true) == 0) lst.Add(Convert.IsDBNull(row["Deletable"]) ? null : (string)row["Deletable"]);
					}
				}
				return dict;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by filter criteria
		///This method returns all data rows in the table using criteriaquery api SECRole
		///</Summary>
		///<returns>
		///IList-DLSECRole.
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IList<DLSECRole> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_SelectAllByCriteria]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("SECRole");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				string whereClause = GetSelectionCriteria(listCriterion);
				string orderClause = GetSelectionOrder(listOrder);
				string skipClause = GetSelectionSkip(dataSkip);
				string takeClause = GetSelectionTake(dataTake);

				if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
					throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DLSECRole> objList = new List<DLSECRole>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DLSECRole retObj = new DLSECRole();
						retObj._roleId					 = Convert.IsDBNull(row["RoleId"]) ? (Int32?)null : (Int32?)row["RoleId"];
						retObj._role					 = Convert.IsDBNull(row["Role"]) ? null : (string)row["Role"];
						retObj._description					 = Convert.IsDBNull(row["Description"]) ? null : (string)row["Description"];
						retObj._insertedBy					 = Convert.IsDBNull(row["InsertedBy"]) ? (Int32?)null : (Int32?)row["InsertedBy"];
						retObj._insertedOn					 = Convert.IsDBNull(row["InsertedOn"]) ? (DateTime?)null : (DateTime?)row["InsertedOn"];
						retObj._insertedMachineInfo					 = Convert.IsDBNull(row["InsertedMachineInfo"]) ? null : (string)row["InsertedMachineInfo"];
						retObj._updatedBy					 = Convert.IsDBNull(row["UpdatedBy"]) ? (Int32?)null : (Int32?)row["UpdatedBy"];
						retObj._updatedOn					 = Convert.IsDBNull(row["UpdatedOn"]) ? (DateTime?)null : (DateTime?)row["UpdatedOn"];
						retObj._updatedMachineInfo					 = Convert.IsDBNull(row["UpdatedMachineInfo"]) ? null : (string)row["UpdatedMachineInfo"];
						retObj._isActive					 = Convert.IsDBNull(row["IsActive"]) ? (bool?)null : (bool?)row["IsActive"];
						retObj._deletable					 = Convert.IsDBNull(row["Deletable"]) ? null : (string)row["Deletable"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select count of all rows using criteriaquery api
		///This method returns all data rows in the table using criteriaquery api SECRole
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion
		///</parameters>
		public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_SelectAllByCriteriaCount]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				string whereClause = GetSelectionCriteria(listCriterion);
				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table SECRole based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprSECRole_UpdateOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@RoleId", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_roleId?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Role", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_role?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Description", SqlDbType.NVarChar, 255, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_description?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@InsertedBy", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_insertedBy?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@InsertedOn", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertedOn?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@InsertedMachineInfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertedMachineInfo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@UpdatedBy", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_updatedBy?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@UpdatedOn", SqlDbType.DateTime, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedOn?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@UpdatedMachineInfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedMachineInfo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@IsActive", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_isActive?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Deletable", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_deletable?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_roleId					 = Convert.IsDBNull(command.Parameters["@RoleId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@RoleId"].Value;
				_role					 = Convert.IsDBNull(command.Parameters["@Role"].Value) ? null : (string)command.Parameters["@Role"].Value;
				_description					 = Convert.IsDBNull(command.Parameters["@Description"].Value) ? null : (string)command.Parameters["@Description"].Value;
				_insertedBy					 = Convert.IsDBNull(command.Parameters["@InsertedBy"].Value) ? (Int32?)null : (Int32?)command.Parameters["@InsertedBy"].Value;
				_insertedOn					 = Convert.IsDBNull(command.Parameters["@InsertedOn"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@InsertedOn"].Value;
				_insertedMachineInfo					 = Convert.IsDBNull(command.Parameters["@InsertedMachineInfo"].Value) ? null : (string)command.Parameters["@InsertedMachineInfo"].Value;
				_updatedBy					 = Convert.IsDBNull(command.Parameters["@UpdatedBy"].Value) ? (Int32?)null : (Int32?)command.Parameters["@UpdatedBy"].Value;
				_updatedOn					 = Convert.IsDBNull(command.Parameters["@UpdatedOn"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@UpdatedOn"].Value;
				_updatedMachineInfo					 = Convert.IsDBNull(command.Parameters["@UpdatedMachineInfo"].Value) ? null : (string)command.Parameters["@UpdatedMachineInfo"].Value;
				_isActive					 = Convert.IsDBNull(command.Parameters["@IsActive"].Value) ? (bool?)null : (bool?)command.Parameters["@IsActive"].Value;
				_deletable					 = Convert.IsDBNull(command.Parameters["@Deletable"].Value) ? null : (string)command.Parameters["@Deletable"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? RoleId
		{
			get
			{
				return _roleId;
			}
			set
			{
				_roleId = value;
			}
		}

		public string Role
		{
			get
			{
				return _role;
			}
			set
			{
				_role = value;
			}
		}

		public string Description
		{
			get
			{
				return _description;
			}
			set
			{
				_description = value;
			}
		}

		public Int32? InsertedBy
		{
			get
			{
				return _insertedBy;
			}
			set
			{
				_insertedBy = value;
			}
		}

		public DateTime? InsertedOn
		{
			get
			{
				return _insertedOn;
			}
			set
			{
				_insertedOn = value;
			}
		}

		public string InsertedMachineInfo
		{
			get
			{
				return _insertedMachineInfo;
			}
			set
			{
				_insertedMachineInfo = value;
			}
		}

		public Int32? UpdatedBy
		{
			get
			{
				return _updatedBy;
			}
			set
			{
				_updatedBy = value;
			}
		}

		public DateTime? UpdatedOn
		{
			get
			{
				return _updatedOn;
			}
			set
			{
				_updatedOn = value;
			}
		}

		public string UpdatedMachineInfo
		{
			get
			{
				return _updatedMachineInfo;
			}
			set
			{
				_updatedMachineInfo = value;
			}
		}

		public bool? IsActive
		{
			get
			{
				return _isActive;
			}
			set
			{
				_isActive = value;
			}
		}

		public string Deletable
		{
			get
			{
				return _deletable;
			}
			set
			{
				_deletable = value;
			}
		}

		#endregion
	}
}
