/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using C3WizardLayer.DataObjects.Interfaces;

namespace C3WizardLayer.DataObjects
{
	public partial class DLPayrollProcessHeader : C3WizardLayerConn_BaseData
	{
		#region member variables
	    protected Int32? _pybatchid;

        protected string _payperiod;
        protected string _employeetype;
        protected DateTime? _payrolldate;
        protected DateTime? _lastpayrolldate;
        protected DateTime? _endofperioddate;

        protected Int32? _companyid;
        protected string _usedflag;

        protected DateTime? _startedon;
        protected DateTime? _endedon;
        protected Int32? _insertby;
		protected string _insertmachineinfo;
		protected Int32? _updateby;
		protected DateTime? _updatedate;
		protected string _updatemachineinfo;

		#endregion

		#region class methods
        public DLPayrollProcessHeader()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table MasterCompany based on the primary key(s)
		///</Summary>
		///<returns>
		///DLMasterCompany
		///</returns>
		///<parameters>
		///Int32? companyId
		///</parameters>
        public static DLPayrollProcessHeader SelectOne(Int32? pybatchid)
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_SelectOne]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

            DataTable dt = new DataTable("Payroll_Process_Header");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
                command.Parameters.Add(new SqlParameter("@pybatchid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)pybatchid ?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

                DLPayrollProcessHeader retObj = null;
				if(dt.Rows.Count > 0)
				{
                    
                    retObj = new DLPayrollProcessHeader();
                    retObj._pybatchid = Convert.IsDBNull(dt.Rows[0]["pybatchid"]) ? (Int32?)null : (Int32?)dt.Rows[0]["pybatchid"];
                    retObj._payperiod= Convert.IsDBNull(dt.Rows[0]["payperiod"]) ? null : (string)dt.Rows[0]["payperiod"];
                    retObj._employeetype= Convert.IsDBNull(dt.Rows[0]["employeetype"]) ? null : (string)dt.Rows[0]["employeetype"];
                    retObj._payrolldate	= Convert.IsDBNull(dt.Rows[0]["payrolldate"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["payrolldate"];
                    retObj._lastpayrolldate	= Convert.IsDBNull(dt.Rows[0]["lastpayrolldate"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["lastpayrolldate"];
                    retObj._endofperioddate	= Convert.IsDBNull(dt.Rows[0]["endofperioddate"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["endofperioddate"];
                    retObj._companyid= Convert.IsDBNull(dt.Rows[0]["companyid"]) ? (Int32?)null : (Int32?)dt.Rows[0]["companyid"];
                    retObj._endedon= Convert.IsDBNull(dt.Rows[0]["endedon"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["endedon"];
                    retObj._startedon	= Convert.IsDBNull(dt.Rows[0]["startedon"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["startedon"];
                    retObj._usedflag = Convert.IsDBNull(dt.Rows[0]["usedflag"]) ? null : (string)dt.Rows[0]["usedflag"];
                    retObj._insertby= Convert.IsDBNull(dt.Rows[0]["insertby"]) ? (Int32?)null : (Int32?)dt.Rows[0]["insertby"];
					retObj._insertmachineinfo= Convert.IsDBNull(dt.Rows[0]["insertmachineinfo"]) ? null : (string)dt.Rows[0]["insertmachineinfo"];
					retObj._updateby= Convert.IsDBNull(dt.Rows[0]["updateby"]) ? (Int32?)null : (Int32?)dt.Rows[0]["updateby"];
					retObj._updatedate= Convert.IsDBNull(dt.Rows[0]["updatedate"]) ? (DateTime?)null : (DateTime?)dt.Rows[0]["updatedate"];
					retObj._updatemachineinfo= Convert.IsDBNull(dt.Rows[0]["updatemachineinfo"]) ? null : (string)dt.Rows[0]["updatemachineinfo"];
				}
				return retObj;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table MasterCompany based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_DeleteOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
                command.Parameters.Add(new SqlParameter("@pybatchid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_pybatchid ?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table MasterCompany
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_InsertOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
               
				command.Parameters.Add(new SqlParameter("@pybatchid", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _pybatchid));
                command.Parameters.Add(new SqlParameter("@payperiod", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_payperiod?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@employeetype", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_employeetype?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@payrolldate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_payrolldate?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@lastpayrolldate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_lastpayrolldate?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@endofperioddate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_endofperioddate?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@companyid", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_companyid?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@endedon", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_endedon?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@startedon", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_startedon?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@usedflag", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_usedflag?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@insertby", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_insertby?? (object)DBNull.Value));				
				command.Parameters.Add(new SqlParameter("@insertmachineinfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertmachineinfo?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@updateby", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_updateby?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@updatedate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedate?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@updatemachineinfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatemachineinfo?? (object)DBNull.Value));
				command.ExecuteNonQuery();
                _pybatchid = Convert.IsDBNull(command.Parameters["@pybatchid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@pybatchid"].Value;
                _startedon = Convert.IsDBNull(command.Parameters["@startedon"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@startedon"].Value;
                _endedon = Convert.IsDBNull(command.Parameters["@endedon"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@endedon"].Value;
                _payperiod = Convert.IsDBNull(command.Parameters["@payperiod"].Value) ? null : (string)command.Parameters["@payperiod"].Value;
                _employeetype = Convert.IsDBNull(command.Parameters["@employeetype"].Value) ? null : (string)command.Parameters["@employeetype"].Value;
                _payrolldate = Convert.IsDBNull(command.Parameters["@payrolldate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@payrolldate"].Value;
                _lastpayrolldate = Convert.IsDBNull(command.Parameters["@lastpayrolldate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@lastpayrolldate"].Value;
                _endofperioddate = Convert.IsDBNull(command.Parameters["@endofperioddate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@endofperioddate"].Value;
                _companyid = Convert.IsDBNull(command.Parameters["@companyid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@companyid"].Value;
                _usedflag = Convert.IsDBNull(command.Parameters["@usedflag"].Value) ? null : (string)command.Parameters["@usedflag"].Value;
                _insertby = Convert.IsDBNull(command.Parameters["@insertby"].Value) ? (Int32?)null : (Int32?)command.Parameters["@insertby"].Value;
                _insertmachineinfo = Convert.IsDBNull(command.Parameters["@insertmachineinfo"].Value) ? null : (string)command.Parameters["@insertmachineinfo"].Value;
                _updateby = Convert.IsDBNull(command.Parameters["@updateby"].Value) ? (Int32?)null : (Int32?)command.Parameters["@updateby"].Value;
                _updatedate = Convert.IsDBNull(command.Parameters["@updatedate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@updatedate"].Value;
                _updatemachineinfo = Convert.IsDBNull(command.Parameters["@updatemachineinfo"].Value) ? null : (string)command.Parameters["@updatemachineinfo"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table MasterCompany
		///</Summary>
		///<returns>
		///IList-DLMasterCompany.
		///</returns>
		///<parameters>
		///
		///</parameters>
        public static IList<DLPayrollProcessHeader> SelectAll(int CompanyId)
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_SelectAll]";
            command.Parameters.Add(new SqlParameter("@CompanyId", SqlDbType.Int, 18, ParameterDirection.Input, false, 18, 0, "", DataRowVersion.Proposed, (object)CompanyId ?? (object)DBNull.Value));
            command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;
            DataTable dt = new DataTable("Payroll_Process_Header");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);
                List<DLPayrollProcessHeader> objList = new List<DLPayrollProcessHeader>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
                        DLPayrollProcessHeader retObj = new DLPayrollProcessHeader();
                        retObj._pybatchid = Convert.IsDBNull(row["pybatchid"]) ? (Int32?)null : (Int32?)row["pybatchid"];
                        retObj._payperiod = Convert.IsDBNull(row["payperiod"]) ? null : (string)row["payperiod"];
                        retObj._employeetype = Convert.IsDBNull(row["employeetype"]) ? null : (string)row["employeetype"];
                        retObj._payrolldate = Convert.IsDBNull(row["payrolldate"]) ? (DateTime?)null : (DateTime?)row["payrolldate"];
                        retObj._lastpayrolldate = Convert.IsDBNull(row["lastpayrolldate"]) ? (DateTime?)null : (DateTime?)row["lastpayrolldate"];
                        retObj._endofperioddate = Convert.IsDBNull(row["endofperioddate"]) ? (DateTime?)null : (DateTime?)row["endofperioddate"];
                        retObj._companyid = Convert.IsDBNull(row["companyid"]) ? (Int32?)null : (Int32?)row["companyid"];
                        retObj._endedon = Convert.IsDBNull(row["endedon"]) ? (DateTime?)null : (DateTime?)row["endedon"];
                        retObj._startedon = Convert.IsDBNull(row["startedon"]) ? (DateTime?)null : (DateTime?)row["startedon"];
                        retObj._usedflag = Convert.IsDBNull(row["usedflag"]) ? null : (string)row["usedflag"];
                        retObj._insertby = Convert.IsDBNull(row["insertby"]) ? (Int32?)null : (Int32?)row["insertby"];
                        retObj._insertmachineinfo = Convert.IsDBNull(row["insertmachineinfo"]) ? null : (string)row["insertmachineinfo"];
                        retObj._updateby = Convert.IsDBNull(row["updateby"]) ? (Int32?)null : (Int32?)row["updateby"];
                        retObj._updatedate = Convert.IsDBNull(row["updatedate"]) ? (DateTime?)null : (DateTime?)row["updatedate"];
                        retObj._updatemachineinfo = Convert.IsDBNull(row["updatemachineinfo"]) ? null : (string)row["updatemachineinfo"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}
		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_SelectAllCount]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;
			try
			{
				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

        ///<Summary>
        ///Select specific fields of all rows using criteriaquery api
        ///This method returns specific fields of all data rows in the table using criteriaquery apiMasterCompany
        ///</Summary>
        ///<returns>
        ///IDictionary-string, IList-object..
        ///</returns>
        ///<parameters>
        ///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
        ///</parameters>
        public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
        {
            SqlCommand command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_SelectAllByCriteriaProjection]";
            command.CommandType = CommandType.StoredProcedure;
            SqlConnection staticConnection = StaticSqlConnection;
            command.Connection = staticConnection;
            DataTable dt = new DataTable("Payroll_Process_Header");
            SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
            try
            {
                string fieldsField = GetProjections(listProjection);
                string whereClause = GetSelectionCriteria(listCriterion);
                string orderClause = GetSelectionOrder(listOrder);
                string skipClause = GetSelectionSkip(dataSkip);
                string takeClause = GetSelectionTake(dataTake);

                if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
                    throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");
                command.Parameters.Add(new SqlParameter("@FieldsField", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)fieldsField ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause ?? (object)DBNull.Value));
                if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
                sqlAdapter.Fill(dt);
                IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
                foreach (IDataProjection projection in listProjection)
                {
                    IList<object> lst = new List<object>();
                    dict.Add(projection.Member, lst);
                    foreach (DataRow row in dt.Rows)
                    {
                        if (string.Compare(projection.Member, "pybatchid", true) == 0) lst.Add(Convert.IsDBNull(row["pybatchid"]) ? (Int32?)null : (Int32?)row["pybatchid"]);
                        if (string.Compare(projection.Member, "payperiod", true) == 0) lst.Add(Convert.IsDBNull(row["payperiod"]) ? null : (string)row["payperiod"]);
                        if (string.Compare(projection.Member, "employeetype", true) == 0) lst.Add(Convert.IsDBNull(row["employeetype"]) ? null : (string)row["employeetype"]);
                        if (string.Compare(projection.Member, "startedon", true) == 0) lst.Add(Convert.IsDBNull(row["startedon"]) ? (DateTime?)null : (DateTime?)row["startedon"]);
                        if (string.Compare(projection.Member, "endedon", true) == 0) lst.Add(Convert.IsDBNull(row["endedon"]) ? (DateTime?)null : (DateTime?)row["endedon"]);
                        if (string.Compare(projection.Member, "payrolldate", true) == 0) lst.Add(Convert.IsDBNull(row["payrolldate"]) ? (DateTime?)null : (DateTime?)row["payrolldate"]);
                        if (string.Compare(projection.Member, "lastpayrolldate", true) == 0) lst.Add(Convert.IsDBNull(row["lastpayrolldate"]) ? (DateTime?)null : (DateTime?)row["lastpayrolldate"]);
                        if (string.Compare(projection.Member, "endofperioddate", true) == 0) lst.Add(Convert.IsDBNull(row["endofperioddate"]) ? (DateTime?)null : (DateTime?)row["endofperioddate"]);
                        if (string.Compare(projection.Member, "companyid", true) == 0) lst.Add(Convert.IsDBNull(row["companyid"]) ? (Int32?)null : (Int32?)row["companyid"]);
                        if (string.Compare(projection.Member, "usedflag", true) == 0) lst.Add(Convert.IsDBNull(row["usedflag"]) ? null : (string)row["usedflag"]);
                        if (string.Compare(projection.Member, "insertby", true) == 0) lst.Add(Convert.IsDBNull(row["insertby"]) ? (Int32?)null : (Int32?)row["insertby"]);
                        if (string.Compare(projection.Member, "insertmachineinfo", true) == 0) lst.Add(Convert.IsDBNull(row["insertmachineinfo"]) ? null : (string)row["insertmachineinfo"]);
                        if (string.Compare(projection.Member, "updateby", true) == 0) lst.Add(Convert.IsDBNull(row["updateby"]) ? (Int32?)null : (Int32?)row["updateby"]);
                        if (string.Compare(projection.Member, "updatedate", true) == 0) lst.Add(Convert.IsDBNull(row["updatedate"]) ? (DateTime?)null : (DateTime?)row["updatedate"]);
                        if (string.Compare(projection.Member, "updatemachineinfo", true) == 0) lst.Add(Convert.IsDBNull(row["updatemachineinfo"]) ? null : (string)row["updatemachineinfo"]);
                        
                    }
                }
                return dict;
            }
            catch
            {
                throw;
            }
            finally
            {
                staticConnection.Close();
                command.Dispose();
            }
        }
        ///<Summary>
        ///Select all rows by filter criteria
        ///This method returns all data rows in the table using criteriaquery api MasterCompany
        ///</Summary>
        ///<returns>
        ///IList-DLMasterCompany.
        ///</returns>
        ///<parameters>
        ///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
        ///</parameters>
        public static IList<DLPayrollProcessHeader> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
        {
            SqlCommand command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_SelectAllByCriteria]";
            command.CommandType = CommandType.StoredProcedure;
            SqlConnection staticConnection = StaticSqlConnection;
            command.Connection = staticConnection;

            DataTable dt = new DataTable("Payroll_Process_Header");
            SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
            try
            {
                string whereClause = GetSelectionCriteria(listCriterion);
                string orderClause = GetSelectionOrder(listOrder);
                string skipClause = GetSelectionSkip(dataSkip);
                string takeClause = GetSelectionTake(dataTake);

                if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
                    throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

                command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause ?? (object)DBNull.Value));

                if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
                sqlAdapter.Fill(dt);

                List<DLPayrollProcessHeader> objList = new List<DLPayrollProcessHeader>();
                if (dt.Rows.Count > 0)
                {
                    foreach (DataRow row in dt.Rows)
                    {
                        DLPayrollProcessHeader retObj = new DLPayrollProcessHeader();

                        retObj._pybatchid = Convert.IsDBNull(row["pybatchid"]) ? (Int32?)null : (Int32?)row["pybatchid"];
                        retObj._payperiod = Convert.IsDBNull(row["payperiod"]) ? null : (string)row["payperiod"];
                        retObj._employeetype = Convert.IsDBNull(row["employeetype"]) ? null : (string)row["employeetype"];
                        retObj._payrolldate = Convert.IsDBNull(row["payrolldate"]) ? (DateTime?)null : (DateTime?)row["payrolldate"];
                        retObj._lastpayrolldate = Convert.IsDBNull(row["lastpayrolldate"]) ? (DateTime?)null : (DateTime?)row["lastpayrolldate"];
                        retObj._endofperioddate = Convert.IsDBNull(row["endofperioddate"]) ? (DateTime?)null : (DateTime?)row["endofperioddate"];
                        retObj._companyid = Convert.IsDBNull(row["companyid"]) ? (Int32?)null : (Int32?)row["companyid"];
                        retObj._endedon = Convert.IsDBNull(row["endedon"]) ? (DateTime?)null : (DateTime?)row["endedon"];
                        retObj._startedon = Convert.IsDBNull(row["startedon"]) ? (DateTime?)null : (DateTime?)row["startedon"];
                        retObj._usedflag = Convert.IsDBNull(row["usedflag"]) ? null : (string)row["usedflag"];
                        retObj._insertby = Convert.IsDBNull(row["insertby"]) ? (Int32?)null : (Int32?)row["insertby"];
                        retObj._insertmachineinfo = Convert.IsDBNull(row["insertmachineinfo"]) ? null : (string)row["insertmachineinfo"];
                        retObj._updateby = Convert.IsDBNull(row["updateby"]) ? (Int32?)null : (Int32?)row["updateby"];
                        retObj._updatedate = Convert.IsDBNull(row["updatedate"]) ? (DateTime?)null : (DateTime?)row["updatedate"];
                        retObj._updatemachineinfo = Convert.IsDBNull(row["updatemachineinfo"]) ? null : (string)row["updatemachineinfo"];
                        objList.Add(retObj);
                    }
                }
                return objList;
            }
            catch
            {
                throw;
            }
            finally
            {
                staticConnection.Close();
                command.Dispose();
            }
        }

        ///<Summary>
        ///Select count of all rows using criteriaquery api
        ///This method returns all data rows in the table using criteriaquery api MasterCompany
        ///</Summary>
        ///<returns>
        ///Int32
        ///</returns>
        ///<parameters>
        ///IList<IDataCriterion> listCriterion
        ///</parameters>
        public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
        {
            SqlCommand command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_SelectAllByCriteriaCount]";
            command.CommandType = CommandType.StoredProcedure;
            SqlConnection staticConnection = StaticSqlConnection;
            command.Connection = staticConnection;

            try
            {
                string whereClause = GetSelectionCriteria(listCriterion);
                command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause ?? (object)DBNull.Value));

                if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
                Int32 retCount = (Int32)command.ExecuteScalar();

                return retCount;
            }
            catch
            {
                throw;
            }
            finally
            {
                staticConnection.Close();
                command.Dispose();
            }
        }

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table MasterCompany based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
            command.CommandText = "[dbo].[ctprPayroll_Process_Header_UpdateOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
                command.Parameters.Add(new SqlParameter("@pybatchid", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _pybatchid));
                command.Parameters.Add(new SqlParameter("@payperiod", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_payperiod ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@employeetype", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_employeetype ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@payrolldate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_payrolldate ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@lastpayrolldate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_lastpayrolldate ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@endofperioddate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_endofperioddate ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@companyid", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_companyid ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@endedon", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_endedon ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@startedon", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_startedon ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@usedflag", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_usedflag ?? (object)DBNull.Value));

                command.Parameters.Add(new SqlParameter("@insertby", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_insertby ?? (object)DBNull.Value));

                command.Parameters.Add(new SqlParameter("@insertmachineinfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_insertmachineinfo ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@updateby", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_updateby ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@updatedate", SqlDbType.SmallDateTime, 4, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatedate ?? (object)DBNull.Value));
                command.Parameters.Add(new SqlParameter("@updatemachineinfo", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_updatemachineinfo ?? (object)DBNull.Value));
				


				command.ExecuteNonQuery();

                _pybatchid = Convert.IsDBNull(command.Parameters["@pybatchid "].Value) ? (Int32?)null : (Int32?)command.Parameters["@pybatchid "].Value;
                _startedon = Convert.IsDBNull(command.Parameters["@startedon"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@startedon"].Value;
                _endedon = Convert.IsDBNull(command.Parameters["@endedon"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@endedon"].Value;
                _payperiod = Convert.IsDBNull(command.Parameters["@payperiod"].Value) ? null : (string)command.Parameters["@payperiod"].Value;
                _employeetype = Convert.IsDBNull(command.Parameters["@employeetype"].Value) ? null : (string)command.Parameters["@employeetype"].Value;
                _payrolldate = Convert.IsDBNull(command.Parameters["@payrolldate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@payrolldate"].Value;
                _lastpayrolldate = Convert.IsDBNull(command.Parameters["@lastpayrolldate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@lastpayrolldate"].Value;
                _endofperioddate = Convert.IsDBNull(command.Parameters["@endofperioddate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@endofperioddate"].Value;
                _companyid = Convert.IsDBNull(command.Parameters["@companyid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@companyid"].Value;
                _usedflag = Convert.IsDBNull(command.Parameters["@usedflag"].Value) ? null : (string)command.Parameters["@usedflag"].Value;
                _insertby = Convert.IsDBNull(command.Parameters["@insertby"].Value) ? (Int32?)null : (Int32?)command.Parameters["@insertby"].Value;
                _insertmachineinfo = Convert.IsDBNull(command.Parameters["@insertmachineinfo"].Value) ? null : (string)command.Parameters["@insertmachineinfo"].Value;
                _updateby = Convert.IsDBNull(command.Parameters["@updateby"].Value) ? (Int32?)null : (Int32?)command.Parameters["@updateby"].Value;
                _updatedate = Convert.IsDBNull(command.Parameters["@updatedate"].Value) ? (DateTime?)null : (DateTime?)command.Parameters["@updatedate"].Value;
                _updatemachineinfo = Convert.IsDBNull(command.Parameters["@updatemachineinfo"].Value) ? null : (string)command.Parameters["@updatemachineinfo"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

        #region member properties

        public virtual Int32? pybatchid
        {
            get
            {
                return _pybatchid;
            }
            set
            {
                _pybatchid = value;
            
            }
        }

        public virtual string payperiod
        {
            get
            {
                return _payperiod;
            }
            set
            {
                _payperiod = value;

            }
        }
        public virtual string employeetype
        {
            get
            {
                return _employeetype;
            }
            set
            {
                _employeetype = value;

            }
        }
        public virtual DateTime? payrolldate
        {
            get
            {
                return _payrolldate;
            }
            set
            {
                _payrolldate = value;

            }
        }

        public virtual DateTime? lastpayrolldate
        {
            get
            {
                return _lastpayrolldate;
            }
            set
            {
                _lastpayrolldate = value;

            }
        }

        public virtual DateTime? endofperioddate
        {
            get
            {
                return _endofperioddate;
            }
            set
            {
                _endofperioddate = value;

            }
        }

        public virtual Int32? companyid
        {
            get
            {
                return _companyid;
            }
            set
            {
                _companyid = value;

            }
        }
        public virtual DateTime? startedon
        {
            get
            {
                return _startedon;
            }
            set
            {
                _startedon = value;
                
            }
        }
        public virtual DateTime? endedon
        {
            get
            {
                return _endedon;
            }
            set
            {
                _endedon = value;
                
            }
        }

        public virtual string usedflag
        {
            get
            {
                return _usedflag;
            }
            set
            {
                _usedflag = value;

            }
        }

        
        
        public virtual Int32? insertby
        {
            get
            {
                return _insertby;
            }
            set
            {
                _insertby = value;
                
            }
        }

        public virtual string insertmachineinfo
        {
            get
            {
                return _insertmachineinfo;
            }
            set
            {
                _insertmachineinfo = value;
              
            }
        }

        public virtual Int32? updateby
        {
            get
            {
                return _updateby;
            }
            set
            {
                _updateby = value;
                
            }
        }

        public virtual DateTime? updatedate
        {
            get
            {
                return _updatedate;
            }
            set
            {
                _updatedate = value;
                
            }
        }

        public virtual string updatemachineinfo
        {
            get
            {
                return _updatemachineinfo;
            }
            set
            {
                _updatemachineinfo = value;
                
            }
        }

        public virtual object Repository
        {
            get { return null; }
            set { }
        }

        
        #endregion
	}
}
