/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using C3WizardLayer.DataObjects;
using C3WizardLayer.DataObjects.Interfaces;
using C3WizardLayer.BusinessObjects.Interfaces;

namespace C3WizardLayer.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BLDeductionsTaxTableDetails.
	///</Summary>
	public partial class BLDeductionsTaxTableDetails : C3WizardLayerConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _taxTabID;
		protected string _taxYear;
		protected string _dedCode;
		protected string _payPeriod;
		protected string _maritalStat;
		protected decimal? _overAmt;
		protected decimal? _baseAmt;
		protected decimal? _taxRate;
		protected Int32? _orderNo;
		protected DateTime? _startDate;
		protected DateTime? _endDate;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BLDeductionsTaxTableDetails()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 taxTabID
		///</parameters>
		public BLDeductionsTaxTableDetails(Int32 taxTabID)
		{
			try
			{
				DLDeductionsTaxTableDetails dlDeductionsTaxTableDetails = DLDeductionsTaxTableDetails.SelectOne(taxTabID);
				_taxTabID = dlDeductionsTaxTableDetails.TaxTabID;
				_taxYear = dlDeductionsTaxTableDetails.TaxYear;
				_dedCode = dlDeductionsTaxTableDetails.DedCode;
				_payPeriod = dlDeductionsTaxTableDetails.PayPeriod;
				_maritalStat = dlDeductionsTaxTableDetails.MaritalStat;
				_overAmt = dlDeductionsTaxTableDetails.OverAmt;
				_baseAmt = dlDeductionsTaxTableDetails.BaseAmt;
				_taxRate = dlDeductionsTaxTableDetails.TaxRate;
				_orderNo = dlDeductionsTaxTableDetails.OrderNo;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DLDeductionsTaxTableDetails
		///</parameters>
		protected internal BLDeductionsTaxTableDetails(DLDeductionsTaxTableDetails dlDeductionsTaxTableDetails)
		{
			try
			{
				_taxTabID = dlDeductionsTaxTableDetails.TaxTabID;
				_taxYear = dlDeductionsTaxTableDetails.TaxYear;
				_dedCode = dlDeductionsTaxTableDetails.DedCode;
				_payPeriod = dlDeductionsTaxTableDetails.PayPeriod;
				_maritalStat = dlDeductionsTaxTableDetails.MaritalStat;
				_overAmt = dlDeductionsTaxTableDetails.OverAmt;
				_baseAmt = dlDeductionsTaxTableDetails.BaseAmt;
				_taxRate = dlDeductionsTaxTableDetails.TaxRate;
				_orderNo = dlDeductionsTaxTableDetails.OrderNo;
				_startDate = dlDeductionsTaxTableDetails.StartDate;
				_endDate = dlDeductionsTaxTableDetails.EndDate;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new DeductionsTaxTableDetails record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DLDeductionsTaxTableDetails dlDeductionsTaxTableDetails = new DLDeductionsTaxTableDetails();
			RegisterDataObject(dlDeductionsTaxTableDetails);
			BeginTransaction("savenewBLDeductionsTaxTableD9728");
			try
			{
				dlDeductionsTaxTableDetails.TaxYear = _taxYear;
				dlDeductionsTaxTableDetails.DedCode = _dedCode;
				dlDeductionsTaxTableDetails.PayPeriod = _payPeriod;
				dlDeductionsTaxTableDetails.MaritalStat = _maritalStat;
				dlDeductionsTaxTableDetails.OverAmt = _overAmt;
				dlDeductionsTaxTableDetails.BaseAmt = _baseAmt;
				dlDeductionsTaxTableDetails.TaxRate = _taxRate;
				dlDeductionsTaxTableDetails.OrderNo = _orderNo;
				dlDeductionsTaxTableDetails.Insert();
				CommitTransaction();
				
				_taxTabID = dlDeductionsTaxTableDetails.TaxTabID;
				_taxYear = dlDeductionsTaxTableDetails.TaxYear;
				_dedCode = dlDeductionsTaxTableDetails.DedCode;
				_payPeriod = dlDeductionsTaxTableDetails.PayPeriod;
				_maritalStat = dlDeductionsTaxTableDetails.MaritalStat;
				_overAmt = dlDeductionsTaxTableDetails.OverAmt;
				_baseAmt = dlDeductionsTaxTableDetails.BaseAmt;
				_taxRate = dlDeductionsTaxTableDetails.TaxRate;
				_orderNo = dlDeductionsTaxTableDetails.OrderNo;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBLDeductionsTaxTableD9728");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one DeductionsTaxTableDetails record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BLDeductionsTaxTableDetails
		///</parameters>
		public virtual void Update()
		{
			DLDeductionsTaxTableDetails dlDeductionsTaxTableDetails = new DLDeductionsTaxTableDetails();
			RegisterDataObject(dlDeductionsTaxTableDetails);
			BeginTransaction("updateBLDeductionsTaxTableDe5850");
			try
			{
				dlDeductionsTaxTableDetails.TaxTabID = _taxTabID;
				dlDeductionsTaxTableDetails.TaxYear = _taxYear;
				dlDeductionsTaxTableDetails.DedCode = _dedCode;
				dlDeductionsTaxTableDetails.PayPeriod = _payPeriod;
				dlDeductionsTaxTableDetails.MaritalStat = _maritalStat;
				dlDeductionsTaxTableDetails.OverAmt = _overAmt;
				dlDeductionsTaxTableDetails.BaseAmt = _baseAmt;
				dlDeductionsTaxTableDetails.TaxRate = _taxRate;
				dlDeductionsTaxTableDetails.OrderNo = _orderNo;
				dlDeductionsTaxTableDetails.Update();
				CommitTransaction();
				
				_taxTabID = dlDeductionsTaxTableDetails.TaxTabID;
				_taxYear = dlDeductionsTaxTableDetails.TaxYear;
				_dedCode = dlDeductionsTaxTableDetails.DedCode;
				_payPeriod = dlDeductionsTaxTableDetails.PayPeriod;
				_maritalStat = dlDeductionsTaxTableDetails.MaritalStat;
				_overAmt = dlDeductionsTaxTableDetails.OverAmt;
				_baseAmt = dlDeductionsTaxTableDetails.BaseAmt;
				_taxRate = dlDeductionsTaxTableDetails.TaxRate;
				_orderNo = dlDeductionsTaxTableDetails.OrderNo;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBLDeductionsTaxTableDe5850");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one DeductionsTaxTableDetails record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DLDeductionsTaxTableDetails dlDeductionsTaxTableDetails = new DLDeductionsTaxTableDetails();
			RegisterDataObject(dlDeductionsTaxTableDetails);
			BeginTransaction("deleteBLDeductionsTaxTableDe6298");
			try
			{
				dlDeductionsTaxTableDetails.TaxTabID = _taxTabID;
				dlDeductionsTaxTableDetails.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBLDeductionsTaxTableDe6298");
				throw;
			}
		}
		
		///<Summary>
		///DeductionsTaxTableDetailsCollection
		///This method returns the collection of BLDeductionsTaxTableDetails objects
		///</Summary>
		///<returns>
		///List[BLDeductionsTaxTableDetails]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BLDeductionsTaxTableDetails> DeductionsTaxTableDetailsCollection()
		{
			try
			{
				IList<BLDeductionsTaxTableDetails> blDeductionsTaxTableDetailsCollection = new List<BLDeductionsTaxTableDetails>();
				IList<DLDeductionsTaxTableDetails> dlDeductionsTaxTableDetailsCollection = DLDeductionsTaxTableDetails.SelectAll();
			
				foreach(DLDeductionsTaxTableDetails dlDeductionsTaxTableDetails in dlDeductionsTaxTableDetailsCollection)
					blDeductionsTaxTableDetailsCollection.Add(new BLDeductionsTaxTableDetails(dlDeductionsTaxTableDetails));
			
				return blDeductionsTaxTableDetailsCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///DeductionsTaxTableDetailsCollectionCount
		///This method returns the collection count of BLDeductionsTaxTableDetails objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 DeductionsTaxTableDetailsCollectionCount()
		{
			try
			{
				Int32 objCount = DLDeductionsTaxTableDetails.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BLDeductionsTaxTableDetails>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DLDeductionsTaxTableDetails.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///DeductionsTaxTableDetailsCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BLDeductionsTaxTableDetails objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> blDeductionsTaxTableDetailsCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DLDeductionsTaxTableDetails> dlDeductionsTaxTableDetailsCollection = DLDeductionsTaxTableDetails.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DLDeductionsTaxTableDetails resdlDeductionsTaxTableDetails in dlDeductionsTaxTableDetailsCollection)
					blDeductionsTaxTableDetailsCollection.Add((T)(object)new BLDeductionsTaxTableDetails(resdlDeductionsTaxTableDetails));
			
				return blDeductionsTaxTableDetailsCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///DeductionsTaxTableDetailsCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BLDeductionsTaxTableDetails objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DLDeductionsTaxTableDetails.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? TaxTabID
		{
			get
			{
				 return _taxTabID;
			}
			set
			{
				_taxTabID = value;
				_isDirty = true;
			}
		}
		
		public virtual string TaxYear
		{
			get
			{
				 return _taxYear;
			}
			set
			{
				_taxYear = value;
				_isDirty = true;
			}
		}
		
		public virtual string DedCode
		{
			get
			{
				 return _dedCode;
			}
			set
			{
				_dedCode = value;
				_isDirty = true;
			}
		}
		
		public virtual string PayPeriod
		{
			get
			{
				 return _payPeriod;
			}
			set
			{
				_payPeriod = value;
				_isDirty = true;
			}
		}
		
		public virtual string MaritalStat
		{
			get
			{
				 return _maritalStat;
			}
			set
			{
				_maritalStat = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? OverAmt
		{
			get
			{
				 return _overAmt;
			}
			set
			{
				_overAmt = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? BaseAmt
		{
			get
			{
				 return _baseAmt;
			}
			set
			{
				_baseAmt = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? TaxRate
		{
			get
			{
				 return _taxRate;
			}
			set
			{
				_taxRate = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? OrderNo
		{
			get
			{
				 return _orderNo;
			}
			set
			{
				_orderNo = value;
				_isDirty = true;
			}
		}
    public virtual DateTime? StartDate
    {
      get
      {
        return _startDate;
      }
      set
      {
        _startDate = value;
        _isDirty = true;
      }
    }
    public virtual DateTime? EndDate
    {
      get
      {
        return _endDate;
      }
      set
      {
        _endDate = value;
        _isDirty = true;
      }
    }

    public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
