/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:27 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using C3WizardLayer.DataObjects.Interfaces;

namespace C3WizardLayer.DataObjects
{
	public partial class DLDecemberBonusSetting : C3WizardLayerConn_BaseData
	{
        #region member variables
        protected Int32? _DBSId;
        protected Int32? _CompanyId;
        protected bool? _isexemptedLevy;
        protected bool? _isexemptedEmployerLevy;
        protected bool? _isexemptedSeverance;
        protected bool? _isexemptedsocialsecurity;
        protected Int32? _insertedBy;
        protected DateTime? _insertedOn;
        protected string _insertedMachineInfo;
        protected Int32? _updatedBy;
        protected DateTime? _updatedOn;
        protected string _updatedMachineInfo;
        protected string _deletable;
        protected bool _isDirty = false;
        #endregion

        #region class methods
        public DLDecemberBonusSetting()
		{
		}
		public virtual void Insert()
		{

		}
		public static IList<DLDecemberBonusSetting> SelectAll()
		{
            return null;
		}
		public static Int32 SelectAllCount()
		{
            return 0;
		}
        
	
		public virtual void Update()
		{
			
		}

        #endregion

        #region member properties
        public virtual Int32? DBSId
        {
            get
            {
                return _DBSId;
            }
            set
            {
                _DBSId = value;
            }
        }
        public virtual bool? IsexemptedLevy
        {
            get
            {
                return _isexemptedLevy;
            }
            set
            {
                _isexemptedLevy = value;
            }
        }
        public virtual bool? IsexemptedEmployerLevy
        {
            get
            {
                return _isexemptedEmployerLevy;
            }
            set
            {
                _isexemptedEmployerLevy = value;
            }
        }
        public virtual bool? IsexemptedSeverance
        {
            get
            {
                return _isexemptedSeverance;
            }
            set
            {
                _isexemptedSeverance = value;
            }
        }
        public virtual bool? Isexemptedsocialsecurity
        {
            get
            {
                return _isexemptedsocialsecurity;
            }
            set
            {
                _isexemptedsocialsecurity = value;
            }
        }
		public Int32? InsertedBy
		{
			get
			{
				return _insertedBy;
			}
			set
			{
				_insertedBy = value;
			}
		}

		public DateTime? InsertedOn
		{
			get
			{
				return _insertedOn;
			}
			set
			{
				_insertedOn = value;
			}
		}

		public string InsertedMachineInfo
		{
			get
			{
				return _insertedMachineInfo;
			}
			set
			{
				_insertedMachineInfo = value;
			}
		}

		public Int32? UpdatedBy
		{
			get
			{
				return _updatedBy;
			}
			set
			{
				_updatedBy = value;
			}
		}

		public DateTime? UpdatedOn
		{
			get
			{
				return _updatedOn;
			}
			set
			{
				_updatedOn = value;
			}
		}

		public string UpdatedMachineInfo
		{
			get
			{
				return _updatedMachineInfo;
			}
			set
			{
				_updatedMachineInfo = value;
			}
		}

		public string Deletable
		{
			get
			{
				return _deletable;
			}
			set
			{
				_deletable = value;
			}
		}

		#endregion
	}
}
