/*************************************************************
** Class generated by CodeTrigger, Version 5.1.0.2
** This class was generated on 2/4/2018 3:12:26 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using C3WizardLayer.DataObjects.Interfaces;

namespace C3WizardLayer.DataObjects
{
	public partial class DLDeductionsTaxTableHeader : C3WizardLayerConn_BaseData
	{
		#region member variables
		protected Int32? _taxTabHID;
		protected string _taxYear;
		protected string _dedCode;
		protected decimal? _weekAllow;
		protected decimal? _biweekAllow;
		protected decimal? _smonthAllow;
		protected decimal? _monthAllow;
		protected decimal? _quarterAllow;
		protected decimal? _syearAllow;
		protected decimal? _yearAllow;
		protected decimal? _miscAllow;
		protected decimal? _hRSWeekAllow;
		protected decimal? _hRSBiweekAllow;
		protected decimal? _hRSSmonthAllow;
		protected decimal? _hRSMonthAllow;
		protected decimal? _hRSQuarterAllow;
		protected decimal? _hRSSyearAllow;
		protected decimal? _hRSYearAllow;
		protected decimal? _hRSMiscAllow;
		protected string _allowOrLimit;
		#endregion

		#region class methods
		public DLDeductionsTaxTableHeader()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table Deductions_Tax_Table_Header based on the primary key(s)
		///</Summary>
		///<returns>
		///DLDeductionsTaxTableHeader
		///</returns>
		///<parameters>
		///Int32? taxTabHID
		///</parameters>
		public static DLDeductionsTaxTableHeader SelectOne(Int32? taxTabHID)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_SelectOne]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Deductions_Tax_Table_Header");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@TaxTabHID", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)taxTabHID?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				DLDeductionsTaxTableHeader retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DLDeductionsTaxTableHeader();
					retObj._taxTabHID					 = Convert.IsDBNull(dt.Rows[0]["TaxTabHID"]) ? (Int32?)null : (Int32?)dt.Rows[0]["TaxTabHID"];
					retObj._taxYear					 = Convert.IsDBNull(dt.Rows[0]["Tax_Year"]) ? null : (string)dt.Rows[0]["Tax_Year"];
					retObj._dedCode					 = Convert.IsDBNull(dt.Rows[0]["Ded_Code"]) ? null : (string)dt.Rows[0]["Ded_Code"];
					retObj._weekAllow					 = Convert.IsDBNull(dt.Rows[0]["Week_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["Week_Allow"];
					retObj._biweekAllow					 = Convert.IsDBNull(dt.Rows[0]["Biweek_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["Biweek_Allow"];
					retObj._smonthAllow					 = Convert.IsDBNull(dt.Rows[0]["Smonth_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["Smonth_Allow"];
					retObj._monthAllow					 = Convert.IsDBNull(dt.Rows[0]["Month_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["Month_Allow"];
					retObj._quarterAllow					 = Convert.IsDBNull(dt.Rows[0]["Quarter_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["Quarter_Allow"];
					retObj._syearAllow					 = Convert.IsDBNull(dt.Rows[0]["Syear_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["Syear_Allow"];
					retObj._yearAllow					 = Convert.IsDBNull(dt.Rows[0]["Year_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["Year_Allow"];
					retObj._miscAllow					 = Convert.IsDBNull(dt.Rows[0]["Misc_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["Misc_Allow"];
					retObj._hRSWeekAllow					 = Convert.IsDBNull(dt.Rows[0]["HRS_Week_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["HRS_Week_Allow"];
					retObj._hRSBiweekAllow					 = Convert.IsDBNull(dt.Rows[0]["HRS_Biweek_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["HRS_Biweek_Allow"];
					retObj._hRSSmonthAllow					 = Convert.IsDBNull(dt.Rows[0]["HRS_Smonth_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["HRS_Smonth_Allow"];
					retObj._hRSMonthAllow					 = Convert.IsDBNull(dt.Rows[0]["HRS_Month_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["HRS_Month_Allow"];
					retObj._hRSQuarterAllow					 = Convert.IsDBNull(dt.Rows[0]["HRS_Quarter_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["HRS_Quarter_Allow"];
					retObj._hRSSyearAllow					 = Convert.IsDBNull(dt.Rows[0]["HRS_Syear_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["HRS_Syear_Allow"];
					retObj._hRSYearAllow					 = Convert.IsDBNull(dt.Rows[0]["HRS_Year_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["HRS_Year_Allow"];
					retObj._hRSMiscAllow					 = Convert.IsDBNull(dt.Rows[0]["HRS_Misc_Allow"]) ? (decimal?)null : (decimal?)dt.Rows[0]["HRS_Misc_Allow"];
					retObj._allowOrLimit					 = Convert.IsDBNull(dt.Rows[0]["Allow_or_Limit"]) ? null : (string)dt.Rows[0]["Allow_or_Limit"];
				}
				return retObj;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table Deductions_Tax_Table_Header based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_DeleteOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@TaxTabHID", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_taxTabHID?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table Deductions_Tax_Table_Header
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_InsertOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@TaxTabHID", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _taxTabHID));
				command.Parameters.Add(new SqlParameter("@Tax_Year", SqlDbType.NVarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_taxYear?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Ded_Code", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_dedCode?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Week_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_weekAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Biweek_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_biweekAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Smonth_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_smonthAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Month_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_monthAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Quarter_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_quarterAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Syear_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_syearAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Year_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_yearAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Misc_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_miscAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Week_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSWeekAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Biweek_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSBiweekAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Smonth_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSSmonthAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Month_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSMonthAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Quarter_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSQuarterAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Syear_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSSyearAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Year_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSYearAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Misc_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSMiscAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Allow_or_Limit", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_allowOrLimit?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_taxTabHID					 = Convert.IsDBNull(command.Parameters["@TaxTabHID"].Value) ? (Int32?)null : (Int32?)command.Parameters["@TaxTabHID"].Value;
				_taxYear					 = Convert.IsDBNull(command.Parameters["@Tax_Year"].Value) ? null : (string)command.Parameters["@Tax_Year"].Value;
				_dedCode					 = Convert.IsDBNull(command.Parameters["@Ded_Code"].Value) ? null : (string)command.Parameters["@Ded_Code"].Value;
				_weekAllow					 = Convert.IsDBNull(command.Parameters["@Week_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Week_Allow"].Value;
				_biweekAllow					 = Convert.IsDBNull(command.Parameters["@Biweek_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Biweek_Allow"].Value;
				_smonthAllow					 = Convert.IsDBNull(command.Parameters["@Smonth_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Smonth_Allow"].Value;
				_monthAllow					 = Convert.IsDBNull(command.Parameters["@Month_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Month_Allow"].Value;
				_quarterAllow					 = Convert.IsDBNull(command.Parameters["@Quarter_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Quarter_Allow"].Value;
				_syearAllow					 = Convert.IsDBNull(command.Parameters["@Syear_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Syear_Allow"].Value;
				_yearAllow					 = Convert.IsDBNull(command.Parameters["@Year_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Year_Allow"].Value;
				_miscAllow					 = Convert.IsDBNull(command.Parameters["@Misc_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Misc_Allow"].Value;
				_hRSWeekAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Week_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Week_Allow"].Value;
				_hRSBiweekAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Biweek_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Biweek_Allow"].Value;
				_hRSSmonthAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Smonth_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Smonth_Allow"].Value;
				_hRSMonthAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Month_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Month_Allow"].Value;
				_hRSQuarterAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Quarter_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Quarter_Allow"].Value;
				_hRSSyearAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Syear_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Syear_Allow"].Value;
				_hRSYearAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Year_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Year_Allow"].Value;
				_hRSMiscAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Misc_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Misc_Allow"].Value;
				_allowOrLimit					 = Convert.IsDBNull(command.Parameters["@Allow_or_Limit"].Value) ? null : (string)command.Parameters["@Allow_or_Limit"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table Deductions_Tax_Table_Header
		///</Summary>
		///<returns>
		///IList-DLDeductionsTaxTableHeader.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DLDeductionsTaxTableHeader> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_SelectAll]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Deductions_Tax_Table_Header");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DLDeductionsTaxTableHeader> objList = new List<DLDeductionsTaxTableHeader>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DLDeductionsTaxTableHeader retObj = new DLDeductionsTaxTableHeader();
						retObj._taxTabHID					 = Convert.IsDBNull(row["TaxTabHID"]) ? (Int32?)null : (Int32?)row["TaxTabHID"];
						retObj._taxYear					 = Convert.IsDBNull(row["Tax_Year"]) ? null : (string)row["Tax_Year"];
						retObj._dedCode					 = Convert.IsDBNull(row["Ded_Code"]) ? null : (string)row["Ded_Code"];
						retObj._weekAllow					 = Convert.IsDBNull(row["Week_Allow"]) ? (decimal?)null : (decimal?)row["Week_Allow"];
						retObj._biweekAllow					 = Convert.IsDBNull(row["Biweek_Allow"]) ? (decimal?)null : (decimal?)row["Biweek_Allow"];
						retObj._smonthAllow					 = Convert.IsDBNull(row["Smonth_Allow"]) ? (decimal?)null : (decimal?)row["Smonth_Allow"];
						retObj._monthAllow					 = Convert.IsDBNull(row["Month_Allow"]) ? (decimal?)null : (decimal?)row["Month_Allow"];
						retObj._quarterAllow					 = Convert.IsDBNull(row["Quarter_Allow"]) ? (decimal?)null : (decimal?)row["Quarter_Allow"];
						retObj._syearAllow					 = Convert.IsDBNull(row["Syear_Allow"]) ? (decimal?)null : (decimal?)row["Syear_Allow"];
						retObj._yearAllow					 = Convert.IsDBNull(row["Year_Allow"]) ? (decimal?)null : (decimal?)row["Year_Allow"];
						retObj._miscAllow					 = Convert.IsDBNull(row["Misc_Allow"]) ? (decimal?)null : (decimal?)row["Misc_Allow"];
						retObj._hRSWeekAllow					 = Convert.IsDBNull(row["HRS_Week_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Week_Allow"];
						retObj._hRSBiweekAllow					 = Convert.IsDBNull(row["HRS_Biweek_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Biweek_Allow"];
						retObj._hRSSmonthAllow					 = Convert.IsDBNull(row["HRS_Smonth_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Smonth_Allow"];
						retObj._hRSMonthAllow					 = Convert.IsDBNull(row["HRS_Month_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Month_Allow"];
						retObj._hRSQuarterAllow					 = Convert.IsDBNull(row["HRS_Quarter_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Quarter_Allow"];
						retObj._hRSSyearAllow					 = Convert.IsDBNull(row["HRS_Syear_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Syear_Allow"];
						retObj._hRSYearAllow					 = Convert.IsDBNull(row["HRS_Year_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Year_Allow"];
						retObj._hRSMiscAllow					 = Convert.IsDBNull(row["HRS_Misc_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Misc_Allow"];
						retObj._allowOrLimit					 = Convert.IsDBNull(row["Allow_or_Limit"]) ? null : (string)row["Allow_or_Limit"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_SelectAllCount]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select specific fields of all rows using criteriaquery api
		///This method returns specific fields of all data rows in the table using criteriaquery apiDeductions_Tax_Table_Header
		///</Summary>
		///<returns>
		///IDictionary-string, IList-object..
		///</returns>
		///<parameters>
		///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_SelectAllByCriteriaProjection]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Deductions_Tax_Table_Header");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				string fieldsField = GetProjections(listProjection);
				string whereClause = GetSelectionCriteria(listCriterion);
				string orderClause = GetSelectionOrder(listOrder);
				string skipClause = GetSelectionSkip(dataSkip);
				string takeClause = GetSelectionTake(dataTake);

				if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
					throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

				command.Parameters.Add(new SqlParameter("@FieldsField", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)fieldsField?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
				foreach (IDataProjection projection in listProjection)
				{
					IList<object> lst = new List<object>();
					dict.Add(projection.Member, lst);
					foreach (DataRow row in dt.Rows)
					{
						if (string.Compare(projection.Member, "TaxTabHID", true) == 0) lst.Add(Convert.IsDBNull(row["TaxTabHID"]) ? (Int32?)null : (Int32?)row["TaxTabHID"]);
						if (string.Compare(projection.Member, "Tax_Year", true) == 0) lst.Add(Convert.IsDBNull(row["Tax_Year"]) ? null : (string)row["Tax_Year"]);
						if (string.Compare(projection.Member, "Ded_Code", true) == 0) lst.Add(Convert.IsDBNull(row["Ded_Code"]) ? null : (string)row["Ded_Code"]);
						if (string.Compare(projection.Member, "Week_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["Week_Allow"]) ? (decimal?)null : (decimal?)row["Week_Allow"]);
						if (string.Compare(projection.Member, "Biweek_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["Biweek_Allow"]) ? (decimal?)null : (decimal?)row["Biweek_Allow"]);
						if (string.Compare(projection.Member, "Smonth_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["Smonth_Allow"]) ? (decimal?)null : (decimal?)row["Smonth_Allow"]);
						if (string.Compare(projection.Member, "Month_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["Month_Allow"]) ? (decimal?)null : (decimal?)row["Month_Allow"]);
						if (string.Compare(projection.Member, "Quarter_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["Quarter_Allow"]) ? (decimal?)null : (decimal?)row["Quarter_Allow"]);
						if (string.Compare(projection.Member, "Syear_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["Syear_Allow"]) ? (decimal?)null : (decimal?)row["Syear_Allow"]);
						if (string.Compare(projection.Member, "Year_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["Year_Allow"]) ? (decimal?)null : (decimal?)row["Year_Allow"]);
						if (string.Compare(projection.Member, "Misc_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["Misc_Allow"]) ? (decimal?)null : (decimal?)row["Misc_Allow"]);
						if (string.Compare(projection.Member, "HRS_Week_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["HRS_Week_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Week_Allow"]);
						if (string.Compare(projection.Member, "HRS_Biweek_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["HRS_Biweek_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Biweek_Allow"]);
						if (string.Compare(projection.Member, "HRS_Smonth_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["HRS_Smonth_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Smonth_Allow"]);
						if (string.Compare(projection.Member, "HRS_Month_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["HRS_Month_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Month_Allow"]);
						if (string.Compare(projection.Member, "HRS_Quarter_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["HRS_Quarter_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Quarter_Allow"]);
						if (string.Compare(projection.Member, "HRS_Syear_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["HRS_Syear_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Syear_Allow"]);
						if (string.Compare(projection.Member, "HRS_Year_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["HRS_Year_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Year_Allow"]);
						if (string.Compare(projection.Member, "HRS_Misc_Allow", true) == 0) lst.Add(Convert.IsDBNull(row["HRS_Misc_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Misc_Allow"]);
						if (string.Compare(projection.Member, "Allow_or_Limit", true) == 0) lst.Add(Convert.IsDBNull(row["Allow_or_Limit"]) ? null : (string)row["Allow_or_Limit"]);
					}
				}
				return dict;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by filter criteria
		///This method returns all data rows in the table using criteriaquery api Deductions_Tax_Table_Header
		///</Summary>
		///<returns>
		///IList-DLDeductionsTaxTableHeader.
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IList<DLDeductionsTaxTableHeader> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_SelectAllByCriteria]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Deductions_Tax_Table_Header");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				string whereClause = GetSelectionCriteria(listCriterion);
				string orderClause = GetSelectionOrder(listOrder);
				string skipClause = GetSelectionSkip(dataSkip);
				string takeClause = GetSelectionTake(dataTake);

				if ((orderClause == "") && ((skipClause != "") || (takeClause != "")))
					throw new Exception("Invalid query: Using 'Take' or 'Skip' requires an OrderBy clause");

				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@OrderClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)orderClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@SkipClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)skipClause?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@TakeClause", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)takeClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DLDeductionsTaxTableHeader> objList = new List<DLDeductionsTaxTableHeader>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DLDeductionsTaxTableHeader retObj = new DLDeductionsTaxTableHeader();
						retObj._taxTabHID					 = Convert.IsDBNull(row["TaxTabHID"]) ? (Int32?)null : (Int32?)row["TaxTabHID"];
						retObj._taxYear					 = Convert.IsDBNull(row["Tax_Year"]) ? null : (string)row["Tax_Year"];
						retObj._dedCode					 = Convert.IsDBNull(row["Ded_Code"]) ? null : (string)row["Ded_Code"];
						retObj._weekAllow					 = Convert.IsDBNull(row["Week_Allow"]) ? (decimal?)null : (decimal?)row["Week_Allow"];
						retObj._biweekAllow					 = Convert.IsDBNull(row["Biweek_Allow"]) ? (decimal?)null : (decimal?)row["Biweek_Allow"];
						retObj._smonthAllow					 = Convert.IsDBNull(row["Smonth_Allow"]) ? (decimal?)null : (decimal?)row["Smonth_Allow"];
						retObj._monthAllow					 = Convert.IsDBNull(row["Month_Allow"]) ? (decimal?)null : (decimal?)row["Month_Allow"];
						retObj._quarterAllow					 = Convert.IsDBNull(row["Quarter_Allow"]) ? (decimal?)null : (decimal?)row["Quarter_Allow"];
						retObj._syearAllow					 = Convert.IsDBNull(row["Syear_Allow"]) ? (decimal?)null : (decimal?)row["Syear_Allow"];
						retObj._yearAllow					 = Convert.IsDBNull(row["Year_Allow"]) ? (decimal?)null : (decimal?)row["Year_Allow"];
						retObj._miscAllow					 = Convert.IsDBNull(row["Misc_Allow"]) ? (decimal?)null : (decimal?)row["Misc_Allow"];
						retObj._hRSWeekAllow					 = Convert.IsDBNull(row["HRS_Week_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Week_Allow"];
						retObj._hRSBiweekAllow					 = Convert.IsDBNull(row["HRS_Biweek_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Biweek_Allow"];
						retObj._hRSSmonthAllow					 = Convert.IsDBNull(row["HRS_Smonth_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Smonth_Allow"];
						retObj._hRSMonthAllow					 = Convert.IsDBNull(row["HRS_Month_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Month_Allow"];
						retObj._hRSQuarterAllow					 = Convert.IsDBNull(row["HRS_Quarter_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Quarter_Allow"];
						retObj._hRSSyearAllow					 = Convert.IsDBNull(row["HRS_Syear_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Syear_Allow"];
						retObj._hRSYearAllow					 = Convert.IsDBNull(row["HRS_Year_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Year_Allow"];
						retObj._hRSMiscAllow					 = Convert.IsDBNull(row["HRS_Misc_Allow"]) ? (decimal?)null : (decimal?)row["HRS_Misc_Allow"];
						retObj._allowOrLimit					 = Convert.IsDBNull(row["Allow_or_Limit"]) ? null : (string)row["Allow_or_Limit"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select count of all rows using criteriaquery api
		///This method returns all data rows in the table using criteriaquery api Deductions_Tax_Table_Header
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion
		///</parameters>
		public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_SelectAllByCriteriaCount]";
			command.CommandType = CommandType.StoredProcedure;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				string whereClause = GetSelectionCriteria(listCriterion);
				command.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar, 500, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)whereClause?? (object)DBNull.Value));

				if (staticConnection.State == System.Data.ConnectionState.Closed) staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table Deductions_Tax_Table_Header based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = "[dbo].[ctprDeductions_Tax_Table_Header_UpdateOne]";
			command.CommandType = CommandType.StoredProcedure;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@TaxTabHID", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_taxTabHID?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Tax_Year", SqlDbType.NVarChar, 6, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_taxYear?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Ded_Code", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_dedCode?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Week_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_weekAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Biweek_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_biweekAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Smonth_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_smonthAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Month_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_monthAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Quarter_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_quarterAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Syear_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_syearAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Year_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_yearAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Misc_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_miscAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Week_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSWeekAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Biweek_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSBiweekAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Smonth_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSSmonthAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Month_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSMonthAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Quarter_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSQuarterAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Syear_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSSyearAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Year_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSYearAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@HRS_Misc_Allow", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 18, 2, "", DataRowVersion.Proposed, (object)_hRSMiscAllow?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@Allow_or_Limit", SqlDbType.NVarChar, 1, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_allowOrLimit?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_taxTabHID					 = Convert.IsDBNull(command.Parameters["@TaxTabHID"].Value) ? (Int32?)null : (Int32?)command.Parameters["@TaxTabHID"].Value;
				_taxYear					 = Convert.IsDBNull(command.Parameters["@Tax_Year"].Value) ? null : (string)command.Parameters["@Tax_Year"].Value;
				_dedCode					 = Convert.IsDBNull(command.Parameters["@Ded_Code"].Value) ? null : (string)command.Parameters["@Ded_Code"].Value;
				_weekAllow					 = Convert.IsDBNull(command.Parameters["@Week_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Week_Allow"].Value;
				_biweekAllow					 = Convert.IsDBNull(command.Parameters["@Biweek_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Biweek_Allow"].Value;
				_smonthAllow					 = Convert.IsDBNull(command.Parameters["@Smonth_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Smonth_Allow"].Value;
				_monthAllow					 = Convert.IsDBNull(command.Parameters["@Month_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Month_Allow"].Value;
				_quarterAllow					 = Convert.IsDBNull(command.Parameters["@Quarter_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Quarter_Allow"].Value;
				_syearAllow					 = Convert.IsDBNull(command.Parameters["@Syear_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Syear_Allow"].Value;
				_yearAllow					 = Convert.IsDBNull(command.Parameters["@Year_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Year_Allow"].Value;
				_miscAllow					 = Convert.IsDBNull(command.Parameters["@Misc_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@Misc_Allow"].Value;
				_hRSWeekAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Week_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Week_Allow"].Value;
				_hRSBiweekAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Biweek_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Biweek_Allow"].Value;
				_hRSSmonthAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Smonth_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Smonth_Allow"].Value;
				_hRSMonthAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Month_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Month_Allow"].Value;
				_hRSQuarterAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Quarter_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Quarter_Allow"].Value;
				_hRSSyearAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Syear_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Syear_Allow"].Value;
				_hRSYearAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Year_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Year_Allow"].Value;
				_hRSMiscAllow					 = Convert.IsDBNull(command.Parameters["@HRS_Misc_Allow"].Value) ? (decimal?)null : (decimal?)command.Parameters["@HRS_Misc_Allow"].Value;
				_allowOrLimit					 = Convert.IsDBNull(command.Parameters["@Allow_or_Limit"].Value) ? null : (string)command.Parameters["@Allow_or_Limit"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? TaxTabHID
		{
			get
			{
				return _taxTabHID;
			}
			set
			{
				_taxTabHID = value;
			}
		}

		public string TaxYear
		{
			get
			{
				return _taxYear;
			}
			set
			{
				_taxYear = value;
			}
		}

		public string DedCode
		{
			get
			{
				return _dedCode;
			}
			set
			{
				_dedCode = value;
			}
		}

		public decimal? WeekAllow
		{
			get
			{
				return _weekAllow;
			}
			set
			{
				_weekAllow = value;
			}
		}

		public decimal? BiweekAllow
		{
			get
			{
				return _biweekAllow;
			}
			set
			{
				_biweekAllow = value;
			}
		}

		public decimal? SmonthAllow
		{
			get
			{
				return _smonthAllow;
			}
			set
			{
				_smonthAllow = value;
			}
		}

		public decimal? MonthAllow
		{
			get
			{
				return _monthAllow;
			}
			set
			{
				_monthAllow = value;
			}
		}

		public decimal? QuarterAllow
		{
			get
			{
				return _quarterAllow;
			}
			set
			{
				_quarterAllow = value;
			}
		}

		public decimal? SyearAllow
		{
			get
			{
				return _syearAllow;
			}
			set
			{
				_syearAllow = value;
			}
		}

		public decimal? YearAllow
		{
			get
			{
				return _yearAllow;
			}
			set
			{
				_yearAllow = value;
			}
		}

		public decimal? MiscAllow
		{
			get
			{
				return _miscAllow;
			}
			set
			{
				_miscAllow = value;
			}
		}

		public decimal? HRSWeekAllow
		{
			get
			{
				return _hRSWeekAllow;
			}
			set
			{
				_hRSWeekAllow = value;
			}
		}

		public decimal? HRSBiweekAllow
		{
			get
			{
				return _hRSBiweekAllow;
			}
			set
			{
				_hRSBiweekAllow = value;
			}
		}

		public decimal? HRSSmonthAllow
		{
			get
			{
				return _hRSSmonthAllow;
			}
			set
			{
				_hRSSmonthAllow = value;
			}
		}

		public decimal? HRSMonthAllow
		{
			get
			{
				return _hRSMonthAllow;
			}
			set
			{
				_hRSMonthAllow = value;
			}
		}

		public decimal? HRSQuarterAllow
		{
			get
			{
				return _hRSQuarterAllow;
			}
			set
			{
				_hRSQuarterAllow = value;
			}
		}

		public decimal? HRSSyearAllow
		{
			get
			{
				return _hRSSyearAllow;
			}
			set
			{
				_hRSSyearAllow = value;
			}
		}

		public decimal? HRSYearAllow
		{
			get
			{
				return _hRSYearAllow;
			}
			set
			{
				_hRSYearAllow = value;
			}
		}

		public decimal? HRSMiscAllow
		{
			get
			{
				return _hRSMiscAllow;
			}
			set
			{
				_hRSMiscAllow = value;
			}
		}

		public string AllowOrLimit
		{
			get
			{
				return _allowOrLimit;
			}
			set
			{
				_allowOrLimit = value;
			}
		}

		#endregion
	}
}
